[WIP] fix: flatten theme tree (SHRUI-204)
kufu/smarthr-ui pull request #1256
Opened 2020-12-25 10:21 UTC by wmoai

## Related URL
https://smarthr.atlassian.net/browse/SHRUI-204

## Overview
`theme` の構造を整理します。

## What I did
### `theme`の構造変更
- `theme.palette`を非推奨にして、`theme.color`に役割を移譲
- `theme.size`を非推奨にして以下に役割を移譲
  - `theme.fontSize`
    - `pxToRem` を含む（`rem`は`font-size`に関わる概念なため）
  - `theme.spacijng`
  - `theme.breakPoint`
- `theme.frame`を非推奨にして以下に役割を移譲
  - `theme.border`
  - `theme.radius`

### やってないこと
- 各コンポーネントにおける、今回非推奨になった`theme`の使用箇所の置き換えはかなり量が多く、まとめて行うとコンフリクトの懸念があるため別PRで対応を行う
- プリミティブトークンの導入は、対応意図を分かりやすくするために別PRで行う

## Capture

2021-01-08 01:52 UTC, uknmr commented on src/themes/createTheme.ts
> +  fontSize?: FontSizeProperty
最終的に作用するのはフォントサイズではなく、テキストサイズのため `textSize` かなと思いました!

2021-01-08 01:55 UTC, uknmr commented on src/themes/createTheme.ts
> +  breakPoint?: BreakPointProperty
`breakpoint` は単語として存在するのでキャメルにしない方がよさそう。

2021-01-08 02:27 UTC, uknmr requested changes
Border 周りを確認した。
- default 定数を明示するとよさそう
- ショートハンドが `default` になってて名前と実態にズレを感じるので可能なら `shorthand` などとしたい

2021-01-08 02:27 UTC, uknmr commented on src/themes/createBorder.ts
> +  default: `${lineWidth} ${lineStyle} ${lineColor}`,
`default` を deprecated して `shorthand` とかにしたさ。

2021-01-08 02:27 UTC, uknmr commented on src/themes/createBorder.ts
> +const lineColor = defaultColor.BORDER
```suggestion
const defaultLineWidth = '1px'
const defaultLineStyle = 'solid'
const defaultLineColor = defaultColor.BORDER
```

2021-01-08 02:27 UTC, uknmr commented on src/themes/createBorder.ts
> +  default: `${lineWidth} ${lineStyle} ${lineColor}`,
```suggestion
  default: `${defaultLineWidth} ${defaultLineStyle} ${defaultLineColor}`,
```

2021-01-08 02:27 UTC, uknmr commented on src/themes/createBorder.ts
> +      default: `${lineWidth} ${lineStyle} ${color}`,
`defaultBorder.default` あるので不要そう

2021-01-08 02:36 UTC, wmoai commented on src/themes/createBorder.ts
> +      default: `${lineWidth} ${lineStyle} ${color}`,
このコードはちょっとわかりにくいのですが、 `default` に対して `userColor.BORDER` の設定を反映させるためのものなので必要だと思われます

2021-01-08 02:51 UTC, uknmr commented on src/themes/createTheme.ts
> +  fontSize?: FontSizeProperty
`fontSize: ${theme.textSize.M}` より `fontSize: ${theme.fontSize.M}` の方が開発側の変換コストが低そうなので `fontSize` でいく。

2021-01-08 07:47 UTC, uknmr commented on src/themes/createBorder.ts
> +      default: `${lineWidth} ${lineStyle} ${color}`,
ホントだ! 理解しました🙏

2021-01-15 00:24 UTC, wmoai commented on src/themes/createTheme.ts
> +  breakPoint?: BreakPointProperty
8ac829f で対応しました

2021-01-15 00:24 UTC, wmoai commented on src/themes/createBorder.ts
> +  default: `${lineWidth} ${lineStyle} ${lineColor}`,
f2204ec で対応しました

2021-01-15 00:24 UTC, wmoai commented on src/themes/createBorder.ts
> +const lineColor = defaultColor.BORDER
6a15fb4 で対応しました

2021-01-15 00:25 UTC, wmoai commented on src/themes/createBorder.ts
> +  default: `${lineWidth} ${lineStyle} ${lineColor}`,
6a15fb4 で対応しました

2021-01-20 01:25 UTC, nabeliwo submitted a review, later dismissed
LGTM :tada:

2021-01-20 01:25 UTC, nabeliwo commented on src/themes/createColor.ts
> +}
[IMO] この型定義どうにかならないかなと以前から考えていたのですが、 `type ColorProperty = Partial< CreatedColorTheme >` の形でいけるということに気づきました。 color の場合はそこからさらにいらない 関数を Omit したりする必要はあったり、 interface から type alias に変わっちゃうというあれもあるのですが…
ただの書き方の話なのでスルーで問題ないです

2021-01-20 03:01 UTC, wmoai commented on src/themes/createColor.ts
> +}
なるほど。
本質的には `ColorProperty` と `CreatedColorTheme` 型はどちらも「色一式にアクセスできる型」の派生であると言えるので、その型を独立して定義するのがいいかもしれないと思いました。具体的には以下のようなイメージです。

```ts
type Palette = {
  TEXT_BLACK: string
  // ...
  OUTLINE: string
}

export type ColorProperty = Partial<Palette>

export type CreatedColorTheme = Palette & {
  hoverColor: (value: string, darkenAmount?: 0.05 | 0.15) => string
  disableColor: (value: string) => string
}
```

また、これだと interface から type 宣言に変わってしまうわけですが、両者の違いはほぼパーシャルクラス機能を使えるかどうかだけであり、これらの想定される使途ではパーシャルクラス機能が必要になることは無いと思われるので、新定義を追加する今回のタイミングで type 宣言にしてしまっても良いかもしれないと思いました。
（逆に後々 interface から type 宣言に変えようとすると BREAKING CHANGE になりうる）

2021-01-20 03:26 UTC, nabeliwo commented on src/themes/createColor.ts
> +}
めっちゃ綺麗にまとまった感があります！！
であればこのタイミングでやっていただけますとありがたいです！

2021-01-20 06:15 UTC, wmoai commented on src/themes/createColor.ts
> +}
対応しました！ ecf897a

2021-01-20 06:32 UTC, nabeliwo submitted a review, later dismissed
LGTM 🎉

2021-01-25 07:07 UTC, nabeliwo commented
https://github.com/kufu/smarthr-ui/pull/1315 がマージされたら取り込んで対応する必要あり

2021-02-02 02:08 UTC, wmoai commented
#1315 の HEAD カラー追加しました
14d4ae3

2021-02-08 03:23 UTC, nabeliwo approved these changes
LGTM 🎉

2021-02-24 03:50 UTC, uknmr approved these changes

2021-02-24 03:52 UTC, merged