Add floatArea component
kufu/smarthr-ui pull request #1270
Opened 2021-01-04 03:37 UTC by kgsi

## Related URL

https://smarthr.atlassian.net/browse/SHRUI-141

## Overview

* SmartHR 内で使われ始めたFloatAreaなるUIを新しく作る

## What I did

* `FloatArea`componentの追加

## 懸念点

- エラーテキストに文字数制限をかけていないので、あまりに文字数が多くなるとレイアウトが崩壊するので、制限をかけたほうがよい？

## Capture

![image](https://user-images.githubusercontent.com/4032232/103498819-5b0d0c80-4e89-11eb-9370-4fc8148dfbe8.png)

2021-02-01 03:29 UTC, nabeliwo requested changes
こちらレビューが遅れて大変申し訳ないです 🙏 
細かい点が多いですがレビューしたのでご確認お願いします！

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/README.md
> +# FloatArea
[MUST] こちら追記お願いします！

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/FloatArea.tsx
> +interface Props {
[IMO] 他のオブジェクトを表す型が type alias を使っているのに対してこれだけ interface なのが気になりました！特に理由がなければ type で統一で良いかと

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/FloatArea.tsx
> +function exist(value: any) {
[IMO] helper を別ファイルで用意しているので、この関数も helper に移動して良さそうです

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/FloatAreaHelper.ts
> +export const validateElement = (primary?: Primary, secondary?: Secondary) => {
[MUST] primary はコンポーネント側で必須の props なのでこの関数でも optional ではなく必須で良さそうです

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/FloatArea.tsx
> +export type errorIcons =
[MUST] これは export する必要なさそうです。あと型の名前は UpperCamelCase でお願いします 🙏  そしてこの型の名前的には複数形にする必要はなさそうです

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/FloatArea.tsx
> +  | FunctionComponentElement<ComponentProps<typeof FaExclamationCircleIcon>>
[ask] errorIcons は FaExclamationTriangleIcon と FaExclamationCircleIcon 以外のアイコンは使わない想定で間違い無いでしょうか？

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/FloatArea.tsx
> +  zIndex?: number
[IMO] この定義、 Props 側の型定義と被っているので Props の top, right, botttom, left, zIndex を消して、 `type Props = StyleProps & {}` という形にするのが良さそうです！

2021-02-01 03:29 UTC, nabeliwo commented on src/components/FloatArea/FloatArea.tsx
> +  | FunctionComponentElement<ComponentProps<typeof SecondaryButtonAnchor>>
[IMO] この定義を書いても PrimaryButton か PrimaryButtonAnchor に絞れないかなと思っていて、そして validateElement があるので渡してほしい element の明示もできているので Props の定義としては ReactNode で良いのではないかと思ったのですが、いかがでしょうか？

2021-02-08 09:42 UTC, kgsi commented on src/components/FloatArea/FloatArea.tsx
> +  | FunctionComponentElement<ComponentProps<typeof FaExclamationCircleIcon>>
現状、こちらはこの2つのみで想定しています！

2021-03-08 11:23 UTC, nabeliwo submitted a review, later dismissed
LGTM 🎉

2021-03-08 11:23 UTC, nabeliwo commented on src/components/FloatArea/README.md
> +  const [visible, setVisible] = useState(true)
ここの useState, 謎かもしれないです！コピペの名残かな
むしろ下で使っているボタンやアイコンのコンポーネントの import をしてほしいかも

2021-03-08 11:23 UTC, nabeliwo commented on src/components/FloatArea/README.md
> +| errorText   |          | **() => void**                                        | -            | If false, text is not display.
errorText は string ですかね。あと description が違うかもです！

2021-03-10 01:27 UTC, kgsi commented on src/components/FloatArea/README.md
> +  const [visible, setVisible] = useState(true)
名残ですね、こちらも修正しました！！

2021-03-10 01:28 UTC, uknmr commented on src/components/FloatArea/FloatArea.tsx
> +  | FunctionComponentElement<ComponentProps<typeof FaExclamationCircleIcon>>
Triangle と Circle はどう使い分けますか?

2021-03-10 01:28 UTC, nabeliwo approved these changes

2021-03-10 01:41 UTC, uknmr commented on src/components/FloatArea/FloatArea.tsx
> +  width: 16px;
pxぇ

2021-03-10 01:43 UTC, uknmr commented on src/components/FloatArea/FloatArea.tsx
> +  width: 16px;
メッセージの文字サイズが通常であれば記述自体が不要そう。
`p > svg` になって大きさは継承された記憶。

2021-03-10 04:00 UTC, nabeliwo commented on src/components/FloatArea/FloatArea.tsx
> +}
これだと right が number なので right に0を入れたい時に 0px が入ってくれないですかね

2021-03-10 04:16 UTC, uknmr commented on src/components/FloatArea/FloatArea.tsx
> +}
確かにぃ!
right / left は指定する可能性ないかも。

2021-03-10 08:15 UTC, kgsi commented on src/components/FloatArea/FloatArea.tsx
> +      font-size: ${pxToRem(font.SHORT)};
この件だけ、全体的にはエラーメッセージが未だSHORTなので、ここだけサイズを替えても部分最適化になっちゃうので、やるとしたら一気に対応したいです！

2021-03-10 11:17 UTC, kgsi commented on src/components/FloatArea/FloatArea.tsx
> +}
記述方法はuさんの書き方がシンプルで好みだったので書き換えました。numberのチェックは以前のexistに戻してます。

> right / left は指定する可能性ないかも。
脳内シミュレーションしてみましたが、classNameでカバーできるケースが殆どで、強く必要が無い気がしてきたので削除してみました。必要になったらまた考えましょう！

2021-03-10 11:38 UTC, uknmr commented on src/components/FloatArea/FloatArea.tsx
> +  | FunctionComponentElement<ComponentProps<typeof FaExclamationCircleIcon>>
メモ： 旧画面が Circle、新画面が Triangle で互換性を保つためにある

2021-03-10 12:11 UTC, kgsi commented on src/components/FloatArea/FloatArea.tsx
> +  margin-right: 0;
TertiaryArea外しても成り立ちそう。無駄なので削除しました！

2021-03-10 12:30 UTC, merged