[WIP] feat: implement FormGroup component
kufu/smarthr-ui pull request #1297
Opened 2021-01-19 03:07 UTC by diescake

## Related URL

https://smarthr.atlassian.net/browse/SHRUI-325

## Overview

- kbn-zero-re から FormGroup コンポーネントをバックポートしたい
- 一旦 deploy-preview でシェアしつつモミたい

## What I did

- kbn-zero-re から FormGroup コンポーネントをコピペ

## Capture

T.B.D.

2021-02-09 03:38 UTC, wmoai reviewed
レビュー遅れてすみません！いくつかコメントしました！

2021-02-09 03:38 UTC, wmoai commented on src/components/FormGroup/FormGroup.tsx
> +`
[IMO] こちら、`Heading` コンポーネント側に `disabled` オプションを追加するのではなく、ここで Extending styles すれば良いのでは？と思いました。

```suggestion
const Title = styled(Heading)<{ themes: Theme }>`
  display: inline-block;
  &.disabled {
    color: ${({ themes }) => themes.palette.TEXT_DISABLED};
  }
`
```

2021-02-16 03:12 UTC, diescake commented
うおお、ありがとうございます！！
そして、全くコメントに気づいておらずすみません！😭

のちほど対応していきます！

2021-02-18 10:22 UTC, diescake commented
rebase and force pushed

2021-02-18 10:28 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +    <Wrapper className={`${className} ${disabledClass}`} themes={theme}>
ホンマや…😭

![image](https://user-images.githubusercontent.com/5195381/108343589-7789bc00-721f-11eb-88eb-45d91a0d481c.png)

2021-02-18 10:32 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +    <Wrapper className={`${className} ${disabledClass}`} themes={theme}>
Fixed in 5fd1f023cebd9249483262141780313eb23e43ed

2021-02-18 10:58 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +                </LabelItem>
完全に 🦀  なので対応しました！！
ついでに LabelItem という名称が StatusLabel そのものという意図が伝わりにくいと思ったのでリネームしています。

Fixed in 0cc1345ec1398282180fb12e5a126e4b604c6abf, cb232154b6df6b647cc9b8a76f6efd4ff6eb010b

2021-02-18 11:24 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +`
おっ、👆で style 当てられます？ 🤔 

割と sytled-components の Extending styles ふんいきでやっていてアレなんですが、Wrapper の各種 color の style の方が詳細度が高いと思っていて外から当てるのは難しいと思っていました！

https://github.com/kufu/smarthr-ui/blob/master/src/components/Heading/Heading.tsx#L48

2021-02-18 11:25 UTC, diescake commented
@wmoai 

レビューありがとうございます！！
指摘の修正しつつコメントしていますので再レビューお願いします！🙏🙏

2021-02-18 11:58 UTC, wmoai commented on src/components/FormGroup/FormGroup.tsx
> +`
Suggested change の例だと `Title` に `className={disabled ? 'disabled' : undefined}` を設定すれば style は当たるようです。
この場合では、`&.disabled` と `Title` 側の `&.blockTitle` の詳細度は同じになっていますが、Extending styles した `&.disabled` が後勝ちしているようです。

ちなみに Extending styles 側が詳細度で負ける場合は `&&.disabled` といった感じで `&` の数で詳細度を上げてやっても良いかもしれません。

2021-02-18 21:52 UTC, uknmr commented
label と入力要素の紐付けしてほしい!

2021-02-19 03:12 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +`
>ちなみに Extending styles 側が詳細度で負ける場合は &&.disabled といった感じで & の数で詳細度を上げてやっても良いかもしれません

なるほど…！

`.hoge.hoge.disabled` みたいな感じになるんですね。
そもそもですが、同じクラス重ねて詳細度あげることができるのね… CSS 力…

2021-02-19 03:16 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +`
wmoai san のコメントの通りで無事適用できたので修正しました！
Header コンポーネントへの修正は revert してますー

Reverted in 91044b04b6e7bc51cb2fb1cb1a2afab736df8575
Fixed in b167fb7280507eb66682fc01f24f695194ae2336

2021-02-19 03:23 UTC, wmoai commented on src/components/FormGroup/FormGroup.tsx
> +`
:bow: :bow: :bow:

2021-02-19 03:32 UTC, diescake commented
@uknmr 

>label と入力要素の紐付けしてほしい!

オッ、label に htmlFor を渡せるようにすると良さそうですかね？ 🤔 
FieldSet と違ってFormGroup 自体は入力要素(Input) を抱えていないので、紐付けはユーザー側でやる感じになりそうですー

2021-02-19 03:39 UTC, diescake commented
あ、違う。👇の Body に紐付けすると良いのかな？

https://github.com/kufu/smarthr-ui/pull/1297/files#diff-e7cc77f9a0f7105e687ca418cba27f279f9162ddac695b46b2724db08f88364eR69

2021-02-19 04:30 UTC, wmoai commented
wrapper の id を `htmlFor` で参照してもラベルとして機能してくれてない感じがするので、外から `htmlFor` を渡せるようにするのが良さそうですね・・・

2021-02-19 08:20 UTC, uknmr commented
ちゃんとソース見てなくて申し訳ないんですが、 `<label>{children}</label>` ではだめかしら?
（複数 Input 来たときにどうするのか、は別の問題としてある）

2021-02-19 11:58 UTC, diescake commented
@uknmr @wmoai 

すみません！ちょっと理解が追いついていない部分がありそうなので、
月曜日か水曜日くらいにちょっとシュッと話をさせてください！🙏

2021-03-11 05:16 UTC, masuP9 commented
続きが気になる 👀

2021-03-11 06:08 UTC, uknmr commented
他プロジェクトで似たような fieldset > legend / label 両対応実装をし始めています。
https://github.com/kufu/utsuwa/blob/master/client/src/app/components/ui/FormGroup/FormGroup.tsx

2021-03-29 12:44 UTC, diescake commented
rebase and force pushed

2021-03-30 02:26 UTC, diescake commented
最新のコードベースで deprecated になっていた theme の参照を修正
e138ff51a59546fe7147f22bf6af684903a30175

2021-03-30 03:39 UTC, diescake commented
@wmoai @uknmr 

以下修正しましたので確認お願いします！！🙏

最新のコードベースで deprecated になっていた theme の参照を修正
0f141a944c384e83d0c054117ab1612665fdb765

children を label 要素内に移動してスタイル微調整
e138ff51a59546fe7147f22bf6af684903a30175

2021-04-01 05:43 UTC, wmoai submitted a review, later dismissed
LGTM 🎉

2021-04-05 08:29 UTC, uknmr requested changes
label 内の div 配置は invalid なため修正お願いします。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/label

2021-04-05 08:29 UTC, uknmr commented on src/components/FormGroup/FormGroup.tsx
> +const Wrapper = styled.div<{ themes: Theme }>`
`Wrapper` と `Label` を分けてる意味がなさそうに見えました!

2021-04-05 08:29 UTC, uknmr commented on src/components/FormGroup/FormGroup.tsx
> +const TitleWrapper = styled.div`
label 内は記述コンテンツしか書けないので、label 内は基本 span 🥺

2021-04-05 08:29 UTC, uknmr commented on src/components/FormGroup/FormGroup.tsx
> +const Title = styled(Heading)<{ themes: Theme }>`
label 内のラベルを見出しに見せたい場合は `role=heading` と `aria-level` 指定するしかない? @masuP9

2021-04-05 08:29 UTC, uknmr commented on src/components/FormGroup/FormGroup.tsx
> +      vertical-align: middle;
`vertical-align: middle;` で縦位置中央にならないことがあって、親（ここでは `ErrorMessage`）で `flex` 指定したいと思うなど。

2021-04-05 08:29 UTC, uknmr commented on src/components/FormGroup/FormGroup.tsx
> +    return css`
```suggestion
const HelpMessage = styled.span<{ themes: Theme }>`
  ${({ themes }) => {
    const { fontSize, spacing } = themes

    return css`
      display: block;
```

2021-04-05 08:29 UTC, uknmr commented on src/components/FormGroup/FormGroup.tsx
> +    return css`
```suggestion
const ErrorMessage = styled.span<{ themes: Theme }>`
  ${({ themes }) => {
    const { fontSize, spacing } = themes

    return css`
      display: block;
```

2021-04-05 08:29 UTC, uknmr commented on src/components/FormGroup/FormGroup.tsx
> +const Body = styled.div<{ themes: Theme; margin: innerMarginType }>`
```suggestion
const Body = styled.span<{ themes: Theme; margin: innerMarginType }>`
```

2021-04-09 06:55 UTC, masuP9 commented on src/components/FormGroup/FormGroup.tsx
> +const Title = styled(Heading)<{ themes: Theme }>`
`styled(Heading)` ならデフォルトで `h1` なので見出しにはなると思ってました！titleTag 的な props で tag の操作ができたほうがよさそう！

2021-04-12 06:24 UTC, diescake commented
コメントあざます！みていきます！！！

2021-04-12 10:31 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +const TitleWrapper = styled.div`
修正しました！

Fixed in bc152a6c2b88d5993cc6842d2e5f92bc3b125201

2021-04-12 10:31 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +      vertical-align: middle;
なるほど！修正しました！！

Fixed in 7a7089eff5bd5509eb1867bb5151314e2a4bf8da

2021-04-12 10:32 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +const Wrapper = styled.div<{ themes: Theme }>`
Wrapper 処しました！

Fixed in 1f3f077cd67b96a32cfd96b6fff3859628ac8194

2021-04-12 10:38 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +const Title = styled(Heading)<{ themes: Theme }>`
@uknmr @masuP9 

ふむふむ、`titleTag` を props に追加して外から Heading の `tag` を変更できるようにしました！

Fixed in 6f54307469fbc4ed677f8c9d968dcc5beb11eb11

2021-04-13 00:31 UTC, diescake commented on src/components/FormGroup/FormGroup.tsx
> +const Title = styled(Heading)<{ themes: Theme }>`
>せっかく titleTag を渡してもらったんですが、label 内に見出し置けないので span のままでよさそう、となっています :glenn_pray_mochimochi:

👆此奴対応しました！
コンポーネントは Heading のまま `tag` を `span` 決め打ちで渡していますー

Fixed in ad5daa7f9f6f765bc2fa10f1920e7705a1318b26

2021-04-13 01:52 UTC, uknmr approved these changes
LGTM:+1:

2021-04-13 02:42 UTC, diescake commented
レビューあざます！！！
マージしますー

2021-04-13 02:44 UTC, merged