feat: add handling when Window object is not supported
kufu/smarthr-ui pull request #1312
Opened 2021-01-25 00:55 UTC by kgsi

## Related URL
- 特になし

## Overview
- gatsbyやnext.jsなどのフレームワークでbuildしようとすると、`window`objectが使えないのでbuild errorが起きる
  - https://www.gatsbyjs.com/docs/debugging-html-builds/
- フレームワーク側で対処しようとすると、一時的なパッチ処理となってしまうので根本を修正したい

## What I did

- `window`objectが`undefined`な場合、uaに空文字列を返すような処理を追加
- `useEffect`などに書いている場合はssr対象外となるので、それらは未書換え
  - 参考: https://takumon.com/error-about-window-is-not-available-during-server-side-rendering-gatsby

## Capture

2021-01-25 01:52 UTC, negiandleek reviewed
`typeof window !== 'undefined'`じゃないと ReferenceErrorになりそう

2021-01-25 02:00 UTC, kgsi commented
> typeof window !== 'undefined'

@negiandleek あ！そうか、修正してみましたが、こんな感じですかねー？

> const ua = typeof window !== `undefined` ? window.navigator.userAgent.toLowerCase() : ''

2021-01-25 03:33 UTC, diescake commented
>gatsbyやnext.jsなどのフレームワークでbuildしようとすると、windowobjectが使えないのでbuild errorが起きる

なるほど…！！

2021-01-25 03:42 UTC, diescake commented on src/libs/ua.ts
> +const ua = typeof window !== `undefined` ? window.navigator.userAgent.toLowerCase() : ''
```suggestion
const ua = typeof window !== 'undefined' ? window.navigator.userAgent.toLowerCase() : ''
```

超絶細かいですが、
変数展開がない純粋な文字列はシングルクオートで統一されてそうです！

2021-01-25 03:47 UTC, diescake commented on src/libs/ua.ts
> +const ua = typeof window !== `undefined` ? window.navigator.userAgent.toLowerCase() : ''
それとこれは IMHO です！

`const ua = ''` のときでも `ua` を参照する下位のユーティリティ関数が、何かしらの値を返すと思うんですが、
それによって予期せぬ動きとならないように、

```ts
const ua = typeof window !== 'undefined'`
```

 のときは、

```ts
const isId = false
const isSp = false
const isTablet = false
const isPc = true
const isTouchDevice = false
```

みたいな、無難な値を固定値で返すようにしておくとハマりにくいかもしれません！

2021-01-26 07:31 UTC, kgsi commented on src/libs/ua.ts
> +const ua = typeof window !== `undefined` ? window.navigator.userAgent.toLowerCase() : ''
@diescake レビューありがとうございます！！記号の件は直しておきました！
IMHOの件ですが確かに..!
ちょっと考えましたが、そもそも空文字を返してるのがわかりにくいので、'SSR' を返すようにしてみました（もしくは'undefined'とかでも）その値が返ってくるのであれば、isId、isSpも返ってくる値も`false`であると予測がつくかなと。

```
window.navigator !== 'undefined' ? window.navigator.userAgent.toLowerCase() : 'SSR'
```

あとは今回のスコープに含めないですが、useEffect内であればSSR/SSG時でもwindowオブジェクトのエラーが出ないので、最終的には独自フック化してもよいのかなと（そこまでやるかでいえば、まだその時期ではないと思ってますが）
https://stackoverflow.com/questions/59494037/how-to-detect-the-device-on-react-ssr-app-with-next-js

2021-01-26 09:02 UTC, nabeliwo commented on src/libs/ua.ts
> +const ua = typeof window !== `undefined` ? window.navigator.userAgent.toLowerCase() : ''
横から失礼します！

> useEffect内であればSSR/SSG時でもwindowオブジェクトのエラーが出ないので、最終的には独自フック化してもよいのかな

現象としてはその通りなのですが、 useEffect はアプリケーションのライフサイクルの中で変化する値に対して使うというものという点と、 useEffect はレンダリング後に呼ばれるので最初に ua がない状態のものがレンダリングされてその後に正しい ua を元にしたものが描画されるという現象が起きそうというのがあって、そこから考えると ua を Hooks で取得するのはちょっと違うかもなと思いました！
ただの感想です！ 🙏

2021-01-26 09:20 UTC, kgsi commented on src/libs/ua.ts
> +const ua = typeof window !== `undefined` ? window.navigator.userAgent.toLowerCase() : ''
@nabeliwo 
aaaa、、そもそもトリッキーな方法だということを念頭に置いてなかったで、ご指摘ごもっともです:bow:
現状の回避策も暫定的ではあるので、折をみて詰めていけたらと思います:pray:

2021-01-26 10:30 UTC, diescake approved these changes
修正あざます！ LGTM です！！ 🎉 🎉

2021-01-26 10:39 UTC, diescake commented on src/libs/ua.ts
> +const ua = typeof window !== `undefined` ? window.navigator.userAgent.toLowerCase() : ''
@kgsi 

あざます！
useEffect については @nabeliwo san と同意見でございますー🙏

2021-01-27 01:29 UTC, negiandleek submitted a review, later dismissed

2021-02-01 03:37 UTC, nabeliwo requested changes

2021-02-01 03:37 UTC, nabeliwo commented on src/libs/ua.ts
> +  typeof window.navigator !== 'undefined' ? window.navigator.userAgent.toLowerCase() : 'SSR'
[MUST] SSR 時には window オブジェクト自体がないので、 `window.navigator` にしてしまうとエラーになってしまうので、 `const ua = typeof window !== 'undefined' ? window.navigator.userAgent.toLowerCase() : 'SSR'` が正しいかと思います！

2021-02-08 07:55 UTC, kgsi commented on src/libs/ua.ts
> +  typeof window.navigator !== 'undefined' ? window.navigator.userAgent.toLowerCase() : 'SSR'
@nabeliwo ありがとうございます！！こちら修正しました:pray:

2021-02-08 07:57 UTC, nabeliwo approved these changes
LGTM 🎉

2021-02-09 05:16 UTC, merged