fix: Dialog: suppressing scroll
kufu/smarthr-ui pull request #1511
Opened 2021-04-13 06:23 UTC by AtsushiM

## Related URL

## Overview

- Dialog の表示・非表示でbodyのscrollが切り替えられてしまい、画面幅が変わることでガタツキが発生してしまう場合がある
- styleに頼らずscriptでscrollを制御することでガタつかないようにしたい

## What I did

- mousewheel, touchmove イベントでscrollをキャンセルする処理を追加
  - passive を false にすることでjsによるブロッキングを回避しました 

## Capture

2021-04-13 06:34 UTC, masuP9 requested changes
ガタつきテストできる Story があるとよいかと思いました！

2021-04-13 06:34 UTC, masuP9 commented on src/components/Dialog/DialogContentInner.tsx
> +const removeDocumentEventLister = document.removeEventListener.bind(document)
document 全体にしちゃうと、Dialog の中のスクロールも抑制されちゃうので、Portal じゃなくて React の root node を対象にしないとダメそうです！

2021-04-13 06:49 UTC, AtsushiM commented on src/components/Dialog/DialogContentInner.tsx
> +const removeDocumentEventLister = document.removeEventListener.bind(document)
🦀 ですね。
一旦WIPにしておくか...

2021-04-22 00:33 UTC, AtsushiM commented
https://github.com/kufu/smarthr-ui/pull/1532 での対応のほうが良さそうなのでこちらはcloseします。

2021-04-22 00:33 UTC, closed without merging