feat: add Link component
kufu/smarthr-ui pull request #1529
Opened 2021-04-20 04:22 UTC by AtsushiM

## Related URL

## Overview

- prefix, suffix などのstyleのバラツキやCmd + Click時の挙動などを統一するため、TextLinkコンポーネントを作りたい

## What I did

## Capture

2021-04-26 08:12 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +      color: ${palette.TEXT_LINK};
この辺りを props で切り替えられるようにしたい。

```css
text-decoration: underline;
text-underline-position: under;
``

2021-04-26 08:12 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +`
擬似擬似コードですが、Wrapper 側にこんな感じで書くと見通しがよくなりそうです。

```
StyledAnchor {
  > * + * {
    margin-left: ${size.pxToRem(size.space.XXS)};
  }
}
```

2021-04-27 04:43 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +  href,
@uknmr 通常の a ではありえるのでそれに習っている感じですね。
例えばリンクの見た目でjs発火させたい場合とか...
このような場合、smarthr-uiの方針としてどうするか、というのを決めてしまっても大丈夫か、が論点かも。

2021-04-27 04:44 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +      color: ${palette.TEXT_LINK};
propsでの切り替えってstyled-componentsによる拡張と記法がブレてしまいそうで微妙な気が...
例えば `エラーの場合`　みたいなpropならわかるんですが `右寄せ` `アンダーラインなし`　みたいなpropははやしたくないかも？

2021-04-27 04:46 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +`
↑だと children 内に何が入ってくるかわからないため、影響範囲が不定になってしまいそうです。

2021-04-27 05:25 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +`
なるほど。prefix と suffix を Icon に絞ってもよさそう。
他の用途がありそうですか?

2021-04-27 05:25 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +      color: ${palette.TEXT_LINK};
`装飾なし` みたいな props はどうですか?

2021-04-27 05:25 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +  href,
リンク空の場合は `e.preventDefault()` と `e.stopPropagation()` を実行した上で `onClick` に渡ってきた関数を実行、とできないかしら。

2021-04-27 05:25 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +  href,
意図せずキーボードフォーカスできない状態、を未然に防ぎたい意図です!

2021-04-28 00:01 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +`
基本的に用途はアイコンになると思います。
ただ、smarthr-uiが提供しているIconとは限らないかと。

2021-04-28 00:09 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +      color: ${palette.TEXT_LINK};
ニュアンスが難しいんですが `装飾なし`　は見た目、スタイルの話で `エラーの場合` は状態を表していると考えています。

まとめると

- `エラーという状態` を `borderを赤くする` と定義するのはコンポーネントの責務として良さそう。
- `装飾なし` は `見た目` の話なのでそれならstyled-components で調整を一意にしたいかも
- 例えば  `リンクを一時的に遷移できない状態にしたい。そのために装飾なし（underlineをけしたい）` なら  `disabled` みたいなpropsを作るのが良いかも

2021-04-28 00:13 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +  href,
aの代わりに〜みたいな感じだったんでなるべくaのデフォルトの挙動を残してる方針でしたが `意図せずキーボードフォーカスできない状態、を未然に防ぎたい意図` は良さそう。

> リンク空の場合は e.preventDefault() と e.stopPropagation() を実行した上で onClick に渡ってきた関数を実行、とできないかしら。

これって要するに `hrefがundefinedで渡ってきたら、内部的には空文字にしてhref属性を設定したい。そのうえでonClickをいい感じにする` と認識してるんですがあってます？

2021-04-28 07:46 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +  href,
あってます!
が、React で `undefined` を渡してしまうと href が存在しないことになるので、tabbable ではなくなってしまいます。
空文字 "" の場合にいい感じにしたい!
参考： https://allyjs.io/data-tables/focusable.html

2021-04-28 07:55 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +      color: ${palette.TEXT_LINK};
あ! ちょっと勘違いしていましたごめんなさい!
text-decoration はデフォルトで入ってますね（だいたい user agent style で入ってるはず）。
入ってないと思って入れたい、みたいな話をしていました!!!

リンクに `disabled` は不要だと思います!

`text-underline-positoin: under;` は文字見やすくなると思うので入れたい。

参考： https://caniuse.com/mdn-css_properties_text-underline-position

2021-04-28 07:56 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +      color: ${palette.TEXT_LINK};
あ、デフォで↑のstyleを当てはめたいって話だったのか。
それなら賛成です！

2021-04-28 07:56 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +`
あくまでテキストのリンクなのである影響範囲が不定にならないようドキュメントなどに、基本アイコンしか想定していない旨を書いておけばいいかなと思いました!

2021-04-28 08:55 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +  href,
> React で undefined を渡してしまうと href が存在しないことになるので、tabbable ではなくなってしまいます。

多分これも認識合ってて、 `<SHRA data-hogehoge="fuga">link</SHRA>` と指定されたら `<a href data-hogehoge="fuga">link</a>` みたいにする、という認識でした。あってそうです？

2021-04-28 12:29 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +  href,
あーなるほど、認識あってます!

2021-05-03 09:59 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +  href,
内部で空文字指定するようにして実装できました。
href属性を明確になくしたい場合は `href={null}` 指定すれば消えることも確認。
明確にやりたい場合なさそうだし `noHref={true}` みたいなオプションは用意しなくていいかな...

2021-05-10 01:16 UTC, uknmr approved these changes
ひとつ imo なコメント入れましたが、LGTM 👍

2021-05-10 01:16 UTC, uknmr commented on src/components/TextLink/TextLink.stories.tsx
> +`
`TextLink` 間の間隔を `<br />` で表したくない気がする。

```suggestion
const Wrapper = styled.div`
  margin: 24px;
  
  > * + * {
    margin-top: 16px;
  }
`
```

2021-05-10 01:23 UTC, uknmr requested changes
あ、ごめんなさい、嘘だった。

別タブで開く場合のアイコンを縛る、かつその場合はアイコンに `aira-label` で別タブで開くよ、を伝えたいと思いました!

参考： https://github.com/kufu/smarthr-ui/blob/c9505de9d38d365a545c7ac3c3ed3e4ae099debb/src/components/MessageScreen/MessageScreen.tsx#L46-L48

2021-05-11 00:05 UTC, AtsushiM commented
@uknmr `target="_blank"`  指定された場合、suffixにExternalIcon&aria-labelを指定するのは良さそうなんですが
`target="_blank" suffix={<HogeIcon />}  aria-label="fugafuga"` の場合はどうしましょう。
`blank指定の場合はsuffix, aria-labelにデフォルト値を設定、明確に指定された場合は指定された値を使う` で良いです？（あまりないパターンだとは思いますが）

2021-05-11 06:09 UTC, uknmr commented
そうですね。明確に指定された場合は指定された値を使う、でいいと思います!

2021-05-14 11:42 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +      color: ${palette.TEXT_LINK};
`text-decoration: underline;` は実装には入っていないので、既存と同じようにアプリ側でリセットを入れてるアプリでは下線は表示されません:+1:

2021-05-24 03:29 UTC, uknmr approved these changes
LGTM:+1:

2021-05-24 04:19 UTC, wmoai reviewed
コメントしました！

2021-05-24 04:19 UTC, wmoai commented on src/components/TextLink/TextLink.tsx
> +  href = '',
`<TextLink onClick={() => {}} >`みたいな時に、 `href` が空文字で設定されることで想定外の遷移が発生するようです。

関連する議論で、このコンポーネントが既存の `a` タグと動作が異なる場合、どういう違いがあるのかがわかる記述があったほうがよい気がしました。

2021-05-24 04:19 UTC, wmoai commented on src/components/TextLink/TextLink.tsx
> +const generateOnClick = (href?: string, onClick?: (e: React.MouseEvent) => void) => {
[IMO] 修正する必要があるかは微妙ですが、コンポーネント内で呼ぶ関数をここで記述すると毎回実行されてしまうので、この処理をコンポーネント内に移して `useMemo()` にすれば多少効率的になるかなと思いました。

2021-05-24 04:19 UTC, wmoai commented on src/components/TextLink/TextLink.tsx
> +      margin-left: ${size.pxToRem(size.space.XXS)};
同じく `spacingByChar`

2021-05-25 00:17 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +const generateOnClick = (href?: string, onClick?: (e: React.MouseEvent) => void) => {
suffixの一緒にuseMemoで効率化してみました

2021-05-25 00:25 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +  href = '',
@wmoai https://github.com/kufu/smarthr-ui/blob/da0c7d73f26f8874929ba3c837ffc9a5643c94b2/src/components/TextLink/README.md#textlink-1
こちらでREADMEにhrefの説明追記しておきました。
伝わりますかね...?

2021-05-25 00:26 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +  href = '',
後 `onClick と href 両方が未指定の場合、focasableにしない` と `href未指定でonClick指定の場合、hrefによる遷移をしない`　処理を追加しました。

2021-05-25 07:14 UTC, wmoai commented on src/components/TextLink/TextLink.tsx
> +  href = '',
README は事実を理解できるので問題ないと思います。

> onClick と href 両方が未指定の場合、focasableにしない

こちら focusable ではなくなった時、下線は無くなるのですが文字色が `TEXT_LINK` のままですが問題ないでしょうか？
![image](https://user-images.githubusercontent.com/270422/119454971-1f111000-bd74-11eb-9bfb-084381d97309.png)

2021-05-25 23:50 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +    }
はい、想定通りですね。
`Cmd + Click` で別タブで開く機能などが使えるようにするための挙動になっています。

2021-05-25 23:53 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +  href = '',
悩ましいですねこれ...
事実上disabledみたいなものですし、色変えたほうが良いような気もしますがこの状態になる可能性はかんり低いと思われるので必要になったら検討でいいかもしれません。

2021-05-26 23:37 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +  href = '',
> 下線は無くなるのですが文字色が TEXT_LINK のまま

これはユーザーエージェントスタイルでも同じ挙動なので問題なさそう（Chrome しか見てないですが）。

2021-05-27 01:04 UTC, wmoai commented on src/components/TextLink/TextLink.tsx
> +  href = '',
了解です！

2021-05-27 02:10 UTC, wmoai commented on src/components/TextLink/TextLink.tsx
> +    }
なるほど。挙動をまとめると

|  | `href` | `onClick` |
| --- | --- | --- |
| Click | ✗ | ○ |
| Cmd(など) + Click | ○ | ✗ |

という感じになると思いますが、このクリックの仕方によって挙動が変わる意図が組み込む人に伝わりにくく、バグの原因になりそうな気がしました。
例えば、 `onClick` に「遷移前に走らせたい処理」などを記述した場合、普通のクリックではその処理が走るが `Cmd + Click` では走らない、ということが起こりそうだなと思いました。

2021-05-27 03:58 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +    }
このショートカット自体は `コンテキストメニューから別タブで開く` を選んだ場合とほぼ同等であるため、むしろ遷移前に走らせたい処理は実行しないでいいかな〜、と思っていました。
ただ言われている挙動もありそうですし以下の感じの対応に変更しようと思っているんですが大丈夫そうでしょうか？

- ショートカットコマンド用のhref設定をするためのpropsを設ける(hrefForShortcut？)
- onClick未指定の場合などはhrefForShrotcutは無視
- hrefと同時指定された場合はhrefを優先

2021-05-27 06:58 UTC, AtsushiM commented on src/components/TextLink/TextLink.tsx
> +    }
@wmoai 意図を伝えるのが難しかったため、機能としてのショートカットのハンドリングは一旦削除しました 🙏

2021-05-27 09:28 UTC, wmoai submitted a review, later dismissed
LGTM 🎉

2021-05-27 23:42 UTC, AtsushiM commented
@wmoai README更新し忘れていましたのでさっと目を通していただけると 🙏

2021-05-28 00:54 UTC, wmoai commented on src/components/TextLink/README.md
> +| prefix    | -        | **ReactNode**        | -               | Set a Fa\*\*\*Icon or Other Icon component to be displayed next to the button text. if target attribute are "_blank", the default val
マークダウンの描画環境によっては `"<FaExternalLinkAltIcon aria-label="別タブで開く" />"` の部分がタグとみなされて何も表示されない場合があるようなので、ダブルクオートではなくバッククオートで囲ったほうが良いかもしれません

![image](https://user-images.githubusercontent.com/270422/119914188-9fb15580-bf9a-11eb-8340-58b57c0ef559.png)

2021-05-28 01:01 UTC, AtsushiM commented on src/components/TextLink/README.md
> +| prefix    | -        | **ReactNode**        | -               | Set a Fa\*\*\*Icon or Other Icon component to be displayed next to the button text. if target attribute are "_blank", the default val
お、なるほど。
対応しますー

2021-05-28 02:38 UTC, wmoai approved these changes
LGTM !

2021-05-28 04:45 UTC, merged