余白を px で提供する・改
kufu/smarthr-ui pull request #1545
Opened 2021-04-26 04:57 UTC by uknmr

余白を pxToRem を使用しないでも使えるように px 値で提供します。

## 概要

- spacing の baseSize を defaultHtmlFontSize から算出します
- spacing の各値を theme から渡すことはできません。baseSize に乗数を掛けたもの各値として設定します
- theme.spacing の各値を数値から px を含む文字列に変更しました
- 既存の `size.space` を使っている箇所を spacingByChar に置き換えました

## 値の置き換え

外から theme を渡さない、デフォルトの状態においては既存の `size.space` と `spacing` には互換性があります。

`size.space` | `spacing` | `spacingByChar` | 実値
--- | --- | --- | ---
\- | X3S | 0.25 | 4px
XXS | XXS | 0.5 | 8px
\- | - | 0.75 | 12px
XS | XS | 1 | 16px
\- | - | 1.25 | 20px
S | S | 1.5 | 24px
M | M | 2 | 32px
L | L | 2.5 | 40px
XL | XL | 3 | 48px
XXL | XXL | 3.5 | 56px
\- | X3L | 4 | 64px
\- | - | 8 | 128px
\- | - | -0.25 | -4px
\- | - | -0.5 | -8px
\- | - | -0.75 | -12px
\- | - | -1 | -16px
\- | - | -1.25 | -20px
\- | - | -1.5 | -24px
\- | - | -2 | -32px
\- | - | -2.5 | -40px
\- | - | -3 | -48px
\- | - | -3.5 | -56px
\- | - | -4 | -64px
\- | - | -8 | -128px

2021-04-27 07:49 UTC, masuP9 requested changes
あと ActionDialog も差分が出ていて、修正漏れぽさ

https://smarthr-ui-snapshots.s3.amazonaws.com/3d2f707df9c7895e9ceba44e82d898427a2bbd39/index.html

2021-04-27 07:49 UTC, masuP9 commented on src/components/FlashMessage/FlashMessage.tsx
> +      min-width: calc(2px + ${spacingByChar(1.5)} + 14px + 8em + 27px + ${spacingByChar(1)});
盛大に差分が出てる => https://smarthr-ui-snapshots.s3.amazonaws.com/3d2f707df9c7895e9ceba44e82d898427a2bbd39/index.html

あとここの最小幅は、200px を文字サイズ依存で、だから `pxToRem` がデザインの意図を反映してるCSSでそのままが良いかなぁと思いました。

2021-04-27 07:53 UTC, uknmr commented on src/components/FlashMessage/FlashMessage.tsx
> +      min-width: calc(2px + ${spacingByChar(1.5)} + 14px + 8em + 27px + ${spacingByChar(1)});
ここは元デザインとも整合性がなく、より実態を表した実装にしてみました。
https://smarthr.invisionapp.com/console/SmartHR-UI-ckhqzotxfh8zt0131gak0mpkm/ckhqzpm20h7em012ahdq62y4m/play

2021-04-27 07:56 UTC, masuP9 commented on src/components/FlashMessage/FlashMessage.tsx
> +      min-width: calc(2px + ${spacingByChar(1.5)} + 14px + 8em + 27px + ${spacingByChar(1)});
りょですー。このPRだとRegの差分が見るべきところなので、Descriptionに意図した差分である旨書いておくとよいかも。

2021-04-28 12:31 UTC, uknmr commented
ActionDialog の修正が漏れていたので修正（目視 & reg-suit 確認済み）

2021-05-10 03:23 UTC, nabeliwo submitted a review, later dismissed
LGTM 🎉  偉業 ✨

2021-05-10 03:24 UTC, nabeliwo reviewed
コンフリクトと CI 落ちだけお願いします 🙏

2021-05-10 14:25 UTC, merged