feat: `ModelessDialog` を追加 (SHRUI-454)
kufu/smarthr-ui pull request #1786
Opened 2021-08-03 09:05 UTC by wmoai

## Related URL
https://smarthr.atlassian.net/browse/SHRUI-454

## Overview
外側の操作をブロックしないモードレスダイアログを追加しました。

### 機能
* ダイアログ表示中も外側を操作可能
* ダイアログを開いた時ににフォーカス位置をダイアログ内に移動し、閉じた時にフォーカスをトリガに戻す
* ヘッダ部分をドラッグするか、ヘッダがフォーカスされている状態で矢印キーによってダイアログを移動可能

### Props

| name | required | type | description |
| --- | ---| --- | --- |
| header | * | `ReactNode` | ヘッダ部分の内容 |
| children | * | `ReactNode` | コンテンツ部分の内容 |
| footer |  | `ReactNode` | フッタ部分の内容 |
| isOpen | * | `boolean` | 開閉状態フラグ |
| onClickClose |  | `(e: MouseEvent) => void` | 閉じるボタンのハンドラ |
| onPressEscape |  | `() => void` | escape キーのハンドラ |
| width |  | `string \| number` | ダイアログの幅 |
| height |  | `string \| number` | ダイアログの高さ |
| top |  | `string \| number` | ダイアログの初期 top 位置 |
| left |  | `string \| number` | ダイアログの初期 left 位置 |
| right |  | `string \| number` | ダイアログの初期 right 位置 |
| bottom |  | `string \| number` | ダイアログの初期 bottom 位置 |

- header 部分はダイアログのラベルに相当すると考え、必須 Props にしました

### 実装を見送った仕様
* モーダルダイアログより前面に表示する
  * これを実現するための方法は現状ではざっくり２つ考えられる
    * `ModelessDialog` の z-index を +1 する
      * そうすると、`ModelessDialog` 上の `DatePicker` や `Tooltip` が裏側に隠れてしまう
    * モーダルである `Dialog` の z-index を -1 する
      * 影響範囲が広がってしまい、今後の保守性に禍根を残しそう
  * z-index が `OVERLAP` のものの前後関係に関するチケットが別で存在するので、そちらで根本解決方法を考えたい

## What I did
- `ModelessDialog` を実装
  - D&D 実現のために `react-draggable` を dependencies に追加
- 既存のダイアログとの共通機能を共通化
  - アニメーション関連
  - フォーカス位置の移動制御

## Capture
![image](https://user-images.githubusercontent.com/270422/128335296-2605c50e-f6f4-46b2-bc4b-5404618fa55c.png)

2021-08-10 03:22 UTC, uknmr requested changes
ざっと見ました!
ヘッダーとフッターの padding は他ダイアログと合わせて、上下 `16px` 左右 `24px` でお願いします。

2021-08-10 03:22 UTC, uknmr commented on src/components/Dialog/ModelessDialog.tsx
> +    margin-left: auto;
`styled(LineUp)` にして `align=space-between` の方が意図がわかりやすいと思います。

2021-08-10 03:22 UTC, uknmr commented on src/components/Dialog/ModelessDialog.tsx
> +    margin: ${spacingByChar(1)};
Title が持つ margin ではなくヘッダー領域が持つ padding なので実装も合わせたい。

2021-08-10 03:22 UTC, uknmr commented on src/components/Dialog/ModelessDialog.tsx
> +                  size="s"
サイズ小さくせず、ネガティブマージンで padding に食い込ませる、がいい気がしました。

2021-08-11 10:15 UTC, im36-123 requested changes

2021-08-11 10:15 UTC, im36-123 commented on src/components/Dialog/ModelessDialog.tsx
> +            <Header className={classNames.header} themes={theme}>
（達成基準 1.1.1, 達成基準 3.3.2）
ドラッグできる部分に accessibility name が必要です！また、ドラッグ可能なことを示す視覚的な情報（アイコンなど）がほしいです〜

ただ、この対応をしようとすると最終的にデザイン調整が必要なのでこの PR では対応しなくて良いと思います。

2021-08-11 10:15 UTC, im36-123 commented on src/components/Dialog/ModelessDialog.tsx
> +      <Draggable handle={`.${classNames.header}`}>
（達成基準 2.1.1）
キーボードでダイアログの移動ができると 2.1.1 が満たせそうです！
重めの対応になるので別タスクとして対応していただいても良いかと！

2021-08-13 05:22 UTC, wmoai commented on src/components/Dialog/ModelessDialog.tsx
> +    margin-left: auto;
このパーツの役割は「閉じるボタンを右寄せする」ことですが、`space-between` で表現すると「各要素を均等配置する」意味を持ってしまい本来の意図と若干ずれるので、`margin-left: auto` で表現するほうが意味的に明確だと思ったのですがどうでしょうか？

2021-08-13 05:24 UTC, wmoai commented on src/components/Dialog/ModelessDialog.tsx
> +    margin: ${spacingByChar(1)};
65cbf66fef77fc7174a89ff85d0f176fb2cfda60 にて対応しました

2021-08-13 05:26 UTC, wmoai commented on src/components/Dialog/ModelessDialog.tsx
> +                  size="s"
ヘッダの閉じるボタン周りの見た目は `BackgroundJobsPanel` のものを踏襲しているため、それらを改善する対応は別途チケット化して行いたいです！

2021-08-13 05:27 UTC, wmoai commented on src/components/Dialog/Dialog.stories.tsx
> +        <SecondaryButton onClick={() => setIsOpen1(!isOpen1)} data-test="dialog-trigger">
4f453e0cb7c964cd20b8c2c34b2466a92793724c にて対応しました

2021-08-13 05:27 UTC, wmoai commented on src/components/Dialog/Dialog.stories.tsx
> +          header="モードレスダイアログ"
4f753101a04f7eea5b865b56bad240258d2df04f にて対応しました

2021-08-13 05:28 UTC, wmoai commented on src/components/Dialog/ModelessDialog.tsx
> +            <Header className={classNames.header} themes={theme}>
ドラッグのハンドル部分を以下にアクセシブルにするかは細かい議論が必要だと思うので、別途チケット化します！

2021-08-13 05:30 UTC, wmoai commented on src/components/Dialog/ModelessDialog.tsx
> +      <Draggable handle={`.${classNames.header}`}>
08e3c5648397437184d7edb49b33d23b4b591d8f の対応で、ヘッダ部分をフォーカス可能にして、ヘッダがフォーカスされている間は矢印キーで移動できるようにしました！

2021-08-13 06:23 UTC, uknmr commented on src/components/Dialog/ModelessDialog.tsx
> +    margin-left: auto;
> margin-left: auto で表現するほうが意味的に明

そんな気がしてきました! このままで大丈夫です!
（`margin: auto` がわからない人もいるんだよなぁ、くらいのコメントでした）

2021-08-16 03:45 UTC, im36-123 commented on src/components/Dialog/ModelessDialog.tsx
> +            <Header className={classNames.header} themes={theme}>
>別途チケット化します！

ありがとうございます！

2021-08-16 03:49 UTC, masuP9 commented on src/components/Dialog/ModelessDialog.tsx
> +      <Draggable handle={`.${classNames.header}`}>
すげーーーーーーーーー

2021-08-16 03:58 UTC, im36-123 submitted a review, later dismissed
対応ありがとうございました！ LGTM です！！

2021-08-16 04:24 UTC, masuP9 reviewed
2点Commentしました！

2021-08-16 04:24 UTC, masuP9 commented on src/components/Dialog/ModelessDialog.tsx
> +              aria-label="ドラッグまたは矢印キーでダイアログを移動させることができます"
@wmoai ラベルというよりは説明なので `aria-label` じゃないほうがよさそうです。じゃあどうすればいいねん、というのは別チケあるならそこでやりましょう〜。

2021-08-16 04:24 UTC, masuP9 commented on src/components/Dialog/ModelessDialog.tsx
> +  }, [handleArrowKey])
`onKeyDown` のほうが `header.ref` とかいらなくてシンプルだなと思ったんですが、`useEffect` にしたのって何か理由ありますか？

2021-08-16 05:02 UTC, wmoai commented on src/components/Dialog/ModelessDialog.tsx
> +  }, [handleArrowKey])
うまくハンドリングできなかったため `document` に直接イベントを張った記憶があるのですが、改めて試してみたら問題なくできたので置き換えました！ 68dfbeea57bffee065dda6b1ced51c9b0b12dad0

2021-08-16 05:09 UTC, masuP9 commented on src/components/Dialog/ModelessDialog.tsx
> +  }, [handleArrowKey])
あざす！シュッとしました ❤️

2021-08-16 05:09 UTC, masuP9 submitted a review, later dismissed

2021-08-16 07:07 UTC, uknmr submitted a review, later dismissed

2021-08-16 08:49 UTC, wmoai commented
@diescake @cidermitaina デザインレビュー完了しましたのでコードレビューお願いします！

2021-09-02 01:03 UTC, cidermitaina approved these changes
めちゃくちゃ遅くなってしまってごめんなさい🙇‍♀️
確認しました！LGTM 🎉

2021-09-06 03:40 UTC, merged