feat: ComboBox・DatePicker・Selectのキャレットの色を変更・統一
kufu/smarthr-ui pull request #1975
Opened 2021-10-20 04:46 UTC by kgsi

## Related URL

- https://kufuinc.slack.com/archives/CGC58MW01/p1634686160240700

## Overview

- プロポーザル的なPR
- Comboboxのキャレットが、デフォルト`BORDER`カラーとなっており、`disabled`とも取れる色になっていた
- 有効であるということを、もっと視覚的にわかるようにしたい
- DatePicker, Selectも同じようなスタイルに合わせたい

## What I did

- ComboBoxのキャレットのデフォルトカラーを`TEXT_GRAY`に変更
- active、disabled時のカラーは据え置き

## Capture

### ComboBox

| Before | After |
|:------:|:------:|
| <img width="431" alt="CleanShot 2021-10-20 at 13 47 04@2x" src="https://user-images.githubusercontent.com/4032232/138029909-44bd225a-fc80-4b52-86ea-c9040a45e835.png"> | <img width="425" alt="CleanShot 2021-10-20 at 13 46 10@2x" src="https://user-images.githubusercontent.com/4032232/138029817-96fa0d8e-aee8-41b9-b417-c36636270263.png"> |

### Select

| Before | After |
|:------:|:------:|
| <img width="354" alt="CleanShot 2021-10-20 at 18 36 27@2x" src="https://user-images.githubusercontent.com/4032232/138068570-64c11f25-f1ee-4924-a23f-4cad60711086.png"> | <img width="298" alt="CleanShot 2021-10-20 at 18 33 22@2x" src="https://user-images.githubusercontent.com/4032232/138068084-9d9e022c-05f9-458a-a1a3-82391cb95eed.png">
 |

### DatePicker

| Before | After |
|:------:|:------:|
| <img width="411" alt="CleanShot 2021-10-20 at 18 34 39@2x" src="https://user-images.githubusercontent.com/4032232/138068251-f6e2d585-ee5f-4727-a98a-596baf036f13.png"> | <img width="388" alt="CleanShot 2021-10-20 at 18 35 09@2x" src="https://user-images.githubusercontent.com/4032232/138068350-6782aa38-991e-4755-96dd-066db15a1e2d.png"> |

2021-10-20 05:13 UTC, uknmr commented on src/components/ComboBox/MultiComboBox.tsx
> +              : theme.color.BORDER
条件を否定で始めないほうが読みやすいと思います。
また、`color.BORDER` もよくわからないので `TEXT_DISABLED` を使いたいです。

SingleComboBox も同じ。

```suggestion
            disabled
              ? theme.color.TEXT_DISABLED
              : isFocused
              ? theme.color.TEXT_BLACK
              : theme.color.TEXT_GREY
```

2021-10-20 05:22 UTC, masuP9 reviewed
1点コメントしました！

2021-10-20 05:22 UTC, masuP9 commented on src/components/ComboBox/SingleComboBox.tsx
> +                      : theme.color.BORDER
[IMO] 三項演算子のネストだと読みにくくなってしまうので、どこかで計算してから渡しても良いかなと思いました！

```TypeScript
const caretIconColor = useMemo(() => {
  if (disabled) return theme.color.BORDER
  if (isFocused) return theme.color.TEXT_BLACK
  return theme.color.TEXT_GREY
}, [disabled, isFocused])

// 中略

<FaCaretDownIcon color={caretIconColor} />
```

2021-10-20 05:56 UTC, kgsi commented on src/components/ComboBox/SingleComboBox.tsx
> +                      : theme.color.BORDER
@masuP9 ありがとうございます！良さそう！memo関数化してみましたー

2021-10-20 09:17 UTC, kgsi commented
@uknmr DatePicker、Selectも対応したのでレビューお願いします:pray:

2021-10-20 23:35 UTC, uknmr requested changes
DatePicker はよさそう。Select は disabled が効かなくなっていました。

2021-10-21 02:49 UTC, kgsi commented on src/components/Select/Select.tsx
> +  }, [isFocused, disabled, theme])
@uknmr style側で管理したほうが良さそうですね、対応してみましたのでご確認お願いします！

2021-10-21 02:50 UTC, kgsi commented on src/components/Select/Select.tsx
>    ...props
`props.`を消し去った影響でした :innocent: こちらも対応済みです！

2021-10-21 04:40 UTC, uknmr requested changes
細かいんですがもう一声お願いします!

2021-10-21 04:40 UTC, uknmr commented on src/components/Select/Select.tsx
> +`
Icon の `color` props は string を受け付けるので、`<FaSortIcon color="inherit" />` でいけるはず。

2021-10-21 04:40 UTC, uknmr commented on src/components/Select/Select.tsx
> +
`IconWrap` に書けば兄弟セレクタとクラス名不要になります。

2021-10-21 04:40 UTC, uknmr commented on src/components/Select/Select.tsx
> +        }
imo: 変えたいのは Icon なので IconWrap 側に書いたほうが読みやすいと考えます。クラス名も不要になりそう。

2021-10-21 04:49 UTC, kgsi commented on src/components/Select/Select.tsx
> +
これは明らかに不要でしたね:tehe:

2021-10-21 06:22 UTC, uknmr commented on src/components/Select/Select.tsx
> +`
コンポーネントとし用意されている I/F（この場合 color props）を使わないで、オーバーラップする理由が見えなかった感じです。
名前も `StyledIcon` とテンポラリに近いものだったので。

2021-10-21 06:23 UTC, uknmr commented on src/components/Select/Select.tsx
> +      <IconWrap themes={theme} className="caret">
消し漏れっぽい。

```suggestion
      <IconWrap themes={theme}>
```

2021-10-21 12:38 UTC, merged