fix: `Input`のwidthをデフォルトの値より小さく設定すると表示が崩れる不具合の修正
kufu/smarthr-ui pull request #2102
Opened 2021-12-09 02:00 UTC by yamish123

## Related URL

## Overview

## What I did

## Capture

2021-12-09 04:33 UTC, yamish123 commented
何故か関係無いところのe2eコケてる

2021-12-09 05:11 UTC, uknmr requested changes
ありがとうございます。コードと動きは問題なさそうでした。
今後のデグレを防ぐための Story 追加もお願いします。
（デフォルト値は smarthr-ui 側で指定しているわけではなく、UA に依って異なりそうでした）

2021-12-09 05:49 UTC, yamish123 commented
@uknmr 
こちら対応しましたー！
修正前後だとこんな感じの差分になります
| before | after |
| - | - |
| ![スクリーンショット 2021-12-09 14 42 37](https://user-images.githubusercontent.com/32166731/145341699-9a71e1bd-2137-4e00-9fdf-9f240bd1c3e7.png) | ![スクリーンショット 2021-12-09 14 42 50](https://user-images.githubusercontent.com/32166731/145341718-dbebef34-227c-43f8-a48b-3a0d49644c48.png) |

2021-12-09 06:23 UTC, uknmr approved these changes
LGTM!

2021-12-10 01:55 UTC, yamish123 commented
@uknmr 
こちら update branchしたところ再度reg-suitのエラーが出てしまったため、再度Approveいただけますでしょうか？ 🙏

2021-12-10 05:16 UTC, uknmr approved these changes

2021-12-10 08:01 UTC, yamish123 commented
@uknmr 
他のPRマージされたのでまたmaster追従 -> reg-suitコケちゃいました 🙇 
よしなのタイミングでApproveしつつマージもしちゃってもらった方が楽かもです！

2021-12-10 08:04 UTC, merged

2021-12-10 08:04 UTC, uknmr commented
問題ないので権限使ってマージしました!