remove gap fallback from `<Cluster>`
kufu/smarthr-ui pull request #2218
Opened 2022-01-24 06:30 UTC by masuP9

## Related URL

https://smarthr.atlassian.net/browse/SHRUI-517

## Overview

## What I did

- remove fallback flex gap
- change Cluster to styled-components
- use CSSProperties type to align, justify props type
- add inline Props

## Capture

2022-01-25 04:53 UTC, uknmr requested changes

2022-01-25 04:53 UTC, uknmr commented on src/components/Layout/Cluster/Cluster.tsx
> -import { useClassNames } from './useClassNames'
元ファイルの削除もお願いします!
https://github.com/kufu/smarthr-ui/blob/2ed3013502aceb72fdee852c65f8a0bf534a522e/src/components/Layout/Cluster/useClassNames.ts

2022-01-31 13:03 UTC, masuP9 commented on src/components/Layout/Cluster/Cluster.tsx
> -import { useClassNames } from './useClassNames'
削除しました！

2022-02-01 01:22 UTC, uknmr approved these changes
LGTM

2022-02-07 02:15 UTC, merged