fix: disabled なボタンに表示するツールチップが正常に動作するように修正 (SHRUI-529)
kufu/smarthr-ui pull request #2280
Opened 2022-02-15 07:30 UTC by wmoai

## Related URL
https://smarthr.atlassian.net/browse/SHRUI-529

## Overview
`Tooltip` コンポーネントは、disabled なボタンに対して設定すると、hover 時に表示されるが leave 時に非表示ならない不具合が発生するため、修正します。

## What I did
- 表示制御のイベントを変更
  - `onMouseEnter` → `onPointerEnter`
  - `onMouseLeave` → `onPointerLeave`

## Capture

2022-02-16 01:09 UTC, uknmr requested changes
button[disabled] の動きは問題なさそうでした!

2022-02-16 01:09 UTC, uknmr commented on src/components/Tooltip/Tooltip.stories.tsx
> +          </Tooltip>
ありえないので例示しないほうがよさそう。
キーボード操作で Tooltip にフォーカスがあたったときに、ボタンにフォーカスしたと勘違いしてしまう。

2022-02-16 09:05 UTC, AtsushiM commented on src/components/Tooltip/Tooltip.tsx
> +      onPointerEnter={getHandlerToShow(onMouseEnter)}
利用者的に `onMouseEnter` を指定したら `onPointerEnter` に設定されてしまうのはだめかも...
影響範囲デカイけど調整出来ないかな...

2022-02-17 02:11 UTC, wmoai commented on src/components/Tooltip/Tooltip.tsx
> +      onPointerEnter={getHandlerToShow(onMouseEnter)}
確かに、ハンドラは適用先と基となるハンドラが一致している必要があるのでそのように修正しました。 31933b4
mouse event 系は `{...props}` で渡されるので、これならこれまでと挙動は変わらないと思います。

2022-02-17 23:18 UTC, AtsushiM approved these changes
LGTM.

2022-02-21 02:25 UTC, uknmr approved these changes

2022-02-21 02:26 UTC, merged