feat: `Button`, `AnchorButton` コンポーネントを追加 (SHRUI-545)
kufu/smarthr-ui pull request #2443
Opened 2022-04-25 07:00 UTC by wmoai

## Related URL
https://smarthr.atlassian.net/browse/SHRUI-545

## Overview
既存のボタンコンポーネントは `PrimaryButton`, `SecondaryButton` など種類毎に別コンポーネントになっていますが、コンポーネントを `Button` と `AnchorButton` に統一し、`variant` Props で種類を選べるように変更します。

## What I did
- `Button`, `AnchorButton` を追加
  - `variant?: 'primary' | 'secondary' | 'danger' | 'skeleton' | 'text'` 、デフォルトは `secondary`
- 既存のボタンを非推奨化
  - `PrimaryButton`
  - `PrimaryButtonAnchor`
  - `SecondaryButton`
  - `SecondaryButtonAnchor`
  - `DangerButton`
  - `DangerButtonAnchor`
  - `SkeletonButton`
  - `SkeletonButtonAnchor`
  - `TextButton`
  - `TextButtonAnchor`

## Capture

2022-04-25 07:55 UTC, uknmr requested changes
regsuit は問題ないことを確認しました!
気になったところにコメント入れました。

2022-04-25 07:55 UTC, uknmr commented on src/components/Button/ButtonWrapper.tsx
> +        background-clip: padding-box;
nits

```suggestion
      background-clip: padding-box;
```

2022-04-25 07:55 UTC, uknmr commented on src/components/Button/ButtonWrapper.tsx
> +        background-clip: padding-box;
nits

```suggestion
      background-clip: padding-box;
```

2022-04-25 07:55 UTC, uknmr commented on src/components/Button/ButtonWrapper.tsx
> +    &:focus,
`:focus-visible` でお願いします。

```suggestion
    &:focus-visible,
```

2022-04-25 07:55 UTC, uknmr commented on src/components/Button/ButtonWrapper.tsx
> +    &:focus,
`:focus-visible` でお願いします。

```suggestion
    &:focus-visible,
```

2022-04-25 07:55 UTC, uknmr commented on src/components/Button/ButtonWrapper.tsx
> +    &:focus {
`:focus-visible` でお願いします。

```suggestion
    &:focus-visible {
```

2022-04-25 07:55 UTC, uknmr commented on src/components/Button/ButtonWrapper.tsx
> +}
`variantStyles` を export して `Button/Button` と `Button/AnchorButton` にそれぞれ書いてもよさそうに思いました（`isAnchor` が冗長に見える）。

2022-04-25 09:22 UTC, wmoai commented on src/components/Button/ButtonWrapper.tsx
> +}
`ButtonWrapper` には Wrapper のスタイル定義とそれに関わるクラス名の付与の責務をまとめていて、`variantStyles` を export して使うと Wrapper のスタイルを決定する記述が分散してコードの見通しが悪くなってしまうためこのような形にしています。
`isAnchor` は確かに一見微妙な感じですが、役割は明確で可読性も壊していないと思うのでこれで問題ないのではないかと判断しました。

2022-04-26 00:43 UTC, wmoai commented on src/components/Button/ButtonWrapper.tsx
> +        background-clip: padding-box;
ありがとうございます。まとめて対応済みです。
[d0f134c](https://github.com/kufu/smarthr-ui/pull/2443/commits/d0f134c902cf5f66b86be97657c95f544e57d0e9)
[96e78d2](https://github.com/kufu/smarthr-ui/pull/2443/commits/96e78d20209e51a3fb718f3edf1be0eb3f2e0ee4)

2022-04-26 01:11 UTC, uknmr submitted a review, later dismissed
LGTM!

2022-04-26 07:17 UTC, wmoai commented
すみません、エスケープハッチ付け忘れてたので追加しました！ [e45bb55](https://github.com/kufu/smarthr-ui/pull/2443/commits/e45bb554ee57550f977a7c6635f300661c7ed007)

2022-05-09 00:25 UTC, uknmr approved these changes

2022-05-09 02:28 UTC, merged