fix: `NotificationBar` の右寄せ部分にエスケープハッチを追加 (SHRUI-555)
kufu/smarthr-ui pull request #2469
Opened 2022-05-02 07:55 UTC by wmoai

## Related URL
https://smarthr.atlassian.net/browse/SHRUI-555

## Overview
`NotificationBar` コンポーネントにおいて、横スクロールを持つコンテナ内に表示した時に右寄せ部分が隠れる問題に対処できるように、コンポーネント内の右寄せ部分にエスケープハッチを追加します。

## What I did
- 右寄せ部分をまとめるために DOM 構造を変更
- 右寄せ部分にエスケープハッチを追加

## Capture

2022-05-09 00:01 UTC, AtsushiM approved these changes
LGTM.

2022-05-09 00:20 UTC, uknmr requested changes

2022-05-09 00:20 UTC, uknmr commented on src/components/NotificationBar/NotificationBar.tsx
> +  & > svg {
imo: 必要以上に詳細度が高く見えました。
```suggestion
  .smarthr-ui-Icon {
```

2022-05-09 00:20 UTC, uknmr commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: auto;
不要そうに見える。

2022-05-09 00:20 UTC, uknmr commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: ${spacingByChar(0.5)};
`RightArea` の `gap` があるので不要そう。

2022-05-09 06:09 UTC, wmoai commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: auto;
削除しました！ [f6a084b](https://github.com/kufu/smarthr-ui/pull/2469/commits/f6a084b9b3d77573363c3aacc90fc96b029c48bc)

2022-05-09 06:12 UTC, wmoai commented on src/components/NotificationBar/NotificationBar.tsx
> +  & > svg {
`.smarthr-ui-Icon` は `Icon` コンポーネントのエスケープハッチで、これをハードコードで指定すると変更に弱くなってしまうので、それを緩和するためにこのようなセレクタ指定にしている感じです。

2022-05-09 06:15 UTC, wmoai commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: ${spacingByChar(0.5)};
これは、既存のスタイルにおいてはメッセージとアクションの間のみ `spaceingByChar(1)` 分のスペースが取られているのを再現するために入れています

2022-05-13 08:02 UTC, uknmr commented on src/components/NotificationBar/NotificationBar.tsx
> +  & > svg {
`.smarthr-ui-Hoge` をエスケープハッチにこだわらなくてもいいのかな、という気はします。
詳細度が不要に高いのが気になるので、styled-components の機能を使うのはどうですか?
https://styled-components.com/docs/advanced#referring-to-other-components

2022-05-13 08:12 UTC, uknmr commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: ${spacingByChar(0.5)};
とすると、下記のようになると意図が明確になると思います!

```tsx
<Wrapper>
  <MessageArea>
    <Icon />
    <Text />
  </MessageArea>
  <ActionArea>
    <ActionWrapper />
    <CloseButton />
  </ActionArea>
</Wrapper>
```

2022-05-26 05:32 UTC, wmoai commented on src/components/NotificationBar/NotificationBar.tsx
> +  & > svg {
スタイル内のコンポーネント指定は対象が複数だとうまく行かないようでした。
flex ボックスにすることで内側の要素に line-height が発生しないようにすることで対応しました。 https://github.com/kufu/smarthr-ui/pull/2469/commits/01101b05a66d9d38de7a33915dd913a7027ad9d7

2022-05-26 05:36 UTC, wmoai commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: ${spacingByChar(0.5)};
既存のスタイルでは `ActionWrapper` と `Text` の間のみ `spacingByChar(1)` が適用され、アクションが存在しない場合　は `ActionWrapper` が無くなり `CloseButton` と `Text` の間は `spacingByChar(0.5)` となるため、その構造では再現できないと思われます。

2022-05-27 04:58 UTC, uknmr commented on src/components/NotificationBar/NotificationBar.tsx
> +  & > svg {
ありがとうございます!

> 内側の要素に line-height が発生しないようにする

これコメントにしておくとよさそうです!

2022-05-27 05:04 UTC, uknmr commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: ${spacingByChar(0.5)};
`Text` との余白ではなく `MessageArea` と `ActoinArea` の余白で良いと思います!
既存から変わるかもしれないですが、どちらも `ActionWrapper` がある場合もない場合も `spacingByChar(1)` でいいかも?

2022-05-27 06:30 UTC, wmoai commented on src/components/NotificationBar/NotificationBar.tsx
> +  & > svg {
コメント追加しました f04c06d00fbdc6aa40373c50307581b487ef496d

2022-05-27 06:31 UTC, wmoai commented on src/components/NotificationBar/NotificationBar.tsx
> +    margin-left: ${spacingByChar(0.5)};
了解です。そのように構造変更しました。 49a14abc3d2fee043cf70c4710a2465fb8fee29e

2022-05-30 00:56 UTC, merged