fix: フォーカスリングが見きれないように修正 (SHRUI-565)
kufu/smarthr-ui pull request #2537
Opened 2022-05-31 05:30 UTC by wmoai

## Related URL
https://smarthr.atlassian.net/browse/SHRUI-565

## Overview
`Pagination`. `TabBar` コンポーネントにおいてフォーカスリングが見切れてしまっている不具合に対応します。

## What I did
- フォーカスリングが見切れないようにコンポーネント内側に余白を設けた

## やらなかったこと
- padding + negative margin による対応だと親要素に対して幅または高さが 100% の時に overflow が発生してしまうため、今回は単純に余白を持つことにしました

## Capture

2022-06-01 01:24 UTC, yt-ymmt approved these changes
各ブラウザでフォーカスリングが見切れていないことを確認しました :lgtm:

2022-06-01 09:12 UTC, AtsushiM approved these changes
:gogo:

2022-06-01 21:26 UTC, uknmr requested changes
imo： margin ではなく padding かも?

2022-06-01 21:26 UTC, uknmr commented on src/components/Pagination/Pagination.tsx
> +      margin: 4px; /* フォーカスリングが見切れないようにするための余白 */
できるだけマジックナンバーを残したくないので、`spacingByChar(0.25)` でどうですか?

2022-06-02 04:46 UTC, wmoai commented on src/components/Pagination/Pagination.tsx
> +      margin: 4px; /* フォーカスリングが見切れないようにするための余白 */
ここで指定している余白は文字サイズとは関係なく 4px であり、`spacingByChar(0.25)` とすると逆に誤解を招くと思います。

ただ、定義を明確化する意味はあると思うので、テーマに余白の定義をまとめました。 [d24bed0](https://github.com/kufu/smarthr-ui/pull/2537/commits/d24bed08c4925da8ed99648dfbe3620780087f6f)

2022-06-02 04:50 UTC, wmoai commented
@uknmr margin か padding かですが、`TabBar` の方は padding を使うと `TabBar` の下線と `TabItem` の下線の位置関係が変わってしまうことから対応が煩雑になるため、よりシンプルに対応可能な margin を選択しました。

また、`Pagination` においても、個人的には margin でも padding でも意味の説明は可能と考えたため、余計な混乱を避けるために margin で統一して良いのではないかと考えています。

2022-06-03 01:24 UTC, uknmr approved these changes
> TabBar の方は padding を使うと TabBar の下線と TabItem の下線の位置関係が変わってしまう

納得しました!!
margin に統べるのも賛成です。

2022-06-03 03:39 UTC, merged