feat: `EmptyTableBody` の追加
kufu/smarthr-ui pull request #2948
Opened 2022-12-01 03:10 UTC by yamish123

## Related URL

## Overview

## What I did

## Capture

2022-12-02 01:29 UTC, yt-ymmt approved these changes
:lgtm: これは便利〜〜！

2022-12-02 01:29 UTC, yt-ymmt commented on src/components/Table/Table.stories.tsx
> +            <Text as="p">別の条件をお試しください。</Text>
（chore）とても細かいところなのですが、文章的にはpタグ1つの内容かな？と思いました。

2022-12-02 02:54 UTC, uknmr requested changes

2022-12-02 02:54 UTC, uknmr commented on src/components/Table/EmptyTableBody.tsx
> +  padding?: Gap
SeparateGap が欲しい場面もある気がします!

2022-12-02 02:54 UTC, uknmr commented on src/components/Table/EmptyTableBody.tsx
> +  children?: ReactNode
imo： `React.PropsWithChildren` を使うといい感じなことに最近気が付きました!

↓ こんな感じに書ける。

```tsx
type Props = PropsWithChildren<{
  padding?: Gap
}>
```

2022-12-02 02:54 UTC, uknmr commented on src/components/Table/EmptyTableBody.tsx
> +export type Props = {
imo： `ComponentProps<typeof Hoge>` で取れるので、type の export 不要そう

2022-12-05 09:50 UTC, yamish123 commented on src/components/Table/Table.stories.tsx
> +            <Text as="p">別の条件をお試しください。</Text>
あざます！個別の p タグをやめました [c42d403](https://github.com/kufu/smarthr-ui/pull/2948/commits/c42d403670eb7f60bf3b9fd1e8f92f9dffad0643)

2022-12-05 09:51 UTC, yamish123 commented on src/components/Table/EmptyTableBody.tsx
> +export type Props = {
その通りなので消しちゃいました！[ad32a93](https://github.com/kufu/smarthr-ui/pull/2948/commits/ad32a93754246744ff6ff200f6e6d36fa51d4a17)

2022-12-05 09:52 UTC, yamish123 commented on src/components/Table/EmptyTableBody.tsx
> +  padding?: Gap
こちら追加しました！[91f61be](https://github.com/kufu/smarthr-ui/pull/2948/commits/91f61bedc523541c69c8e399ca1052f47330cc72)

2022-12-07 00:54 UTC, yt-ymmt approved these changes
:lgtm:

2022-12-07 05:03 UTC, merged