feat: add contentWidth for FilterDropdown
kufu/smarthr-ui pull request #3042
Opened 2023-01-22 02:10 UTC by ytnk531

Add contentWidth property for fixing width of FilterDropdown.

## Related URL

## Overview
This PR adds contentWidth property for fixing width of FilterDropdown.

In some situations, fixing DropdownContent's width is useful.
It seems to be done by fixing width of FilterDropdown's children. But DropdownContentInner component's max-width CSS property makes it difficult.

The screenshot below shows how the content be rendered in the [storybook](https://smarthr-ui.netlify.app/?path=/story/buttons%EF%BC%88%E3%83%9C%E3%82%BF%E3%83%B3%EF%BC%89-dropdown--filter-dropdown).

<img width="439" alt="image" src="https://user-images.githubusercontent.com/9428628/213848263-8f02090c-6ff9-45f9-a87f-8eeb05edf180.png">

The content area is smaller than its contents. It looks broken.
This behavior comes from DropdownContentInner's max-width property setting.
For this reason, I changed max-width property to be disabled when with property provided.

### How about using smarthr-ui-Dropdown-content class
This problem seems to be solved by using `smarthr-ui-Dropdown-content` class ([added here](https://github.com/kufu/smarthr-ui/blob/48163c6e549c2ce9ab8314a225190b2e56118cef/src/components/Dropdown/DropdownContent.tsx#L52)) with styled-component. But it should be difficult. This is because DropdownContent is rendered as a child element of body by createPortal. Not child of FilterDropdown. Styling such element with styled-component is difficult.

So I wanted to add this feature.

## What I did
- Added contentWidth for FilterDropdown.
- Disabled max-width property when width is passed to DropdownContentInner.

## Capture
<img width="746" alt="image" src="https://user-images.githubusercontent.com/9428628/213897475-54b64f30-3d9e-463e-807f-89846b10c6eb.png">

2023-01-25 03:41 UTC, AtsushiM commented on src/components/Dropdown/DropdownContentInner.tsx
> +      `}
(nits)
好みの問題かと思いますが、$widthに対する判定が二度行われるので三項演算子を使うと意図が明確になって良いかもしれません。

```
${$width === undefined ? (
  css`
    max-width: ~
  `
) : (
  css`
    width: ~
  `
)}
```

2023-01-25 04:05 UTC, ytnk531 commented on src/components/Dropdown/DropdownContentInner.tsx
> +      `}
あっ
タシカニぃ！ありがとうございます！

2023-01-30 02:03 UTC, AtsushiM approved these changes

2023-01-30 02:58 UTC, uknmr requested changes
横スクロールが発生してしまうため、DropdownContentInner が広がるのではなく、内包要素がレスポンシブに狭まる、のが良さそうに思いました。

2023-02-05 01:00 UTC, ytnk531 commented
@uknmr 
コメントありがとうございます。
右スクロールが発生しないようにする内包コンテンツが伸縮する方向で実装してみます。
ただ、伸縮させようとしてもDropdownContentInnerの内側に横幅固定の要素があるなどの要因で狭まることができない場合があるのですが、どのような仕様にとするのが望ましいでしょうか？
上記の事象は現行の [storybook](https://smarthr-ui.netlify.app/?path=/story/buttons%EF%BC%88%E3%83%9C%E3%82%BF%E3%83%B3%EF%BC%89-dropdown--filter-dropdown)で、ウィンドウサイズを小さくすると確認できます。
<img width="439" alt="image" src="https://user-images.githubusercontent.com/9428628/213848263-8f02090c-6ff9-45f9-a87f-8eeb05edf180.png">
内包要素が突き抜けて、横スクロールが発生します。

横スクロールが発生するのを防ごうと思うと、`overflow: hidden;`とするくらいしか思いつかず…
<img width="475" alt="image" src="https://user-images.githubusercontent.com/9428628/216767553-0472947a-2a0e-4bb3-b9ec-bc2d43b6b970.png">

2023-02-16 12:31 UTC, uknmr commented
@ytnk531 こちら放置していてごめんなさい!

横幅固定の要素があることがおかしい場合が多いと思います。
利用者がどんな環境で閲覧しているかは実装側ではわからないため、基本的にレスポンシブに作るべきだと考えています。

FilterDropdown がそもそも幅の狭い画面に対応できていなかったため修正してみました。
https://github.com/kufu/smarthr-ui/pull/3130

2023-02-17 00:44 UTC, ytnk531 commented
#3130 で、幅が狭いときに崩れる問題は解消されるのでクローズします。

2023-02-17 00:44 UTC, closed without merging