feat: Base に背景色を指定するための color を追加
kufu/smarthr-ui pull request #3081
Opened 2023-01-30 04:32 UTC by uknmr

Base に背景色を付けたいことが多いが、毎度 styled-components で wrap していて不便だった。
- 灰色以外の色を指定することは基本的にないため、グレースケールに絞っている
- セマンティクストークン名でもプリミティブトークン名でもどちらでも指定できる
- 初期値は WHITE

2023-01-30 12:09 UTC, yamish123 requested changes
Story上で動作確認出来なかったので修正お願いします！ 🙏 

あと、Baseに背景色をつけるケースって従業員サーベイでは遭遇したことが無いのですが、具体的にどういう画面で出てきますかね？興味本位で見てみたく

2023-01-30 12:09 UTC, yamish123 commented on src/components/Base/Base.stories.tsx
> +          </li>
Story上で色が効いてなさそうです！ `color` じゃなくて `bgColor` 指定しないといけなさそう

https://deploy-preview-3081--smarthr-ui.netlify.app/?path=/story/data-display%EF%BC%88%E3%83%87%E3%83%BC%E3%82%BF%E8%A1%A8%E7%A4%BA%EF%BC%89-base--base-story
![スクリーンショット 2023-01-30 21 07 48](https://user-images.githubusercontent.com/32166731/215472736-8f5e6d09-f106-4f7e-9ef8-adb211d4a962.png)

2023-01-30 20:41 UTC, uknmr commented on src/components/Base/Base.stories.tsx
> +          </li>
ありがとうございます!
修正漏れていました🙏

2023-01-30 20:44 UTC, uknmr commented
@yamish123 Base の上で更に見た目上の区切りを作りたいときがあるようです!
Dialog もある種 Base なので、その中で使いたい時も色付けたりします。
（他プロダクトをざっと眺めたんですが、radius の効いていない灰色を敷いてるところも多そうだった……）
![image](https://user-images.githubusercontent.com/19403400/215590545-a8dd7dc4-dec9-40e3-b8e5-d5565be4020f.png)

2023-01-31 02:49 UTC, yamish123 approved these changes
LGTM 🎉 
ユースケースも把握しました！よく見るやつだ！

2023-01-31 02:53 UTC, uknmr commented
角丸をどうするかの議論がありそうですが、Base に灰色をのせることは変わらないので、一旦マージしてしまいます。

2023-01-31 02:53 UTC, merged