feat: READMEのURL書き換え・日本語に変更
kufu/smarthr-ui pull request #3103
Opened 2023-02-06 03:49 UTC by kgsi

## Related URL

## Overview

## What I did

## Capture

2023-02-06 03:53 UTC, kgsi commented on README.md
> +root.render(<App />)
`createRoot`を使った最新の書き方に合わせた

2023-02-07 04:57 UTC, yamish123 reviewed
1点だけ気になった点コメントしました！

2023-02-07 04:57 UTC, yamish123 commented on README.md
> +Smart [コントリビュート](https://github.com/kufu/smarthr-ui/blob/master/CONTRIBUTING.md)をお待ちしています。
Smart コントリビュートとは！？

2023-02-08 01:08 UTC, uknmr requested changes
Figma やデザインシステムへのリンクと一文がどこかにあっても良さそうに思いました!

2023-02-08 01:08 UTC, uknmr commented on README.md
> +SmartHR UI はそのすべてのアプリケーションの UI コンポーネントを共通化して、デザイン・実装の速度や完成度を向上させるための UI コンポーネントライブラリです。
imo: 生産性の方が馴染みがあってイメージつくかも

```suggestion
SmartHR UI はそのすべてのアプリケーションの UI コンポーネントを共通化して、開発生産性や完成度を向上させるための UI コンポーネントライブラリです。
```

2023-02-08 01:08 UTC, uknmr commented on README.md
> +SmartHR-UI は[npm package](https://www.npmjs.com/package/smarthr-ui)として提供されています。
能動態でよさそう。

```suggestion
SmartHR-UI は[npm package](https://www.npmjs.com/package/smarthr-ui)として提供しています。
```

2023-02-08 01:08 UTC, uknmr commented on README.md
>  const App: React.FC<Record<string, unknown>> = () => (
不要そう

```suggestion
const App: React.FC = () => (
```

2023-02-08 01:08 UTC, uknmr commented on README.md
>  const theme = createTheme({})
不要なはず。

```suggestion
const theme = createTheme()
```

2023-02-08 09:08 UTC, kgsi commented on README.md
> +Smart [コントリビュート](https://github.com/kufu/smarthr-ui/blob/master/CONTRIBUTING.md)をお待ちしています。
コレ直しました！

2023-02-08 21:33 UTC, uknmr approved these changes
LGTM!

2023-02-08 23:09 UTC, merged