feat: Th に並び替え機能を追加
kufu/smarthr-ui pull request #3128
Opened 2023-02-15 02:36 UTC by uknmr

## Related URL

- https://w3c.github.io/aria-practices/examples/table/sortable-table.html
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort

## Overview

半端に `onClick` が付き、利用側で実装する形になっていたため、smarthr-ui としてあるべき並び替え機能を実装しました。

### 考えられる状態

以下の状態に対して `sort?: 'ascending' | 'descending' | 'none'` という props を追加しました。

- sort できない列
- sort できるがしていない列
- 昇順で sort している
- 降順で sort している

この props は並び替え状態を見た目的に制御するだけでなく、`th[aria-sort]` としても使われます。

## 残タスク

- [ ] 初期文言の decorators 化

## Capture

2023-02-15 03:06 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +    height: calc(1em * ${leading.NORMAL} + ${space(0.5)} * 2);
この方法ではthが複数行になる場合などに対応できないため、筋が良くないかも...
styleを当て直したりする際に困りそうです。
順当にpadding: 0を当てるかnegative marginで対応したほうが良さそう。

2023-02-15 03:06 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +  const sortLabel = useMemo(() => {
aria-labeではなくaria-sortのほうが良いかも。
https://github.com/kufu/smarthr-ui/pull/3127/files#diff-27f14c5125072726601ca9775063ccab3f6d656cb5802c0c556d3f25071767e2R95

こちらならば昇順、降順は自動的に利用言語に追わせられることは @maverick さんと確認済みです

2023-02-15 03:06 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      <FaSortDownIcon color={sort === 'descending' ? 'TEXT_BLACK' : 'TEXT_DISABLED'} />
既知の問題ですが `sortしていないニュートラルなカラムがソート可能である` ことの視覚的情報が存在していないことは問題かもです。
sortアイコンの中抜版などつかって表現できないかな...

2023-02-15 03:06 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      <FaSortDownIcon color={sort === 'descending' ? 'TEXT_BLACK' : 'TEXT_DISABLED'} />
smarthr本体では VisuallyHiddenTextを使い、スクリーンリーダー対応などしました https://github.com/kufu/hanica/pull/28993/files#diff-2cafc7fc18b0992bb379d645a7c90fe8704225016c925ca7f82150fe513efe05R28

2023-02-15 03:23 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +  const sortLabel = useMemo(() => {
📝 ここはテーブルセルではなくアイコンなのでaria-labelで良さそう

2023-02-15 03:36 UTC, uknmr commented on src/components/Table/Th.tsx
> +      <FaSortDownIcon color={sort === 'descending' ? 'TEXT_BLACK' : 'TEXT_DISABLED'} />
Story で言うとこの色がどちらも灰色になってるのが「sortしていないニュートラルなカラムがソート可能である」を指しています。
![image](https://user-images.githubusercontent.com/19403400/218921446-7da15721-9e94-4e35-8812-182b3a8ad82f.png)

2023-02-15 03:36 UTC, uknmr commented on src/components/Table/Th.tsx
> +      <FaSortDownIcon color={sort === 'descending' ? 'TEXT_BLACK' : 'TEXT_DISABLED'} />
ラベルは「並び替えなし」としています。

2023-02-15 03:39 UTC, uknmr commented on src/components/Table/Th.tsx
> +    height: calc(1em * ${leading.NORMAL} + ${space(0.5)} * 2);
今回、ここのロジックは触ってないんですが、複数行の場合に height は勝手に広がるはずなので初期値みたいな扱いだと思います。
ボタンが入ることもあって negative margin でやればいいと思うんだけど、既存が固定 px だったのを踏襲してここまで来てるんだと思います。

2023-02-15 03:51 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +    height: calc(1em * ${leading.NORMAL} + ${space(0.5)} * 2);
なるほど？
しかし今回のthをposition: relative, 中身のbuttonをposition:absoluteにした場合、button内が複数行になっても浮いてるためthが追随しなくなるかと。

2023-02-15 04:03 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +        return decorators?.descendingLabel?.(LABEL[sort]) || LABEL[sort]
この書き方をするならswitchではなく、`return decorators?.descendingLabel?.(LABEL[sort]) || LABEL[sort]` だけで完結できるように `LABEL`のキーを調整するほうがスッキリしそう。

```
const LABEL = {
  ascending: '昇順',
  descending: '降順',
  none: '並び替えなし',
}

...

const sortLabel = useMemo(() => decorators?.ascendingLabel?.(LABEL[sort]) || LABEL[sort], [decorators, sort])
```

2023-02-15 04:07 UTC, AtsushiM commented on src/components/Table/Table.stories.tsx
> +                  noSortLabel: (text) => `ascending(${text})`,
このdecoratorの名称だとなんのためのdecoratorかが少しわかりづらそうです。
また、利用する箇所自体は同一であるため、3つのdecoratorにわけず、一つのdecoratorで実装するのがいいかもしれません。

```
decorators={{ sortDirectionVisuallyHiddenText: (text) => `hoge(${text})` }}
```

2023-02-15 04:09 UTC, AtsushiM commented on src/components/Table/Table.stories.tsx
> +                  noSortLabel: (text) => `ascending(${text})`,
decorators[any] の関数は第2引数にanyで値を受け取れるので `{ sort: sort }` などで向きを明確に渡してあげるのもありかと。

2023-02-15 04:10 UTC, uknmr commented on src/components/Table/Th.tsx
> +    height: calc(1em * ${leading.NORMAL} + ${space(0.5)} * 2);
たしかに!
padding と negative margin に戻します!

2023-02-15 04:36 UTC, uknmr commented on src/components/Table/Table.stories.tsx
> +                  noSortLabel: (text) => `ascending(${text})`,
よさそう

2023-02-15 04:48 UTC, uknmr commented on src/components/Table/Table.stories.tsx
> +                  noSortLabel: (text) => `ascending(${text})`,
修正しました!!
https://github.com/kufu/smarthr-ui/pull/3128/commits/f9247beba287b4de0e38407fe89d74a0c50308b1

2023-02-15 04:57 UTC, AtsushiM requested changes

2023-02-15 04:57 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
`sortDirectionLabel` では `非表示のテキストである` ことがわからないため、`sortDirectionVisuallyHiddenText` などのほうが良さそうです。

2023-02-15 04:57 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
また、今の状態では利用者側は表示のための文字列で条件分岐しなくてはいけなくなるため `decorators?. sortDirectionVisuallyHiddenText?.(SORT_DIRECTION_LABEL[sort], { sort })` のようにsortによって一意になる値を渡すほうが良さそうです

2023-02-15 05:17 UTC, uknmr commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
> sortDirectionLabel では 非表示のテキストである ことがわからない

ラベルが非表示であるかどうかを意識する必要はないと思ったので、VisuallyHidden を消しています。

後者、実装しました!
[084c778](https://github.com/kufu/smarthr-ui/pull/3128/commits/084c77801c3fb6f25c1e77d4c7551b1a288b1c94)

2023-02-15 06:05 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
> ラベルが非表示であるかどうかを意識する必要はない

まぁ↑も一理あるんですが、単純に名前からなんのためのdecoratorか分かりづらいかと。(表示上に現れませんし)
今の名前だと `デフォルトは空文字でどこかに表示されるラベル` と区別がつかないので少なくともアクセシビリティのため or 代替テキストチックなもの ということがわかるフレーズを名前に含める必要はあると思います

2023-02-15 06:51 UTC, uknmr commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
意匠として表に出る可能性があった場合に I/F が変わるのは避けたいし、アクセシビリティや代替テキストと伝える必要を理解できていません!

2023-02-15 07:42 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
> 単純に名前からなんのためのdecoratorか分かりづらいかと

実装を見ればなんのためのdecoratorかはわかりますが、現状の名前ではどこに出すのか、なんのためのdecoratorなのかの伝達が不十分だと思います。

> 意匠として表に出る可能性があった場合に I/F が変わるのは避けたいし

逆にこれが理解できていないのですが、I/Fが変わるなどではなく、上述している通り、予想しやすい名前にしたいな、という感じです。

2023-02-15 08:15 UTC, uknmr commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
> なんのためのdecoratorなのかの伝達が不十分

これを伝える必要がないように思います。付けたいのはラベルなので可視だろうが不可視だろうが、`sortDirectionLabel` でラベルを表せてませんか?

2023-02-15 08:48 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +  onClick,
(相談)
実質sort時専用のhandlerになっていますし、名前専用にしたほうが良かったりしますかね...?
他の利用方法思いつかないため、基本的に問題ないとは思いますが...

2023-02-15 08:48 UTC, uknmr commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
特定したい気持ちもわかりますが、ラベルでも代替テキストでも不可視テキストでも変わらない役割としての名前を付けたいです。
意匠が変わる場合に props 名の変更はしたくないです。

2023-02-15 08:49 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +  onClick,
もしくはsort設定関係なくonClickは設定してしまうか...
https://github.com/kufu/smarthr-ui/pull/3128/files#diff-c005ac40cf7ed0fe9ef63656052603a6bc37ef72e8baed89961edb9b86c666e1R53

2023-02-15 08:49 UTC, uknmr commented on src/components/Table/Th.tsx
> +  onClick,
`decorators` ではなく `sortDirectionLabelDecorator` にする、みたいな認識であってますか?

2023-02-15 08:52 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +  onClick,
あ、コメント付ける箇所が1行ずれてました！
onClickに対するコメントです！

2023-02-15 08:55 UTC, uknmr commented on src/components/Table/Th.tsx
> +  onClick,
型で縛ってしまってもいいくらいだと思ったので名前も専用にするのも賛成です!
`onSortClick?: (sort: sortTypes) => void` みたいな感じかなぁ。

2023-02-15 08:57 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
> 意匠が変わる場合に props 名の変更はしたくない

こちらの気持ちもわかりますが、意匠が変わることによってその箇所を示せなくなるならそれは名前を変更するべきでbreaking-changeやむなしかと思います。
そもそも今回の対象テキストは `実装上複数のアイコンを一つにまとめた箇所に対する代替テキスト` だと思うのでそれが大幅に変更される可能性は低い気がします。

2023-02-15 09:02 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +  onClick,
いっそのこと `onSort` でいいかもしれません。
意図は伝わるし...
その場合、 Omitを使って onClick は設定できないようにしたいっすね

2023-02-16 01:08 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
ざっとまとめ

-  sortDirectionLabel だと利用者側からみてどこに設定されるかの解釈の余地が生まれてしまうので詳細な名前にしたい
- decoratorの名称だけで認識齟齬なく場所が特定できる名前が良い
- 今の所 `sortDirectionIconAlt` とか？

2023-02-16 01:28 UTC, uknmr commented on src/components/Table/Th.tsx
> +  onClick,
修正しました!
[d6104f0](https://github.com/kufu/smarthr-ui/pull/3128/commits/d6104f0a31ea4b8a235984322faefd85a3c75508)

2023-02-16 01:41 UTC, yamish123 commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
私も `sortDirectionIconAlt` ですかね〜。`sortDirectionLabel` だと、渡しの場合だと画面上のどこかに視覚的に表示されるのかな？という勘ぐりが発生した上でソースコード見に行っちゃうかも。

> 意匠が変わる場合に props 名の変更はしたくない

これぐらいの変更があるときはbreaking-changesで変えちゃっても良いと思うので、そこまで気にしなくてもいいかなとは思いました！

2023-02-16 01:49 UTC, uknmr commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
視覚的かどうかは関係ないだよなぁ、と思いつつ「開発者の生産性を損なわない」という意思の元に修正しました!
[b473205](https://github.com/kufu/smarthr-ui/pull/3128/commits/b473205420e9553799d47dbc7e8f123cbe139dcf)

2023-02-16 01:50 UTC, taconasu commented on src/components/Table/Th.tsx
> +      (decorators?.sortDirectionLabel?.(SORT_DIRECTION_LABEL[sort]) || SORT_DIRECTION_LABEL[sort]),
> 画面上のどこかに視覚的に表示されるのかな？という勘ぐりが発生した上でソースコード見に行っちゃうかも。

ここは僕も思いました〜。
`VisuallyHiddenText`よりは`Alt`の方が直感的に意図が理解できて好きです

2023-02-16 09:41 UTC, AtsushiM approved these changes
一部コメントしましたが LGTMです！
コメントは検討いただければ 🙏

2023-02-16 09:41 UTC, AtsushiM commented on src/components/Table/Th.tsx
> +  descending: '降順',
(nits)
めっちゃ悩ましいんですが、エンジニアとしては `asc` `desc` のほうがあきらかに馴染みがあるので省略形にしたいかも...
(DBにデータとして持っていたりする場合もある)

aria-sortに設定するときに `${sort}ending` とすればいいので実装でも困らないし...

2023-02-16 11:00 UTC, uknmr commented on src/components/Table/Th.tsx
> +  descending: '降順',
`aria-sort` のためにそのまま使ってただけなので、変換入れました!
[f936a58](https://github.com/kufu/smarthr-ui/pull/3128/commits/f936a58380980d5d525945c9ed7b5335b0940508)

2023-02-16 11:40 UTC, AtsushiM approved these changes
LGTM!

2023-02-16 12:32 UTC, merged