feat: FixColumnTableを追加
kufu/smarthr-ui pull request #3249
Opened 2023-04-05 02:16 UTC by kgsi

## Related URL

## Overview

## What I did

## Capture

2023-04-05 02:46 UTC, uknmr commented
パッと見の感想です!
- 左端の行頭に影がなさそう
- 用途に応じて Table と FixedColumnTable を使い分けるのは難しそう

2023-04-05 03:02 UTC, kgsi commented
@uknmr 
早速ありがとうございます！まだ自信がなかったのでレビューには出してなかったのですが

> 左端の行頭に影がなさそう

コレちょっと迷ってました！やはり行頭に影がないと結構違和感ありそうですかね？（CSSで背景を敷く必要があったので、技術的な難しさもありました）
コレが厳しいとやはり影をCSSのみでつけるのは難しそうです（JSで制御したほうが筋が良さそうです）

> 用途に応じて Table と FixedColumnTable を使い分けるのは難しそう

ここも一旦実装してみましたが悩みはありました。他の方法としてTableを`FixedColumnTable`に含まずに、Tableの外側に囲うwrapperのみを提供する...という方法が考えられると思うのですが、それだとどうですか？

```
<FixedColumnTableWrap> // 名前は適当
  <Table>...</Table>
</FixedColumnTableWrap>

```

2023-04-25 11:32 UTC, kgsi commented
社内で出た結論に基づいて対応

- Component名は`TableReel`に変更
- あくまでTableのWrapperとして定義
- 横へのスクロールを示唆するInnerShadowな表現を加える

2023-04-26 09:27 UTC, yamish123 commented on src/components/Table/Th.tsx
> +    `}
Th と Td で同じスタイルがコピペされてそうだったので、外出しして共通化出来ると良いな〜と思いました

2023-04-26 09:31 UTC, yamish123 commented on src/components/Table/TableReel.tsx
> +  /* stylelint-disable */
消し忘れ？

2023-04-26 09:33 UTC, yamish123 commented on src/components/Table/TableReel.tsx
> +type TableElementProps = Omit<HTMLAttributes<HTMLTableElement>, keyof Props>
これ、最終的には div タグに渡されていると思うのですが、`HTMLTableElement` を使っているのってどういう意図だったりしますか？

2023-04-26 11:25 UTC, kgsi commented on src/components/Table/TableReel.tsx
> +type TableElementProps = Omit<HTMLAttributes<HTMLTableElement>, keyof Props>
これ、前回までの名残ですね、消しました:pray:

2023-04-26 11:26 UTC, kgsi commented on src/components/Table/Th.tsx
> +    `}
TableReel内でexportして共通化してみましたー（utility的なファイルにまとめてみたほうが良いんですかね？）

2023-04-28 00:37 UTC, yamish123 commented on src/components/Table/Th.tsx
> +        transition: opacity 0.2s;
ASK
thだけtransitionが設定されているのって何か意図があったりするのでしょうか？
Storybook上で動作試してみたらthとtdでshadownの表示/非表示のタイミングが微妙にずれてそうだった

2023-04-28 01:27 UTC, kgsi commented on src/components/Table/Th.tsx
> +        transition: opacity 0.2s;
@yamish123 書き換え時の消し忘れでした！fixedにtransitionを付けなくとも動作するので削除しましたm

2023-04-28 01:32 UTC, yamish123 submitted a review, later dismissed
LGTM 🎉

2023-04-28 08:56 UTC, uknmr requested changes
`src/index.ts` での export を忘れてそうです!

それ以外も気になるところをコメントしてます!
imo は判断おまかせします!!

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/Table.stories.tsx
Table とは別コンポーネントになるので Story を分けても良さそうですが、どうですか?

以下の様な対応が考えられそうです!
- Table とは別に TableReel を作る
- Table の配下に all とは別に withTableReel を作る

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/Table.tsx
> +export const Table: FC<Props & ElementProps> = ({
ありがとう〜!

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +}
imo： 好みですが、React で型が提供されています

```suggestion
export type Props = PropsWithChildren
```

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +  }, [tableWrapperRef, setShowShadow])
imo： hooks に切り出した方が見通しがよくなりそう

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +export const reelShadow = ({ showShadow = true, direction = 'left' }: ReelShadow) => {
imo： Table が持ってるスタイルを Td で使う意味はなく共通のスタイルを使いたい意図だと思うので、別ファイルに出してよさそう。

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +      left: ${direction === 'left' ? '0' : '-12px'};
マジックナンバーをできるだけやめたい

```suggestion
      left: ${direction === 'left' ? '0' : space(-0.75)};
```

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +      height: 100%;
`positoin: absolute` なので、`inset-block: 0` を指定すれば `height` は不要です!

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +      pointer-events: none; /* 影の領域が広すぎるとクリッカブルエリアを侵食するので無効化 */
良いコメント:+1:

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +      transition: opacity 0.2s;
アニメーションのデザイントークン作りたいですね（別でやろ

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
色は theme.color から使っても良さそうかも? と思ったんだけど難しそうですか?

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +`
手元で確認してなくて申し訳なんですが、div を二重にしてるのって何故ですか?

2023-04-28 08:56 UTC, uknmr commented on src/components/Table/Td.tsx
> +            opacity: 1;
何故必要なのかコメントが合ったほうがよさそう!

2023-05-01 01:10 UTC, kgsi commented
> `src/index.ts` での export を忘れてそうです!

@uknmr 
ありがとうございます！取り急ぎこの件ですが、exportできてると思いますー、ほかは確認していきます！
https://github.com/kufu/smarthr-ui/pull/3249/files#diff-80b6424ab31f649afd7ee0ba6bb678d6249ecb58c56f982946a3f2033359413a

2023-05-01 05:01 UTC, uknmr commented
> src/index.ts での export を忘れてそうです!

ここへの追加が必要です!
https://github.com/kufu/smarthr-ui/blob/551d45a72b92b3cb7cdc4f884756238cd466b80a/src/index.ts#L61-L73

2023-05-01 05:08 UTC, kgsi commented on src/components/Table/TableReel.tsx
> +`
@uknmr スクロールさせるためのdivと、その上から固定で影をつけるためのdivとして２つ必要...という認識です！

2023-05-01 05:20 UTC, kgsi commented on src/components/Table/TableReel.tsx
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
themeをreelShadowにわたす必要が出てくるんですが、ここだけのために全部のコンポーネントからthemeを渡すのは、今の時点ではコスパが悪いかなぁと思うんですがどうですか？

2023-05-01 05:26 UTC, kgsi commented on src/components/Table/TableReel.tsx
> +export const reelShadow = ({ showShadow = true, direction = 'left' }: ReelShadow) => {
切り出しました

2023-05-01 05:33 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
reelShadow 内で `useTheme()` を使えないかしら?

2023-05-01 05:51 UTC, uknmr commented on src/components/Table/TableReel.tsx
> +  useReelCells(tableWrapperRef, setShowShadow)
こんな感じに書ける気がしました!

```suggestion
  const { showShadow, tableWrapperRef } = useReelCells()
```

2023-05-01 05:51 UTC, uknmr commented on src/components/Table/reelShadow.ts
> +  const shadowWidth = '12px' //影の横幅はpx指定で固定とする
こう書けそう

```suggestion
  const theme = useTheme()
  const shadowWidth = theme.space(0.75)
```

2023-05-01 05:51 UTC, uknmr commented on src/components/Table/reelShadow.ts
> +      inset-block: 0;
- `inset-block` なので `top` が不要になる
- `left` と近い方がよさそう

```suggestion
      inset-block: 0;
      left: ${direction === 'left' ? '0' : `-${shadowWidth}`};
      width: ${shadowWidth};
      pointer-events: none; /* 影の領域が広すぎるとクリッカブルエリアを侵食するので無効化 */
```

2023-05-01 05:51 UTC, uknmr commented on src/components/Table/Th.tsx
> +    transition: all 0.1s;
Table の方では `opacity 0.2s` となってたんですが、意図的ですか?

2023-05-01 05:52 UTC, kgsi commented on src/components/Table/TableReel.tsx
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
useThemeってHookかReactの関数内でしか呼べないんじゃなかったでしたっけ...と思ったけどこれをHookとして`useReelShadow`とかにすればいいのか。

2023-05-01 06:26 UTC, kgsi commented on src/components/Table/Th.tsx
> +    transition: all 0.1s;
あ、これは不要ですね！reelShadowで任せているので削除しましたー

2023-05-01 07:37 UTC, uknmr commented on src/components/Table/Th.tsx
> +  /** `true` のとき、TableReel内で左固定表示になる */
```suggestion
  /** `true` のとき、TableReel内で固定表示になる */
```

2023-05-01 07:37 UTC, uknmr commented on src/components/Table/Td.tsx
> +  /** `true` のとき、TableReel内で左固定表示になる */
```suggestion
  /** `true` のとき、TableReel内で固定表示になる */
```

2023-05-01 07:37 UTC, uknmr commented on src/components/Table/useReelShadow.ts
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
透明色は使えなそうですか?
https://smarthr.design/products/design-tokens/color/#h3-6

2023-05-01 07:37 UTC, uknmr commented on src/components/Table/Table.stories.tsx
> +        <TableReel style={{ whiteSpace: 'nowrap' }}>
機能に影響するわけではなさそうなので取ったほうがよさそう

```suggestion
        <TableReel>
```

2023-05-01 07:37 UTC, uknmr commented on src/components/Table/Table.stories.tsx
> +          <TableReel style={{ whiteSpace: 'nowrap' }}>
```suggestion
          <TableReel>
```

2023-05-01 07:37 UTC, uknmr commented on src/components/Table/Table.stories.tsx
> +WithReel.storyName = 'Table Reel'
純粋な提案

```suggestion
WithReel.storyName = 'with TableReel'
```

2023-05-01 07:37 UTC, uknmr commented on src/components/Table/Table.stories.tsx
> +        <TableReel style={{ whiteSpace: 'nowrap' }}>
Table を nowrap にすることがそれなりに多いので、Table に props で指定できるといいんですかね（別チケで!

2023-05-01 07:42 UTC, kgsi commented on src/components/Table/Table.stories.tsx
> +        <TableReel style={{ whiteSpace: 'nowrap' }}>
のほうがよさそうですねー

2023-05-01 07:44 UTC, kgsi commented on src/components/Table/useReelShadow.ts
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
@uknmr 透明色についてはかなり調整したので、このまま行きたい気持ちがありますー。`rgba(0, 0, 0, 0.2)`は頑張れば`TRANSPARENCY_15`に置き換えられそうだけど微妙に変わってしまいます。
`rgba(0, 0, 0, 0)`は`TRANSPARENCY_0`が合っても良さそう（別チケかな）

2023-05-01 07:57 UTC, uknmr commented on src/components/Table/useReelShadow.ts
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
`rgba(0, 0, 0, 0)` は `transparent` でどうですか?

```suggestion
      }, rgba(0, 0, 0, 0.2) 0%, transparent 100%);
```

2023-05-01 07:59 UTC, kgsi commented on src/components/Table/useReelShadow.ts
> +      }, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%);
あー、transparentで使えるんですね！（知らなかった）

2023-05-01 08:06 UTC, uknmr approved these changes
LGTM~

2023-05-01 08:15 UTC, merged