[WIP] chore: ui-props.jsonを作成するスクリプトを追加・JSONを作成
kufu/smarthr-ui pull request #3267
Opened 2023-04-14 04:23 UTC by yuw27b

## Related URL
https://github.com/kufu/smarthr-design-system-issues/issues/1220

## Overview
SmartHR Design System側でpropsの一覧を表示するため、ビルド後の`lib/**/*.d.ts`ファイルからJSONファイルを作っていますが、そのJSON作成スクリプトをこちらに移植しました。

- SDSでのProps表示例：https://smarthr.design/products/components/accordion-panel/#h2-0

### 移植した経緯
現在は最新バージョンのPropsのみを表示していますが、他のバージョンにも切り替えられるようにする予定です。その際には、過去のバージョンのprops定義もJSONファイルから取得できる必要があります。SmartHR UIの`public`ディレクトリ以下にJSONファイルを置いておき、Storybook（Chromatic）上に各バージョンのJSONが存在する状態にしたいです。

## What I did
- JSONを作るスクリプト（`scripts/exportUIProps.ts`）の追加
  - ベースはSDSのもの（https://github.com/kufu/smarthr-design-system/blob/main/scripts/exportUIProps.ts ）と同じです
- 書き出したJSONファイル（`public/exports/smarthr-ui-props.json`）自体の追加
- package.jsonへのスクリプト（`export:ui-props`）の追加
  - JSONを生成するためには、ビルド後の`lib`ディレクトリが存在している必要があるため、`yarn build:lib`も合わせて実行しています

### 自動実行の追加（未実装）
UIのバージョンが上がるタイミングで自動実行できると良いと考えています。
例えば以下のような実装だとどうでしょうか？（できるだけUI自体の運用の邪魔にならないようにしたいです。）

**案1：リリース作成のGitHub Actionsに挟み込む**
このあたり↓で`yarn export:ui-props`して`release-candidate`ブランチにコミットするようなイメージ
https://github.com/kufu/smarthr-ui/blob/68b63417f0d0c3ad7a045df1db6a62aebbb40864/.github/workflows/startRelease.yml#L50-L53

**案2：`husky`のpre-commitでトリガーする**
コミット時に`src`以下に変更があれば`yarn export:ui-props`を実行してJSONファイルをコミットに含める

## Capture
UIコンポーネント自体への影響はありません

2023-04-14 04:27 UTC, yuw27b commented on scripts/exportUIProps.ts
> +const relativePath = path.relative(process.cwd(), __dirname)
この部分はSDSでは
```
const SRC_PATH = path.join(__dirname, '../node_modules/smarthr-ui/lib/**/**.d.ts')
```
なのですが、`__dirname`のみだと絶対パスになり、実行環境が変わるとJSONファイルに差分が発生する可能性があるので、自動実行などを見越して相対パスにしました。

2023-04-18 02:33 UTC, yuw27b commented on .github/workflows/startRelease.yml
> +          git add public/exports/smarthr-ui-props.json && git diff --cached --exit-code --quiet || git commit -m 'Update smarthr-ui-props.json'
GitHub ActionsにJSON作成スクリプトの実行と、JSONに差分が出ればコミットするgitコマンドを追加しました。
この場所で問題ないかなどレビューいただければと思います。

2023-04-18 03:05 UTC, AtsushiM submitted a review, later dismissed

2023-04-18 03:08 UTC, yamish123 reviewed
全体的に良さそうでした！1点だけコメントしたので確認頂ければと思います 🙏

2023-04-18 03:08 UTC, yamish123 commented on .github/workflows/startRelease.yml
> +          git add public/exports/smarthr-ui-props.json && git diff --cached --exit-code --quiet || git commit -m 'Update smarthr-ui-props.json'
コミットメッセージは conventional commits のフォーマットになっている必要があるので、以下のように修正した方が良いかなと思いました！

```suggestion
          yarn export:ui-props
          git add public/exports/smarthr-ui-props.json && git diff --cached --exit-code --quiet || git commit -m 'chore: Update smarthr-ui-props.json'
```

2023-04-18 06:12 UTC, yuw27b commented
@yamish123 ありがとうございます！この点失念しておりました、すみません。suggestionを取り込ませていただきました。

2023-04-19 04:27 UTC, uknmr requested changes
一点気になりをコメントしました!

2023-04-19 04:27 UTC, uknmr commented on package.json
> +    "export:ui-props": "yarn build:lib && ts-node scripts/exportUIProps.ts"
scripts 内は yarn に依存していないように見えるため、run-s で書き換えた方が良いと考えました。

```suggestion
    "export:ui-props": "run-s build:lib 'ts-node scripts/exportUIProps.ts'"
```

提案の記述動作の確認はしていません:pray:

2023-04-20 01:06 UTC, yuw27b commented on package.json
> +    "export:ui-props": "yarn build:lib && ts-node scripts/exportUIProps.ts"
@uknmr ありがとうございます！確かにscripts内には`yarn`は出てきていないですね。

サジェストいただいたコードを手元で検証してみたのですが、

> ERROR: Task not found: "ts-node"

となってしまい、[ドキュメント](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md)など確認したところ`run-s`にはnpmスクリプトしか渡せないようでした。

ですので、例えば以下のように2つのタスクを定義するのはどうでしょうか？これであれば動作は大丈夫でした。
```
"write:ui-props": "ts-node scripts/exportUIProps.ts",
"export:ui-props": "run-s build:lib write:ui-props"
```

2023-04-20 01:29 UTC, uknmr commented on package.json
> +    "export:ui-props": "yarn build:lib && ts-node scripts/exportUIProps.ts"
分けて定義するで LGTM です!

2023-04-20 02:12 UTC, yuw27b commented on package.json
> +    "export:ui-props": "yarn build:lib && ts-node scripts/exportUIProps.ts"
ありがとうございます、修正しました：https://github.com/kufu/smarthr-ui/pull/3267/commits/56751396f12e5711e7a282f77589ce9548f25994

2023-04-20 02:17 UTC, uknmr approved these changes
LGTM~

2023-04-20 02:18 UTC, merged