feat: Enable ComboBox item.label to accept ReactNode
kufu/smarthr-ui pull request #3270
Opened 2023-04-17 06:10 UTC by MRTAFU

## Related URL
- https://smarthr.atlassian.net/browse/SHRUI-672

## Overview
SingleComboBox および MultiComboBox の `item.label` に対し、 `string` 型以外に `ReactNode` 型を渡せるように対応しました。

## What I did
- `item.label` が `ReactNode` の場合、それを `react-innertext` を用いてHTMLタグを除いた文字列に変換し、SingleComboBox の inputの文字列と部分一致検索ができるように対応しました。
- labelの型情報を `string` 型から `ReactNode`型に変更しました。

## Capture
| UI | 実際の要素 |
|---|----|
| ![スクリーンショット 2023-04-07 15 57 19](https://user-images.githubusercontent.com/13245326/230558418-a2c92d13-b95b-482c-9433-b8af1ce44613.png) | ![スクリーンショット 2023-04-07 15 58 38](https://user-images.githubusercontent.com/13245326/230558673-6162dad9-fa90-47e7-91da-0f04ea9cd185.png) |

2023-04-18 03:13 UTC, yamish123 approved these changes
コードの内容とStorybookでの挙動確認しました！
実装もイメージ通りで、testも書いてあって最高でした！！！

2023-04-19 04:42 UTC, uknmr requested changes
ありがとうございます! テストもあって素敵。SmartHR Pattern の方で、いい感じの使い方を書きたくなった!
気になりをコメントしました!!

2023-04-19 04:42 UTC, uknmr commented on src/components/ComboBox/ComboBox.stories.tsx
> +        <p>（ダミーテキストダミーテキストダミーテキストダミーテキスト）</p>
細かいですが、button には基本的にフレージング・コンテンツしか入らないため、div や p は入りません。
縦に並べたい場合は Stack[as=span] など別の方法を使う必要があります。

```suggestion
        <span>
          アイテムのラベルが<span>ReactNodeの場合</span>
        </span>
        <span>（ダミーテキストダミーテキストダミーテキストダミーテキスト）</span>
```

2023-04-19 04:42 UTC, uknmr commented on src/components/ComboBox/SingleComboBox.tsx
> +        typeof defaultItem.label === 'string' ? defaultItem.label : innerText(defaultItem.label),
innerText の内部的に `typeof hoge === 'string'` を判定してそうなのもあり、ここでは判定せずに `innetText(defaultItem.label)` としてもよさそうに見えました。
確実に判定して分けた方がよさそうですか?
https://github.com/CharlesStover/react-innertext/blob/master/src/index.ts

2023-04-19 04:42 UTC, uknmr commented on src/components/ComboBox/SingleComboBox.tsx
> +        typeof selectedItem.label === 'string' ? selectedItem.label : innerText(selectedItem.label),
同上。

2023-04-19 04:42 UTC, uknmr commented on src/components/ComboBox/useOptions.ts
> +      return convertMatchableString(typeof label === 'string' ? label : innerText(label)).includes(
ここも innerText だけでよさそう。

2023-04-19 23:50 UTC, MRTAFU commented on src/components/ComboBox/ComboBox.stories.tsx
> +        <p>（ダミーテキストダミーテキストダミーテキストダミーテキスト）</p>
全くもってその通りなので、修正させていただきました 🙏 
https://github.com/kufu/smarthr-ui/pull/3270/commits/a376a825c81c7c9a95fb0b32f9d87deff0ce15fb

2023-04-19 23:54 UTC, MRTAFU commented on src/components/ComboBox/SingleComboBox.tsx
> +        typeof defaultItem.label === 'string' ? defaultItem.label : innerText(defaultItem.label),
ライブラリ内の確認ありがとうございます！
不要な処理実行を避けたいという意図だったので、確かに内部で同様の判定があるので判定を取り除きました 👍 
https://github.com/kufu/smarthr-ui/pull/3270/commits/744ff262281e7f2428662ca1bb34037acb9b9398

2023-04-20 02:32 UTC, uknmr reviewed
もう一声入れされてもらいました!

2023-04-20 02:32 UTC, uknmr commented on src/components/ComboBox/ComboBox.stories.tsx
> +      </>
挙動としては問題ないんですが、Stack が内部的に `display: flex;` となり Stack しているだけなので、意図的には次の提案のようなコードが良さそうです。

```suggestion
      <Stack as="span" gap={0.25}>
        <span>アイテムのラベルがReactNodeの場合</span>
        <span>（ダミーテキストダミーテキストダミーテキストダミーテキスト）</span>
      </>
```

2023-04-20 04:38 UTC, MRTAFU commented on src/components/ComboBox/ComboBox.stories.tsx
> +      </>
Stackをstackされる側とユースケースを勘違いしてました 🙏
 こちらも修正済みです！
https://github.com/kufu/smarthr-ui/pull/3270/commits/bdfea4548e12df77ac8b6efaa12bc79c075dc03e

2023-04-20 05:04 UTC, uknmr commented on src/components/ComboBox/ComboBox.stories.tsx
> +      </>
良かったです!

2023-04-20 05:05 UTC, uknmr approved these changes
LGTM!

2023-04-20 05:05 UTC, merged