feat: FilterDropdown に responseMessage を渡せるようにする
kufu/smarthr-ui pull request #3348
Opened 2023-05-15 05:51 UTC by k-shirahama

## Related URL

## Overview

FilterDropdown に responseMessage を渡したいケースがある

## What I did

ActionDialogを参考に、responseMessage を渡せるようにした

## Capture

2023-05-15 05:53 UTC, k-shirahama commented on src/components/Dialog/ActionDialog/index.ts
> +export { responseMessageType } from './ActionDialogContentInner'
responseMessageTypeを使いたかったのでexportしたんですが、お作法があっているか不安です 🙏

2023-05-15 06:16 UTC, AtsushiM requested changes

2023-05-15 06:16 UTC, AtsushiM commented on src/components/Dialog/ActionDialog/index.ts
> +export { responseMessageType } from './ActionDialogContentInner'
これって `FilterDropdown` で `responseMessageType` を使いたいからexportしているって認識であっていますか？
`FilterDropdown` と `ActionDialog` は基本お互い関係がないコンポーネント同士なので `FilterDropdown` が `ActionDialog` の型に依存しちゃうのはおかしいかも。

1. FilterDropdownで `responseMessageType` を新規に型宣言する
2. https://github.com/kufu/smarthr-ui/blob/master/src/types/props.ts などに `responseMessageType` を移植、ActionDialogとFilterDropdownでimportする

のどちらかが良さそうな気がします！

2023-05-15 06:31 UTC, uknmr reviewed
imo だけ入れました!

2023-05-15 06:31 UTC, uknmr commented on src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
> +        <dt>Has response message success</dt>
imo: FilterDropdown を開いた時にメッセージを確認するわけではなく「適用」を押した際の “レスポンス” だと思うので、Story 上でそれが表せているとより良さそうです。

2023-05-15 06:31 UTC, uknmr commented on src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
> +          <Cluster gap={1} align={'center'} justify={'space-between'}>
imo： 特に問題ないですが、ここだけ書き方が違って気になりました。

```suggestion
          <Cluster gap={1} align="center" justify="space-between">
```

2023-05-15 10:29 UTC, k-shirahama commented on src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
> +          <Cluster gap={1} align={'center'} justify={'space-between'}>
@uknmr コメントありがとうございます。修正しました！https://github.com/kufu/smarthr-ui/pull/3348/commits/a0ac3ae5544ede0fddf4d87b2a27ec91f22a18f1

2023-05-15 10:29 UTC, k-shirahama commented on src/components/Dialog/ActionDialog/index.ts
> +export { responseMessageType } from './ActionDialogContentInner'
@AtsushiM コメントありがとうございます。2の方針で修正しました！https://github.com/kufu/smarthr-ui/pull/3348/commits/2b7f564773d31b809716e3d166eea55c98afa5f4

2023-05-15 10:30 UTC, AtsushiM commented on src/types/props.ts
> +    }
👍

2023-05-15 10:32 UTC, k-shirahama commented on src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
> +        <dt>Has response message success</dt>
@uknmr 
コメントありがとうございます。`dt` に指定しているテキストを修正した方が良さそうという意味であってますか？

2023-05-15 10:33 UTC, AtsushiM submitted a review, later dismissed
LGTM!
動作的なものは問題なさそうなので uknmr の指摘事項の確認 & 調整お願いします〜

2023-05-15 13:27 UTC, uknmr commented on src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
> +        <dt>Has response message success</dt>
ActionDialog と完全に同じではないんですが、「適用」を押したレスポンスとして responseMessage を表示する動的な Story があるとよさそう、という意味です。

responseMessage としては、success か error だけあればよさそうなので、`FilterDropdown` の children に「error を発生させるためのチェックボックス」を入れておく、とか。

参考： https://story.smarthr-ui.dev/?path=/story/dialog%EF%BC%88%E3%83%80%E3%82%A4%E3%82%A2%E3%83%AD%E3%82%B0%EF%BC%89-dialog--action-dialog

2023-05-16 02:44 UTC, nabeliwo approved these changes
1点細かいとこだけコメント書きましたが、LGTM です 🎉

2023-05-16 02:44 UTC, nabeliwo commented on src/types/props.ts
> +export type responseMessageType =
[nits] 元からなってた部分なのであれですが、型定義は UpperCamelCase にしていただきたいです 🙏

2023-05-16 03:33 UTC, k-shirahama commented on src/components/Dropdown/FilterDropdown/FilterDropdown.stories.tsx
> +        <dt>Has response message success</dt>
@uknmr 
丁寧なコメントありがとうございます！ActionDialogを参考に修正してみました。
https://github.com/kufu/smarthr-ui/pull/3348/commits/6e3703b135dc2dbcda05b31c4fdad9388016fa22

2023-05-16 03:33 UTC, k-shirahama commented on src/types/props.ts
> +export type responseMessageType =
@nabeliwo 
見落としてました 🙏 修正しました！https://github.com/kufu/smarthr-ui/pull/3348/commits/b257d2b2fb3c16050802293119cee3a3c2a21639

2023-05-16 05:54 UTC, AtsushiM approved these changes

2023-05-16 08:45 UTC, nabeliwo submitted a review, later dismissed

2023-05-16 09:22 UTC, uknmr submitted a review, later dismissed
LGTM~
（nits は無視でも問題ありません!!!

2023-05-16 09:22 UTC, uknmr commented on src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
>            )}
nits: この方が見通しよさそうかも?

```suggestion
          {responseMessage?.status === 'success' && (
            <Message>
              <FaCheckCircleIcon
                color={themes.color.MAIN}
                text={responseMessage.text}
                role="alert"
              />
            </Message>
          )}
          {responseMessage?.status === 'error' && (
            <Message>
              <FaExclamationCircleIcon
                color={themes.color.DANGER}
                text={responseMessage.text}
                role="alert"
              />
            </Message>
          )}
```

2023-05-16 09:29 UTC, k-shirahama commented on src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
>            )}
https://github.com/kufu/smarthr-ui/pull/3348/commits/5be554bdbed07c12f812787e43bbc13598081c61
修正しました！

2023-05-16 09:39 UTC, merged