feat!: DefinitionList を画面サイズに応じて列数を変化させる
kufu/smarthr-ui pull request #3418
Opened 2023-06-05 08:19 UTC by uknmr

## Related URL

## Overview

DefinitionList の I/F と振る舞いを見直しました。

- 標準では画面幅に応じて列数が増減
- `maxColumns` を指定すると、`maxColumns` 以内の列数で増減

## What I did

- `layout` は削除
- 最大列数を指定する `macColumns` を追加
- 標準のデフォルト幅は 12em–30em とした
  - 12em は日付が余裕を持って閲覧できる幅
  - 30em は長すぎず短すぎず CJK における最適幅の min 値
- 不要な型定義の export を削除
- Story を整理

## 気になってること

- nowrap を組みあせた時の段落ちがいまいち
- アイテム幅をはみ出てしまう場合に必ず段落ちさせつつ、余った領域は `flex-grow` する方法はないかしら
  - item に `fill?: boolean` みたいな props を渡せてもいいかも?
  - `fill = true` の時、`max-width` を消して、`flex-basis: 100%` とするイメージ

## Capture

2023-06-05 10:10 UTC, oti requested changes
@uknmr nowrap で折り返したカラムを flex-grow させるの、max-width をトルツメしたらできるっぽいです。ご確認お願いいたします！

2023-06-05 10:10 UTC, oti commented on src/components/DefinitionList/DefinitionList.tsx
> +    `}
```suggestion
```

> アイテム幅をはみ出てしまう場合に必ず段落ちさせつつ、余った領域は flex-grow する方法はないかしら

これって `maxColumns` 指定なしのときですかね？

`max-width` プロパティをトルツメしたらそんな動きになったように思います。

| 画面幅狭い | 画面幅広い |
| :---: | :---: |
| ![スクリーンショット 2023-06-05 19 04 33](https://github.com/kufu/smarthr-ui/assets/710216/e25c99a2-e609-4fbf-8fee-97b6b48a735d) | ![スクリーンショット 2023-06-05 19 05 02](https://github.com/kufu/smarthr-ui/assets/710216/32c1c2c5-c6eb-4714-a3be-d76e35d83a82) |

2023-06-05 11:17 UTC, uknmr commented on src/components/DefinitionList/DefinitionList.tsx
> +    `}
> maxColumns 指定なしのときですかね？

可能なら指定ありのときもです!
必要なのは nowrap を使った折り返しではなく、特定アイテムを幅いっぱいに表示されることな気がしてきました。

<img width="1167" alt="image" src="https://github.com/kufu/smarthr-ui/assets/19403400/43e06fc8-600e-43ee-85d7-8db9a3d30d9e">

2023-06-06 07:44 UTC, oti approved these changes
タイポっぽいのありましたが chore なのでLGTMです！

2023-06-06 07:44 UTC, oti commented on src/components/DefinitionList/DefinitionList.stories.tsx
> +        は項目の幅を最大化にし、できるだけ説明を折り返さずに表示できますグループ
```suggestion
        は項目の幅を最大化にし、できるだけ説明を折り返さずに表示できるグループ
```

2023-06-06 07:48 UTC, uknmr commented on src/components/DefinitionList/DefinitionList.stories.tsx
> +        は項目の幅を最大化にし、できるだけ説明を折り返さずに表示できますグループ
部署欄だから suffix にグループつければいいか、という意図的グループでした😇

2023-06-06 07:49 UTC, merged