feat: Icon の size をデザイントークンで指定するように変更
kufu/smarthr-ui pull request #3431
Opened 2023-06-09 06:59 UTC by taconasu

## Related URL

https://smarthr.atlassian.net/browse/SHRUI-668

## Overview

size は文字列・数値指定で px 単位を指定する非推奨なプロパティとして定義されていたが、デザイントークンによる指定で調整可能にしてサイズ変更を簡単かつ柔軟に指定できるようにしたい。

## What I did

- size の型を `FontSizes`型に変更
- 指定されたトークンに応じて`rem`値を算出するロジックを追加
  - テキストとアイコンを同等の扱いにするためText コンポーネントの実装に合わせている

## Capture

2023-06-09 09:10 UTC, uknmr requested changes

2023-06-09 09:10 UTC, uknmr commented on src/components/Icon/generateIcon.tsx
>     * アイコンの大きさ
提案!

```suggestion
   * アイコンの大きさ（フォントサイズの抽象値）
```

2023-06-09 09:10 UTC, uknmr commented on src/components/Icon/Icon.stories.tsx
>  )
`Size: Story` は指定を推奨していないので、ごっそり削ってもよさそうです!

2023-06-09 09:10 UTC, uknmr commented on src/components/ComboBox/MultiSelectedItem.tsx
> +              size="XS"
ローカルで確認してみたんですが、特に指定する必要はなさそうでした!（14px 時代の名残な気がします）

```suggestion
```

2023-06-09 09:10 UTC, uknmr commented on src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
> +const SmallFaCheckCircleIcon = styled(FaCheckCircleIcon)`
IMO!

```suggestion
const FilteredCheckIcon = styled(FaCheckCircleIcon)`
```

2023-06-12 08:38 UTC, taconasu commented on src/components/ComboBox/MultiSelectedItem.tsx
> +              size="XS"
おっ、そうなんですね👀？
指定しないパターンでも特にUIに違和感なかったので取り込みますー

2023-06-12 08:39 UTC, taconasu commented on src/components/Icon/Icon.stories.tsx
>  )
あ、それでいうとpx値指定からトークン指定に変わったことに伴ってsizeの`@deprecated`を削除してたりするんですが非推奨は継続なニュアンスの方が正しいんですかね？

2023-06-12 08:46 UTC, taconasu commented on src/components/Icon/generateIcon.tsx
> +    const iconSize = size ? theme.fontSize[size] : '1em' // 指定がない場合は親要素のフォントサイズを継承する
> size がなければ無指定（1em）になる

これマジですか・・・？undefinedにするとStoryの下の方のGitHub Icon が巨大化しますね...
DOMを確認してもundefinedを指定している場合にSVGに対して1emが渡っている感じがしないかも...

'1em'を渡すケース
![image](https://github.com/kufu/smarthr-ui/assets/38499847/66700aea-b63f-4368-9e43-3bcd445bd86f)

undefinedを渡すケース
![image](https://github.com/kufu/smarthr-ui/assets/38499847/dc7793b0-b91f-4be0-b52c-661eaaead374)

2023-06-12 08:48 UTC, taconasu commented on src/components/Icon/generateIcon.tsx
> +        height={iconSize}
https://github.com/kufu/smarthr-ui/pull/3431#discussion_r1226306606

と同様にこの指定を消すと同じくGitHubのアイコンのところが巨大化します🤔
サイズに合わせた領域を確保するように明示しておく分には実害がなさそうなのでこのままのほうが良いのではと思っているんですがどうなんでしょう...🥺

2023-06-12 09:04 UTC, taconasu commented on src/components/Dropdown/FilterDropdown/FilterDropdown.tsx
> +const SmallFaCheckCircleIcon = styled(FaCheckCircleIcon)`
040414b385c6c544fa455a5c002a03c38879f934

2023-06-13 01:05 UTC, taconasu commented on src/components/Icon/generateIcon.tsx
> +    const iconSize = size ? theme.fontSize[size] : '1em' // 指定がない場合は親要素のフォントサイズを継承する
あ、GitHubアイコンのやつは自前でSVGタグを用意しているパターンか🤔
このケースも救うならwidth, heightの指定とsize未指定時のデフォルトのsizeを`1em`にしておくのは残しで良いかと思ったんですが、どう思います？

2023-06-13 22:25 UTC, uknmr commented on src/components/Icon/Icon.stories.tsx
>  )
そうですね!
アイコンはテキストに近いもの（代替）と考えているので、基本的にはそのアイコンの親要素のフォントサイズをそのまま使えば問題ない場合が多いです。
https://story.smarthr-ui.dev/?path=/story/media%EF%BC%88%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2%EF%BC%89-icon--with-text

2023-06-13 22:39 UTC, uknmr commented on src/components/Icon/generateIcon.tsx
> +        height={iconSize}
size と width, height が全て指定されてるのに違和感があったので、`size={iconSize}` を消して、

```
width={iconSize}
height={iconSize}
```

を残すのが良さそうです!
react-icons の実装も size はただ width / height に入れてるだけでした。
https://github.com/react-icons/react-icons/blob/3faddeaca917520c312c5919d425473fd6fc5352/packages/react-icons/src/iconBase.tsx#L65-L66

2023-06-14 08:43 UTC, taconasu commented on src/components/Icon/generateIcon.tsx
> +        height={iconSize}
react-iconsのI/FとしてSVGのwidthとheightを決定づけるのが`size`プロパティだと思っているので

> size={iconSize} を消して

これだと正常にサイズのトークンを適用することができなくなりませんか？
実際sizeの指定を除くとサイズ変更ができなくなります。

また、widthとheightを同時に指定しているのは先に記載したような任意のSVGを使用した（react-iconsを介さない）パターンを救うためなので、どちらもカバーするのであれば3つとも指定しておく必要があると思っています🤔

2023-06-15 02:32 UTC, uknmr approved these changes
LGTM~

ハマったところにコメントの追記だけ入れされてもらいました!
https://github.com/kufu/smarthr-ui/pull/3431/commits/fa56351c9e295748b61acb4b25c318f6a8d42a84

2023-06-15 05:18 UTC, merged