fix: InformationPanelのHeadingが自動計算されるようにマークアップを変更する
kufu/smarthr-ui pull request #3525
Opened 2023-07-05 01:12 UTC by AtsushiM

## Related URL

## Overview

## What I did

## Capture

2023-07-06 04:44 UTC, uknmr requested changes

2023-07-06 04:44 UTC, uknmr commented on src/components/InformationPanel/InformationPanel.tsx
> +      <Section>
`role="region"` と `aria-labelledby` で既にランドマークロールが付与されているので見直した方が良さそうです。
`Base > Section` としてもよさそう。

2023-07-06 07:40 UTC, AtsushiM commented on src/components/InformationPanel/InformationPanel.tsx
> +      <Section>
お、なるほど。
ちょっと確認します

2023-07-06 07:47 UTC, AtsushiM commented on src/components/InformationPanel/InformationPanel.tsx
> +      <Section>
@uknmr 
Wrapperをsectionに、コード内に追加していた Section を SectioningFragmentに変更することで良い感じにしてみました

2023-07-06 08:32 UTC, uknmr commented on src/components/InformationPanel/InformationPanel.tsx
>        aria-labelledby={titleId}
`section > hn` と直下になってないとランドマークロールにならないんでしたっけ?
もしなるようであれば、`role=region` と `aria-labelledby` は消しても良さそう。

2023-07-06 08:34 UTC, AtsushiM commented on src/components/InformationPanel/InformationPanel.tsx
>        aria-labelledby={titleId}
SectioningFragmentはタグとしては出力されないので今までと変わらないかと

2023-07-06 08:57 UTC, uknmr commented on src/components/InformationPanel/InformationPanel.tsx
>        aria-labelledby={titleId}
div だった Base が forwardedAs で section になってます!

2023-07-06 23:36 UTC, AtsushiM commented on src/components/InformationPanel/InformationPanel.tsx
>        aria-labelledby={titleId}
あ、そういうことか。
消していいかも

2023-07-07 00:06 UTC, uknmr commented on src/components/InformationPanel/InformationPanel.tsx
>        aria-labelledby={titleId}
section が暗黙の `role=region` を持ってるので、`role=region` は消しても良さそうでした。
ランドマークロールにするためには明示的に `aria-label` や `aria-labelledby` を付けないと駄目そうだったので、`aria-labelledby` は残しで良さそうです!

2023-07-07 00:39 UTC, AtsushiM commented on src/components/InformationPanel/InformationPanel.tsx
>        aria-labelledby={titleId}
@uknmr 対応してみました

2023-07-07 02:10 UTC, uknmr approved these changes
LGTM~!

2023-07-07 02:18 UTC, merged