Fix eslint
kufu/smarthr-ui pull request #3554
Opened 2023-07-12 06:33 UTC by AtsushiM

## Related URL

## Overview

## What I did

## Capture

2023-07-13 00:48 UTC, yamish123 approved these changes
コード確認しました！
VRTの差分も出てないし、a11yのheading levelのエラーも出てないので良さそう 👍

2023-07-13 08:03 UTC, uknmr requested changes
コンポーネント名は UI 実装において、適切な抽象をするためにとても大切だと考えているので、eslint のチェックで名前が縛られすぎてしまうのはつらいな、と思いました!
外から渡すなり、Label や Title など Heading みのある名前は判定対象にできないかしら?

2023-07-13 08:50 UTC, AtsushiM commented on src/components/AppNavi/AppNavi.tsx
> +const StyledNav = styled(Nav)<{ themes: Theme }>`
> Q: HogeNav としないと lint できないから Nav 縛りをしている認識であってますか?

そうですね、navであることが名称からわからないとHeadingのoutlineのチェックが行えないので、という感じです。
WrapperNavが良さそうですね

2023-07-13 08:50 UTC, AtsushiM commented on src/components/Calendar/Calendar.tsx
> +const Container = styled.div<{ themes: Theme }>`
なるほど？
SectioningContentにする必要性もないところだしignore commentにしますか

2023-07-13 08:52 UTC, AtsushiM commented on src/components/Layout/Cluster/Cluster.stories.tsx
> +const StyledHeading = styled(Heading)`
いいえ、lint効きますが、他のファイルとここだけ命名ルールを変える意味もなさそうなので...
他はHeadingを例えばHogeHeadingに変えるという形でやっているのでここだけ smarthr-ui/Heading を shrHeadingにする意味はないな、という感じです

2023-07-13 08:52 UTC, AtsushiM commented on src/components/RadioButtonPanel/RadioButtonPanel.stories.tsx
> +          <Heading tag="h2" type="blockTitle">
tag消し忘れっぽいですね。
やっておきます

2023-07-13 09:21 UTC, uknmr commented on src/components/Layout/Cluster/Cluster.stories.tsx
> +const StyledHeading = styled(Heading)`
今回の修正だけ見ると、そうですが以下の書き方も smarthr-ui では StyledHoge よりも多い気がしているので元のままでもよさそうです。

```typescript
import { Hoge as shrHoge } from '../Hoge'
const Hoge = styled(shrHoge)``
```

2023-07-13 09:23 UTC, uknmr commented on src/components/SectioningContent/SectioningContent.stories.tsx
> +      {/* eslint-disable-next-line smarthr/a11y-heading-in-sectioning-content */}
理解しました!!
理想的には「あえてSectioningContentの中に入る可能性もあるだろうなぁ、その場合でもh1を出力する」これを要約したものを見出しにするとわかりやすそう。

2023-07-13 09:29 UTC, uknmr commented on src/components/RightFixedNote/RightFixedNote.tsx
> +const TextareaLabelHeading = styled(Heading)<{ themes: Theme }>`
Q: ここを変える必要性がわからなかったので、知りたい!

2023-07-13 23:19 UTC, AtsushiM commented on src/components/RightFixedNote/RightFixedNote.tsx
> +const TextareaLabelHeading = styled(Heading)<{ themes: Theme }>`
`コンポーネントがHeadingであること` を判定する方法は `/Heading$/` の正規表現にマッチするかどうかで行っています。
なのでHeadingの拡張なのにコンポーネント名がHeadingで終わっていないとチェックが狂ってしまうことになります。
なので `Styled(Heading)` をしているコンポーネントは `HogeHeading`になっていないとエラーになるルールがあるため調整しています

2023-07-13 23:21 UTC, AtsushiM commented on src/components/Layout/Cluster/Cluster.stories.tsx
> +const StyledHeading = styled(Heading)`
個人的には拡張しているところ(const Hoge = styled(shrHoge)``)まで読まないと `smarthr-ui/Heading` なのか `拡張しているHeading` なのかがわからなくなってしまうので強い意志がないなら今回の修正後のパターンに直したいなぁと思っています。

2023-07-13 23:22 UTC, AtsushiM commented on src/components/SectioningContent/SectioningContent.stories.tsx
> +      {/* eslint-disable-next-line smarthr/a11y-heading-in-sectioning-content */}
良さそう。
やっときますー

2023-07-13 23:49 UTC, yamish123 commented on src/components/Layout/Cluster/Cluster.stories.tsx
> +const StyledHeading = styled(Heading)`
> 個人的には拡張しているところ(const Hoge = styled(shrHoge)``)まで読まないと smarthr-ui/Heading なのか `拡張しているHeading` なのかがわからなくなってしまうので強い意志がないなら今回の修正後のパターンに直したいなぁと思っています。

ここは割りとアグリーっす！

2023-07-14 00:13 UTC, uknmr commented on src/components/RightFixedNote/RightFixedNote.tsx
> +const TextareaLabelHeading = styled(Heading)<{ themes: Theme }>`
`label > span` でも `Heading` にする理由がわかっていません!

2023-07-14 00:13 UTC, uknmr commented on src/components/Layout/Cluster/Cluster.stories.tsx
> +const StyledHeading = styled(Heading)`
👌

2023-07-14 00:25 UTC, AtsushiM commented on src/components/RightFixedNote/RightFixedNote.tsx
> +const TextareaLabelHeading = styled(Heading)<{ themes: Theme }>`
あ、ここspanを期待している箇所なんすね。
ならこちらのコンポーネントでspanであることを確定させたいっすね（あくまでここのコードだけならHeadingの拡張でしか無いので）

2023-07-14 00:32 UTC, AtsushiM commented on src/components/RightFixedNote/RightFixedNote.tsx
> +const TextareaLabelHeading = styled(Heading)<{ themes: Theme }>`
@uknmr 
- `TextareaLabelText` にリネーム
- attrsでtagとtypeを隠蔽して、利用する際にHeadingであることを意識する必要がないようにした
という感じで対応しました

https://github.com/kufu/smarthr-ui/pull/3554/files#diff-af57e50ae4cd1e26f5189cd1ff5dd3685283f6bc3d9e82154de452677e801e7dR93-R145

2023-07-14 00:51 UTC, AtsushiM commented
> 外から渡すなり、Label や Title など Heading みのある名前は判定対象にできないかしら?

`Title` はともかく、`Label` は labelタグである可能性が残るので無理っすねぇ...
Titleに関してはやってしまっても良さそうに思えますが、ワンちゃんtitleタグの可能性もある（headingの中身を書き換える系のコンポーネントなどで問題になるかもしれない）ので基本見出しであるなら名前はHeadingにそろえてもらうほうがメリットは大きいと思います

2023-07-14 01:49 UTC, uknmr commented on src/components/RightFixedNote/RightFixedNote.tsx
> +// eslint-disable-next-line smarthr/a11y-heading-in-sectioning-content
ここも disable 必要になるのかー!

2023-07-14 01:52 UTC, uknmr commented on src/components/RightFixedNote/RightFixedNote.tsx
> +const TextareaLabelHeading = styled(Heading)<{ themes: Theme }>`
👍

2023-07-14 02:05 UTC, AtsushiM commented on src/components/RightFixedNote/RightFixedNote.tsx
> +// eslint-disable-next-line smarthr/a11y-heading-in-sectioning-content
なりますねぇ 
`const TextareaLabelText = styled(Heading)` をチェックしていて `Headingを拡張しているな！だから名前はXxxxHeadingになってるかな？` というチェックがされているので。
attrsの中身まで見にいって tag に spanが設定されているか？をチェックすればdisableしなくても良くなりますがまぁレアケースかなぁ...
(そも今回の場合、作りたいものはHeadingではなくてLabelテキストの中身、なのでTextコンポーネント使って欲しさもある)

2023-07-14 02:13 UTC, uknmr commented on src/components/RightFixedNote/RightFixedNote.tsx
> +// eslint-disable-next-line smarthr/a11y-heading-in-sectioning-content
> Textコンポーネント使って欲しさ

たしかに!

2023-07-14 02:13 UTC, uknmr approved these changes

2023-07-14 02:13 UTC, merged