fix: Combobox系コンポーネント内で利用している"hidden"というclass名が外部cssに影響を受けないよう、prefixを追加
kufu/smarthr-ui pull request #3667
Opened 2023-08-25 07:20 UTC by AtsushiM

## Related URL

## Overview

## What I did

## Capture

2023-08-26 02:17 UTC, uknmr requested changes
プロダクト側が持つ問題をコンポーネントライブラリ側で解決してしまっているように見えるので、本当にライブラリ側で吸収する必要があるのか議論したいです。

また class で操作せず、`[aria-hidden]` や `[aria-disabled]` を使う方法もありそうです。

2023-08-27 22:53 UTC, AtsushiM commented
> プロダクト側が持つ問題をコンポーネントライブラリ側で解決してしまっているように見えるので、本当にライブラリ側で吸収する必要があるのか

一応プロダクト側の問題と言えそうですが、本質的には  `他ライブラリでも使われている可能性が高い名称が使われている` ことが問題であり、プロダクト側では解決出来ない場合が多々有りそうです
(実際bootstrapと組み合わせている場合などはbootstrapを排除する以外に対応が困難)

smarthr-uiで対応する場合、対象classなどの名称を変更するだけで対応でき、他ライブラリなどとの組み合わせ問題が起きる可能性も減らせることからsmarthr-uiで対応するほうが筋が良さそうに思います。

> また class で操作せず、[aria-hidden] や [aria-disabled] を使う方法もありそうです。

これ思いついてなかったので良いかも。
属性を設定している箇所によっては対応出来ないかもですが検討してみますね

2023-08-28 00:42 UTC, AtsushiM commented
@uknmr 
aria系属性はinputに直接設定されており、今回のhidden, disabled系classはそのwrapperについていたため、使えなさそうです。
Firefox系を無視すれば:hasで対応できそうですが、対応としては現在のclass名で対応するほうが筋が良さそうに思います

2023-08-28 02:09 UTC, uknmr commented
Bootstrap を組み合わせて使ってるのはコンポーネントライブラリから見ると想定外です。

> aria系属性はinputに直接設定されており、今回のhidden, disabled系classはそのwrapperについていたため、使えなさそう

👍 
Tailwind CSS 化も見えてきているためプロダクト側の根治を考えたほうがよさそうに思います。

2023-08-28 02:24 UTC, AtsushiM commented
> Bootstrap を組み合わせて使ってるのはコンポーネントライブラリから見ると想定外です。

想定外だとは思うんですが、現実として存在していますし、掛けるコストと実用性から考えるとsmarthr-ui側で対応するのもありかなぁと思っています
(例としてbootstrapを出しただけで、外部styleが当たってしまう可能性を減らしておくこと自体はベストプラクティス的に実施してもいいんじゃないかなぁ派です)

> Tailwind CSS 化も見えてきているためプロダクト側の根治を考えたほうがよさそうに思います。

個人的にはtailwindだから〜とか観点にはならない気がしています。
（上述のベストプラクティスの話とかに絡みますが、smarthr-uiで定義しているstyleであることは明示しておいた方がいいと思っている派なのでprefixは付けたいかなぁ...）

2023-08-29 02:54 UTC, Tokky0425 reviewed
クラス名ではなく、styled-components に props を渡す形で対応するのではどうですか？

イメージですが、
```tsx
const Container = styld.div`
  cursor: ${({ $disabled }) => $disabled ? 'not-allowd' : 'default'};
`
```
的な感じで良いのではないかと 🤔

2023-08-29 05:44 UTC, AtsushiM commented
@Tokky0425 
これstyleを再レンダリングしたくなくてあえてやってるのかと思っていました。
style再作成していいならprops渡すのありですね

2023-08-29 08:42 UTC, Tokky0425 commented
> これstyleを再レンダリングしたくなくてあえてやってるのかと思っていました。

styled-components のスタイル定義の再計算と style 要素へのインジェクト処理のコストが問題なのであれば、下記みたいな感じで回避できるはずです 👍 

```tsx
const Container = styld.div.attrs((props) => ({
  style: {
    cursor: props.$disabled ? 'not-allowed' : 'default',
  }
}))``
```

2023-08-30 00:07 UTC, AtsushiM commented
@Tokky0425 @uknmr 
attrsでstyle属性を書き換える方法に変更しました 🙏

2023-08-31 04:04 UTC, Tokky0425 reviewed
一点コメントしました！:pray:

2023-08-31 04:04 UTC, Tokky0425 commented on src/components/ComboBox/MultiComboBox.tsx
> +          <InputWrapper hidden={!isFocused}>
`hidden` だと HTML 要素に hidden がついてしまうので、`$hidden` にした方が良いかも〜と思いました！  (`display: none;` でいずれにしろアクセシビリティツリーからは消えているので hidden がついても別に問題はないんですが)

SingleComboBox の方も同じです！

2023-08-31 07:01 UTC, AtsushiM commented on src/components/ComboBox/MultiComboBox.tsx
> +          <InputWrapper hidden={!isFocused}>
ああ、hidden属性...
普段使わないから失念してました 🙇 
対応します〜

2023-09-01 01:39 UTC, Tokky0425 approved these changes
ありがとうございます！ 🌮

2023-09-01 03:28 UTC, uknmr approved these changes

2023-09-01 03:29 UTC, merged