Feat/textlink tailwind
kufu/smarthr-ui pull request #3844
Opened 2023-10-16 02:42 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2023-10-16 03:17 UTC, atzzCokeK commented
link-underlineを色まで指定するとリグレッションが発生していたので、色は指定しないように変更。命名も合わせてlink_underline -> underlineに変更
![image](https://github.com/kufu/smarthr-ui/assets/25091548/97da573a-999e-4e34-bfdf-a5c3b5047910)

2023-10-16 08:58 UTC, uknmr requested changes
PR で提案を入れてみました!
https://github.com/kufu/smarthr-ui/pull/3848

2023-10-16 08:58 UTC, uknmr commented on smarthr-ui-preset.ts
> +      underline: defaultShadow.UNDERLINE,
何の下線かわからないので明示したい。

```suggestion
      underline: defaultShadow.LINK_UNDERLINE,
```

2023-10-16 08:58 UTC, uknmr commented on src/themes/createShadow.ts
> +  UNDERLINE?: string
```suggestion
  LINK_UNDERLINE?: string
```

2023-10-16 08:58 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
>      const theme = useTheme()
消せそう。

2023-10-16 08:58 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +    color: 'TEXT_LINK',
Q: 元々 `color` props は存在しませんでしたが、必要そうですか?

2023-10-16 08:58 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +    underline: {
`underline` も既存にはなさそうです。

2023-10-17 07:49 UTC, atzzCokeK commented on src/components/TextLink/TextLink.tsx
> +    color: 'TEXT_LINK',
@uknmr 
ここでも指摘を書いてくださってましたね...:bow:

2023-10-17 07:54 UTC, uknmr approved these changes

2023-10-18 03:24 UTC, uknmr requested changes

2023-10-18 03:24 UTC, uknmr commented on src/components/TextLink/TextLink.tsx
> +type Props = VariantProps<typeof textLink> & {
見逃してました。
ここで `VariantProps<typeof textLink>` は `variants` を持たないため、`{}` となるのではないかと考えれらます。`variants` をそのまま props の型として使いたい場合でなければ使う必要はなさそうです。
https://www.tailwind-variants.org/docs/typescript

2023-10-18 03:25 UTC, atzzCokeK commented on src/components/TextLink/TextLink.tsx
> +type Props = VariantProps<typeof textLink> & {
たしかにすぎです🙇

2023-10-19 06:48 UTC, uknmr approved these changes
LGTM~

2023-10-19 06:54 UTC, merged