refactor: Loader を tailwindcss 化
kufu/smarthr-ui pull request #3985
Opened 2023-11-14 02:38 UTC by Tokky0425

## Related URL

## Overview

T/O

## What I did

## Capture

2023-11-14 02:40 UTC, Tokky0425 commented on src/smarthr-ui-preset.ts
Loader でしか使わないアニメーションなのに preset に書くのは微妙だなという気持ちがあるので、もう少しきれいに管理するための妙案募集中です！

2023-11-14 11:18 UTC, uknmr commented on src/components/Loader/Loader.tsx
> +        spinner: ['shr-w-[24px]', 'shr-h-[24px]'],
ある

```suggestion
        spinner: ['shr-w-1.5', 'shr-h-1.5'],
```

2023-11-14 11:18 UTC, uknmr commented on src/components/Loader/Loader.tsx
> +        spinner: ['shr-w-[48px]', 'shr-h-[48px]'],
ある

```suggestion
        spinner: ['shr-w-3', 'shr-h-3'],
```

2023-11-14 11:18 UTC, uknmr commented on src/components/Loader/Loader.tsx
> +          'shr-left-[-100%]',
ある

```suggestion
          '-shr-left-full',
```

2023-11-14 11:18 UTC, uknmr commented on src/components/Loader/Loader.tsx
>    className = '',
この初期化いらなくなるはずなので消したい。

```suggestion
  className,
```

2023-11-14 11:18 UTC, uknmr commented on src/components/Loader/Loader.tsx
> +  })
`wrapper({ className })` してるからここでは不要そう?

```suggestion
  const { wrapper, spinner, line, cog, cogInner, textSlot } = loaderStyle({
    type,
    size,
  })
```

2023-11-14 11:18 UTC, uknmr commented on src/smarthr-ui-preset.ts
keyframes はどうしようもなさそうですが、animation の方は arbitary value が使えそうです。
https://tailwindcss.com/docs/animation#arbitrary-values

2023-11-14 13:29 UTC, uknmr commented on src/components/Loader/Loader.tsx
> +    textSlot: ['shr-block', 'shr-mt-1', 'shr-text-base', 'shr-text-center'],
元にはなさそうに見えた（VRT で diff が出てるのもたぶんここ）

```suggestion
    textSlot: ['shr-mt-1', 'shr-text-base', 'shr-text-center'],
```

2023-11-16 02:37 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
> +    textSlot: ['shr-block', 'shr-mt-1', 'shr-text-base', 'shr-text-center'],
あ、申し送り忘れてましたが、ここは元の実装が inline 要素に対して margin-top が指定されていた関係で margin が効いてなかったので修正した感じです！
なので、VRT の diff は意図したものでした！

2023-11-20 08:40 UTC, Tokky0425 commented on src/smarthr-ui-preset.ts
arbitary values 使うの、やや見づらさがあったのでちょっと迷ったんですが、少なくとも preset に入れるのはあるべき姿ではないと思ったので animation は preset から剥がしました！
https://github.com/kufu/smarthr-ui/pull/3985/commits/883aab85ad644ec80f29a3b6186c1a640ff3c9ca

2023-11-20 08:41 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
>    className = '',
https://github.com/kufu/smarthr-ui/pull/3985/commits/ccdd64db4d41aea8da6ffcda18e828515a9d8a02 😎

2023-11-20 08:41 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
> +  })
https://github.com/kufu/smarthr-ui/pull/3985/commits/ccdd64db4d41aea8da6ffcda18e828515a9d8a02 😎

2023-11-20 08:41 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
> +          'shr-left-[-100%]',
https://github.com/kufu/smarthr-ui/pull/3985/commits/0a49503e3fdc9ddb0e235a281505d04b023c3944 👍

2023-11-20 08:41 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
> +        spinner: ['shr-w-[48px]', 'shr-h-[48px]'],
https://github.com/kufu/smarthr-ui/pull/3985/commits/0a49503e3fdc9ddb0e235a281505d04b023c3944 👍

2023-11-20 08:41 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
> +        spinner: ['shr-w-[24px]', 'shr-h-[24px]'],
https://github.com/kufu/smarthr-ui/pull/3985/commits/0a49503e3fdc9ddb0e235a281505d04b023c3944 👍

2023-11-20 08:42 UTC, Tokky0425 commented
@uknmr もろもろレビュー反映したので確認お願いします！

2023-11-20 13:15 UTC, uknmr requested changes
Button の VRT で差分が出ていました。

2023-11-20 13:15 UTC, uknmr commented on src/components/Loader/Loader.tsx
>  }
Button 内で使う場合など `as=span` として使いたい場合があるため、`as` props が必要そうです。

2023-11-20 13:15 UTC, uknmr commented on src/components/Loader/Loader.tsx
> +    spinner: [
元々ついていた `.s` を使った Button で VRT の差分が出ていました。
`.s` である必要はないですが、`smarthr-ui-Loader-spinner` などとクラス名を振って、Button 側で指定できると良さそうです。

2023-11-22 03:41 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
>  }
利用側で as=span と指定するのではなく、そもそも Loader を span タグで作ってしまえば良いのではと思ったのですが、何か懸念ありますかね？ 🤔

2023-11-22 05:20 UTC, Tokky0425 commented on src/components/Loader/Loader.tsx
> +    spinner: [
これ、`.s` だけじゃなくて `.light` に対しても Button 側でスタイルが当たっていることに気づきました 👁️ 
(更に `shr-border-disabled` が当たっていない要素がもう一つあって、s、light の代替に加えてもう1クラス用意しないといけなそう。キャプチャのローダーの色が白い部分)
<img width="154" alt="image" src="https://github.com/kufu/smarthr-ui/assets/14817308/ee83f14f-e239-4a8c-b47b-8edf7bd5a17f">

そうなってくると Loader 側で Button の実装を意識する部分が結構多くなってしまうな〜と思ったので、このタイミングで Loader の size に `xs` を用意したり、type に `disabled` (?) を用意したりする感じだとどうですかね？ (もしくは `insideButton` という props を生やしてこのあたりのスタイルをまとめて適用するか)

2023-11-22 05:52 UTC, uknmr commented on src/components/Loader/Loader.tsx
>  }
よさそう。ないです!

2023-11-22 05:58 UTC, uknmr commented on src/components/Loader/Loader.tsx
> +    spinner: [
`xs` も `type=disabled` もよさそうに思います!

2023-11-27 11:34 UTC, uknmr approved these changes
LGTM~

2023-11-28 01:30 UTC, merged