chore: LineClampのVRT用Storyを追加
kufu/smarthr-ui pull request #4024
Opened 2023-11-21 04:59 UTC by tomof

## Overview

LineClampコンポーネントにVRT用のStoryを追加しました。

## What I did

### VRT用Storyを追加
- VRT State
  - hover、activeを擬似的に指定した状態（その状態もスタイルによる装飾がないようなので、変化はありません）
- VRTUserHover
  - ユーザー操作のhoverをシミュレートしてツールチップを表示した状態
- VRTUserFocus
  - ユーザー操作のfocusをシミュレートしてツールチップを表示した状態
- VRT Forced Colors
  - forcedColors: 'active' を適用した状態。ツールチップが出ている状態が良いと考え、フォーカスしてツールチップが表示されている状態を対象にしています

LineClampのストーリーに対してVRT用のストーリーを追加しました。
他に必要なストーリーがあればご指摘ください。

2023-11-21 23:23 UTC, AtsushiM approved these changes

2023-11-22 01:14 UTC, uknmr requested changes
タブで移動すると、フォーカスリングが表示され Tooltip が表示されるので確認をお願いします!
<img width="487" alt="image" src="https://github.com/kufu/smarthr-ui/assets/19403400/4e190692-b2ee-416c-bb89-031688ac807b">

2023-11-22 01:15 UTC, uknmr commented
q: VRT State に hover や focus がありそうですが、別途 Story を切っている理由はありますか?

2023-11-24 02:11 UTC, tomof commented
@uknmr 

> タブで移動すると、フォーカスリングが表示され Tooltip が表示されるので確認をお願いします!
> q: VRT State に hover や focus がありそうですが、別途 Story を切っている理由はありますか?

疑似クラスを再現するプラグイン [storybook-addon-pseudo-states](https://www.npmjs.com/package/storybook-addon-pseudo-states) では、装飾の変化を反映するだけで、このようなツールチップを出すようなことは出来ないようでしたので、ユーザー操作をシミュレートするVRTUserHoverとVRTUserFocusを用意しました。ただし、Stroybookの実行ではツールチップは表示されますが、スクリーンショットに反映されまていませんね。調整致します🙇‍♂️

また、[chore: TabBarのVRT用Storyを追加でコメント](https://github.com/kufu/smarthr-ui/pull/3989)したように、ブラウザデフォルトの装飾も反映しないようですし、VRT Stateの方を取りやめて、ユーザー操作をシミュレートするVRTUserHoverとVRTUserFocusだけにするのが良さそうに思いますがいかがでしょうか？

2023-11-24 05:55 UTC, tomof commented
@uknmr 下記はそれぞれホバーやフォーカスでツールチップが表示された状態でスナップショットが撮られるように修正しました。[storybook-addon-pseudo-states](https://www.npmjs.com/package/storybook-addon-pseudo-states)を使用したVRT Stateでは前述のとおり、ツールチップを出すことができないので、このストーリー自体を削除したと考えていますがいかがでしょうか。

- VRTUserHover
- VRTUserFocus
- VRT Forced Colors

2023-11-28 01:28 UTC, uknmr commented
> [storybook-addon-pseudo-states](https://www.npmjs.com/package/storybook-addon-pseudo-states)を使用したVRT State

削除で良いと思います! @tomof

2023-11-28 05:22 UTC, tomof commented
@uknmr VRT State削除しました！

2023-11-28 05:51 UTC, uknmr approved these changes
ありがとうございます!

2023-11-28 05:52 UTC, merged