Refactor/shr UI 768
kufu/smarthr-ui pull request #4073
Opened 2023-12-04 02:42 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2023-12-04 03:27 UTC, atzzCokeK commented on src/components/Pagination/Pagination.tsx
> +      'shr-gap-x-0.5',
これまでmargin-left(first-child以外)等で指定されていた箇所をgapに置き換えました。
slotsでのclassNameの指定と、variantsでのclassNameの指定と、どちらもclass自体は当たるんですが、slotsのほうの適用が優先されてしまい、回避策としてgapを選択しました。ちなみに以下のような形で初めは実装していました。

```typescript
onst pagination = tv({
  slots: {
    wrapper: ['shr-inline-block', 'shr-max-w-full'],
    list: [
      'shr-flex',
      'shr-items-center',
      'shr-m-0.25',
      'shr-p-0',
      '[&>li:not(:first-child)]:shr-ml-0.5',
      '[&>li]:shr-list-none',
    ],
  },
  variants: {
    withoutNumbers: {
      true: {
        list: [
          '[&>li.smarthr-ui-Pagination-prev]:shr-ml-0.5',
          '[&>li.smarthr-ui-Pagination-last]:shr-ml-0.5',
        ],
      },
      false: {
        list: [
          '[&>li.smarthr-ui-Pagination-prev]:shr-mr-0.5',
          '[&>li.smarthr-ui-Pagination-next]:shr-ml-1',
        ],
      },
    },
  },
})
```
'[&>li:not(:first-child)]:shr-ml-0.5' が '[&>li.smarthr-ui-Pagination-next]:shr-ml-1' よりも優先されてしまう。variantで指定している & 詳細度的にも後者が優先だと思ったんですが、自分がなにか勘違いしていそうでお力貸してほしいです:bow:

<img width="335" alt="image" src="https://github.com/kufu/smarthr-ui/assets/25091548/c54966e1-a986-44a6-bf25-ac10f4f5354e">

2023-12-10 11:49 UTC, atzzCokeK commented on src/components/Button/ButtonWrapper.tsx
> +        'focus-visible:shr-bg-white-darken',
こちらはprefix漏れの対応

2023-12-13 08:01 UTC, atzzCokeK commented on src/components/Pagination/PaginationItem.tsx
> +        '[&&&]:disabled:shr-cursor-default',
ここはコメント入れてスタイルが当たるように調整しました。

2023-12-13 08:45 UTC, uknmr requested changes

2023-12-13 08:45 UTC, uknmr commented on src/components/Pagination/Pagination.tsx
> +      <li className={listItem({ first: true })}>
決まっているものに対して関数を呼び出しているのは違和感がありました!

- firstItem
- prevItem
- nextItem
- lastItem
という variants を用意すると良いかもと思いました。
listItem に書いてある基本スタイルは [Compound slots](https://www.tailwind-variants.org/docs/slots#compound-slots) の仕組みでなんとかなります。

2023-12-13 08:45 UTC, uknmr commented on src/components/Pagination/PaginationItem.tsx
> +        'active',
使わなくなったはずなので消しましょう!

```suggestion
```

2023-12-13 08:45 UTC, uknmr commented on src/components/Pagination/PaginationItem.tsx
>          disabled
この `disabled` や `onClick` を `page === currentPage` で分岐させれば if を消せそうですね!
以下、疑似コード。


```tsx
const current = page === currentPage

return (
  <Button
    ...
    onClick={() => !current && onClick(page)}
    disabled={current}
    aria-current={current ? "page" : ""}
    ...
  </Button>
)
```

2023-12-13 08:45 UTC, uknmr commented on src/components/Pagination/PaginationItem.tsx
> +        '[&&&]:disabled:shr-cursor-default',
`diabled` 属性の方の制御を `page === currentPage` で行い、ここはあくまで `active === true` 時のスタイルとして書いたほうがわかりやすいと思いました!

2023-12-13 08:45 UTC, uknmr commented on src/components/Pagination/Pagination.tsx
> +  const { wrapper, list, listItem } = pagination({ withoutNumbers })
useMemo したい

2023-12-28 03:12 UTC, atzzCokeK commented on src/components/Pagination/PaginationItem.tsx
> +        '[&&&]:disabled:shr-cursor-default',
ここですが以下のように変更しています :bow:
active => disabledに変えています。active用のStyleとdisabled時のStyleの区別がないと判断したからです。
```
https://github.com/kufu/smarthr-ui/pull/4073/files#diff-7ba47ebff2bb52850a6a6aca520e0473ee86d034563260dca0138f05601cd8c7R8-R18
```

ただ僕が正しく理解できず、u-sanのご指摘を誤解している🦆説がとてもありそう？なので遠慮なくおっしゃってください🙇

2024-01-08 23:50 UTC, uknmr requested changes
もう少し単純になりそうな気がしました!

2024-01-17 06:24 UTC, uknmr commented on src/components/Pagination/Pagination.tsx
> +    },
ムシで!

2024-01-17 13:04 UTC, uknmr approved these changes
LGTM~

2024-01-18 03:04 UTC, merged