[WIP] Chip コンポーネントを追加する
kufu/smarthr-ui pull request #4101
Opened 2023-12-08 09:05 UTC by oti

## Overview

ComboBox 内で使われていた `<MultiSelectedItem />` （下記画像ん矢印が示すもの）を切り出して、プロダクト側で自由に使いたいです。

![スクリーンショット_2023-12-08_17_53_17](https://github.com/kufu/smarthr-ui/assets/710216/87952344-9913-46ef-a304-890a068315a3)

プロダクト側で下記のような利用イメージを想定しています。

![スクリーンショット 2023-12-08 17 56 51](https://github.com/kufu/smarthr-ui/assets/710216/ab4c68b2-1453-43d6-9003-f6ac2ff77125)

## What I did

ComboBox から切り出そうとしましたが機能が複雑だったため、いったん超最低限の機能だけ備えた `<Chip />` コンポーネントを新規追加しました。

- ラベルが表示できる
- XXS〜XXL で文字の大きさを変えられる

## Capture

![スクリーンショット 2023-12-08 17 49 29](https://github.com/kufu/smarthr-ui/assets/710216/499e9017-1e95-468f-95fb-dec60c043990)

2023-12-08 11:00 UTC, uknmr requested changes
size 展開そんなに居るんだろうか? と思いました!
プロダクト側で利用の展開が見えていれば別ですが、MultiComboBox や添付の使用用途を見る限り、size="S" のみで始めても良さそうに見えました。

2023-12-08 11:00 UTC, uknmr commented on src/components/Chip/index.ts
> +export * from './Chip'
`/Chilp` に閉じたいファイルが混じった場合にも外に export されてしまうため、`Chip/index` は `Chip` の API と考え、外に出すべきものを明示するべきだと考えます。

あと、`src/index` の方への追記が必要です。
（`src/index` の方は逆に `Chip` に何があるかを考える必要がないので、`import * from` して良いと考えます）

2023-12-08 11:00 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +  const className = chip({ size })
- memo 化したい
- className が渡ってこないと styled-components が効かないので渡さないといけない
- 外から className を渡したい場合もある

```suggestion
  const className = useMemo(() => chip({ size, className }), [size, className])
```

2023-12-08 11:00 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +export const Chip: FC<Props> = ({ label, size = 'M' }) => {
```suggestion
export const Chip: FC<Props> = ({ size = 'M', className, ...props }) => {
```

とすると、

```tsx
return <span {...props} className={className} />
```

と書けそう。

2023-12-08 11:00 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +    'shr-box-border',
border-box は必要ですか?

2023-12-08 11:00 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +    'contrast-more:shr-border-high-contrast',
😍

2023-12-08 11:00 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +      S: ['shr-text-sm', 'shr-px-0.75', 'shr-py-0.5'],
MultiComboBox や添付の Figma に比べて padding が大きく、デブって見えますが意図的ですか?

2023-12-11 03:37 UTC, oti commented on src/components/Chip/Chip.tsx
> +    'shr-box-border',
これは不要でした〜

2023-12-11 03:38 UTC, oti commented on src/components/Chip/Chip.tsx
> +      S: ['shr-text-sm', 'shr-px-0.75', 'shr-py-0.5'],
size 別の展開をみたとき、やや窮屈な印象をうけたので 1 step 太らせてましたが、サイズをSにしぼってみると気にならくなったので、修正しました。

2023-12-11 03:38 UTC, oti commented on src/components/Chip/Chip.tsx
> +export const Chip: FC<Props> = ({ label, size = 'M' }) => {
{label} は表示に必要なのでそのままで、追加の属性を {...props} で受け取れるようにしました。

2023-12-11 03:39 UTC, oti commented
@uknmr レビューありがとうございます！　打ち返し確認お願いします:bow:

2023-12-11 06:47 UTC, uknmr requested changes

2023-12-11 06:47 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +export type Props = {
`React.CompnentProps<typeof Hoge>` のような呼び出しで型は作れるので、基本的に `export` は不要と考えています。

```suggestion
type Props = {
```

2023-12-11 06:47 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +export const chip = tv({
スタイリングの export も外から使う場面が出たタイミングで考えたい。

```suggestion
const chip = tv({
```

2023-12-11 06:47 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +}
- React.CompnentProps<typeof Hoge> のような呼び出しで型は作れるので、基本的に export は不要
- label は children の方がよさそう（PropsWithChildren がそれ）
  - `<Chip label="最終評価記号" />` とするよりも
  - `<Chip>最終評価記号</Chip>` とした方がよさそう
- `size` だけ抜く必要はなさそう
- `className` 以外にも `span` が持つ属性を渡せたほうがよさそう


```suggestion
type Props = PropsWithChildren & VariantProps<typeof chip> & ComponentPropsWithoutRef<'span'>
```

2023-12-11 06:47 UTC, uknmr commented on src/components/Chip/Chip.tsx
> +      S: ['shr-text-sm', 'shr-px-0.5', 'shr-py-0.25'],
コンポーネント系のサイズ指定が現状小文字の `s` になってる物が多いため、一旦そっちに寄せて、どこかのタイミングで揃えたい、という気持ちです。

```suggestion
      s: ['shr-text-sm', 'shr-px-0.5', 'shr-py-0.25'],
```

2023-12-11 06:47 UTC, uknmr commented on src/components/Chip/Chip.stories.tsx
> +  </Stack>
- 謎の `dl` と Stack が残ってそう
- Cluster の方がよく組み合わされそう
- ラベルや Label、label などのバリエーション意図がわからなかった
- `aria-label` もなくてもよさそう

```suggestion
  <Cluster align="center">
    <Chip label="ラベル" />
    <Chip label="Label ラベル" aria-label="ラベル" />
  </Stack>
```

2023-12-11 06:50 UTC, uknmr commented
@oti 送ったと思ってたコメントが送れてなかったりして、やや二度手間な返信になってしまいました:pray:

2023-12-11 06:58 UTC, oti commented on src/components/Chip/Chip.stories.tsx
> +  </Stack>
`aria-label` は他の属性も渡せるんだよを示したかったためですが、他コンポーネントの基本設計としてできる前提ですかね？　であれば承知しましま。

2023-12-11 07:10 UTC, uknmr commented on src/components/Chip/Chip.stories.tsx
> +  </Stack>
> 他コンポーネントの基本設計としてできる前提です

認識の通りです!
アイコンを渡す場合などに例として追加するとよさそうに思いました。

2023-12-11 07:39 UTC, oti commented on src/components/Chip/Chip.tsx
> +}
@uknmr 他コンポーネントを見ると `PropsWithChildren<Hoge>` でジェネリクスで書いてるものが圧倒的に多かったのでジェネリクスにしてみました。

FYI: TableReel.tsx でだけ `PropsWithChildren & Hoge` が使われてました

2023-12-11 07:44 UTC, oti commented
@uknmr children にするは :naruhodo: でした。度々ありがとうございました。指摘箇所修正したので確認お願いいたします :bow:

2023-12-11 07:57 UTC, uknmr approved these changes
oti さんにまだ権限がなく CI が回りきってなかったので、ローカルで `yarn lint` して確認しました。
Chromatic も動いてないですが、Storybook を見て問題なさそう & 新規追加なのでなくても問題なしと判断しました!

2023-12-11 07:58 UTC, merged