fix: AccordionPanelTrigger 内の見出しテキストで折り返しが発生する際に、アイコンとの間に改行が発生しないようにする
kufu/smarthr-ui pull request #4151
Opened 2023-12-28 01:47 UTC by s-sasaki-0529

## Related URL

N/A

## Overview

`<AccordionPanel>` を構成する `<AccordionPanelTrigger>` の見出しテキストの折り返し時の挙動を調整したいです。

## What I did

`<AccordionPanelTrigger>` コンポーネントの `children` のコンテンツ幅がコンテナを溢れた際に、`children` が幅を確保しようとコンテナ全体が折り返してしまいます。 (Capture の before 参照)

これは v39.0.1 からそのような挙動をするようになり、おそらくは以下PRでの tailwindcss 化の際に `<Cluster>` で横並びにした影響かと思われます。

- https://github.com/kufu/smarthr-ui/pull/3935 

他の既存挙動に影響が出ず、差支えがなければコンテナ自体が折り返さないようにスタイルを調整して、以前の状態 (Capture の after 参照) に戻したいのですが如何でしょうか？

## Capture

|before|after|
|----|---|
|![スクリーンショット 2023-12-27 22 30 40](https://github.com/kufu/smarthr-ui/assets/16274215/33cc634d-d937-4890-908b-a75d0b44dc0a)|![スクリーンショット 2023-12-27 22 30 23](https://github.com/kufu/smarthr-ui/assets/16274215/28f5377a-e95e-48e0-9dc2-78f4e5042d92)|

2023-12-28 02:08 UTC, s-sasaki-0529 commented on src/components/AccordionPanel/AccordionPanelTrigger.tsx
> +    title: 'shr-flex-1',
正確には `flex-basis: 0` がほしいだけ。

2023-12-31 12:39 UTC, uknmr reviewed
`Cluster` の箇所に `className="shr-flex-nowrap"` を追加し、left / rightIcon に対して `shrink-0` を足すのが良さそうに見えました!

2024-01-09 03:19 UTC, s-sasaki-0529 commented
@uknmr 

> Cluster の箇所に className="shr-flex-nowrap" を追加し、left / rightIcon に対して shrink-0 を足すのが良さそうに見えました!

ありがとうございます！確かにそのほうが実現したいことに対して最低限の対応で済ませられそうです！
修正してみましたが如何でしょうか？

2024-01-09 03:26 UTC, uknmr requested changes

2024-01-09 03:26 UTC, uknmr commented on src/components/AccordionPanel/AccordionPanelTrigger.tsx
> +    rightIcon: 'group-aria-expanded:-shr-rotate-180:shrink-0',
元の記述が効かなくなってました!（Chromatic の差分はここでした）

```suggestion
    leftIcon: 'group-aria-expanded:shr-rotate-90 group-aria-expanded:shrink-0',
    rightIcon: 'group-aria-expanded:-shr-rotate-180 group-aria-expanded:shrink-0',
```

2024-01-09 03:27 UTC, s-sasaki-0529 commented on src/components/AccordionPanel/AccordionPanelTrigger.tsx
> +    rightIcon: 'group-aria-expanded:-shr-rotate-180:shrink-0',
失礼しました！今一生懸命 VRT 結果を眺めてるところでした 🙏

2024-01-09 03:33 UTC, uknmr approved these changes
LGTM~!

2024-01-09 23:16 UTC, AtsushiM approved these changes

2024-01-10 09:57 UTC, merged