fix: PageCounterの-にaria-labelを追加する
kufu/smarthr-ui pull request #4297
Opened 2024-02-08 06:02 UTC by TakahiroHimi

## Related URL

## Overview

## What I did

## Capture

2024-02-08 08:58 UTC, uknmr commented
decorator の追加も必要そう。

2024-02-09 12:41 UTC, TakahiroHimi commented on src/components/PageCounter/PageCounter.tsx
> +  }
`aria-label`は文字列しか受け付けないので、そのような型定義にしています。

2024-02-09 12:44 UTC, TakahiroHimi commented on src/components/PageCounter/PageCounter.tsx
> +): ExecuteDecoratorReturn<T> => {
`decorator`の方が`DecoratorType`だったら`ReactNode`、`string`か`undefined`だったら`string`を返すような型で定義しています。
可読性に自信を持てないコードになってしまったので、より良い形があったら教えていただきたいです…🙏

2024-02-09 13:19 UTC, oti requested changes
画像でないものを画像として扱うのは違和感ありました。

title 属性をつけるのはどうでしょうか？　ツールチップが出ますが出ても支障ないと思います。

title 属性でうまく読み上げられない場合は、Visually Hidden なテキストも試してみたいです。

両方ともすでに検討・検証済みでしたらすみません:pray:

2024-02-09 13:19 UTC, oti commented on src/components/PageCounter/PageCounter.tsx
> +        </span>
```suggestion
        <span title={rangeSeparator}>
          –
        </span>
```

2024-02-14 05:44 UTC, TakahiroHimi commented on src/components/PageCounter/PageCounter.tsx
> +        </span>
@oti 
ご指摘ありがとうございます🙏
titleだとNVDAで読み上げられないようだったので、Visually Hiddenを利用する方向で修正しました！
この形であれば正常に読み上げられることを確認しております 🙇 

https://github.com/kufu/smarthr-ui/pull/4297/commits/39f0a58f5fcddb30ca4f12c3c88e73ff37bf7bd4

2024-02-14 08:22 UTC, uknmr reviewed
decorator や型以外のところは自信ないですが、本筋の修正に対して LGTM!

2024-02-14 08:30 UTC, oti approved these changes
`<VisuallyHidden />` についてはLGTMです！
僕も型定義部分に自身がないので @AtsushiM @Tokky0425 にもレビューをいただきたい所存です :bow:

2024-02-14 09:04 UTC, Tokky0425 reviewed
一見気になりをコメントしました！

2024-02-14 09:04 UTC, Tokky0425 commented on src/components/PageCounter/PageCounter.tsx
> +  )
`executeDecorator` を無理に噛ませないで

```ts
const rangeSeparator = decorators?.rangeSeparator ?? RANGE_SEPARATOR
```

でも良いのかなと思ったんですがどうですかね？ 🤔

2024-02-14 09:21 UTC, TakahiroHimi commented on src/components/PageCounter/PageCounter.tsx
> +  )
@Tokky0425 

完全同意で「私はいったい何と戦ってたんだ」の気持ちになったので修正しました！
ご指摘ありがとうございます🙏

https://github.com/kufu/smarthr-ui/pull/4297/commits/9fd79db50668b77e9a9e6e2f67dc5d2476cafcfd

2024-02-14 09:27 UTC, Tokky0425 approved these changes
LGTM! 🌮

2024-02-14 10:27 UTC, merged