refactor: HeaderLinkをTailwindCSS化する
kufu/smarthr-ui pull request #4326
Opened 2024-02-16 05:38 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2024-02-16 05:41 UTC, atzzCokeK commented on src/components/Header/HeaderLink.tsx
> +type Props = PropsWithChildren<ComponentProps<typeof TextLink>>
このPropsの書き方これでいいのか！？が不安なので重点的に見てもらいたいです :bow:

2024-02-16 06:30 UTC, atzzCokeK commented on src/components/Header/HeaderLink.tsx
> +    href={props.href}
eslintのルールに引っかかるので、こちらはhrefを指定

2024-02-16 07:26 UTC, uknmr requested changes

2024-02-16 07:26 UTC, uknmr commented on src/components/Header/HeaderLink.tsx
> +type Props = PropsWithChildren<ComponentProps<typeof TextLink>>
`children` を明示的に追加する必要ないので不要

```suggestion
type Props = ComponentProps<typeof TextLink>
```

2024-02-16 07:26 UTC, uknmr commented on src/components/Header/HeaderLink.tsx
> +  <TextLink
href は props に含まれていて、このコンポーネントで考える必要はないので disabled で問題なし。


```suggestion
  // eslint-disable-next-line smarthr/a11y-anchor-has-href-attribute
  <TextLink
```

2024-02-16 07:26 UTC, uknmr commented on src/components/Header/HeaderLink.tsx
> +    className="smarthr-ui-header-link shr-pe-0.25 shr-ps-0.25 shr-text-white shr-shadow-none focus-visible:shr-focus-indicator hover:shr-text-white [&:not(focus-visible)]:shr-shadow-none"
- `smarthr-ui-header-link` はどこから来たのかわからなかった
- `hoge-inline` は `hoge-x` で書けます
- `[&:not(focus-visible)]:shr-shadow-none` は必要そうでした? `shr-shadow-none` が詳細度で負けてる気がしました

```suggestion
    className="shr-px-0.25 shr-text-white focus-visible:shr-focus-indicator hover:shr-text-white [&]:shr-shadow-none"
```

2024-02-16 07:29 UTC, atzzCokeK commented on src/components/Header/HeaderLink.tsx
> +    className="smarthr-ui-header-link shr-pe-0.25 shr-ps-0.25 shr-text-white shr-shadow-none focus-visible:shr-focus-indicator hover:shr-text-white [&:not(focus-visible)]:shr-shadow-none"
@uknmr 

>smarthr-ui-header-link
残り返信するんですが、こちらは足しました！！取り急ぎ...いらないようであれば消します :+1: つける付けないって基準あるんですか？

2024-02-16 07:57 UTC, uknmr commented on src/components/Header/HeaderLink.tsx
> +    className="smarthr-ui-header-link shr-pe-0.25 shr-ps-0.25 shr-text-white shr-shadow-none focus-visible:shr-focus-indicator hover:shr-text-white [&:not(focus-visible)]:shr-shadow-none"
基準ないんですが、外から万が一スタイリングに手を入れたい場合に用意してるものなので、今回のようなコンポーネントの DOM が入れ子になっていないものは不要ですね。
書き方は定まっていて `smarthr-ui-ComponentName-subName` となってます。

2024-02-21 04:57 UTC, atzzCokeK commented on src/components/Header/HeaderLink.tsx
> +    className="smarthr-ui-header-link shr-pe-0.25 shr-ps-0.25 shr-text-white shr-shadow-none focus-visible:shr-focus-indicator hover:shr-text-white [&:not(focus-visible)]:shr-shadow-none"
@uknmr 
>[&:not(focus-visible)]:shr-shadow-none は必要そうでした? 

はい、こちらはshr-shadow-noneだと以下のようになってしまっていたので追記しています。
shr-shadow-none単体は不要そうになったので削除しました。
![image](https://github.com/kufu/smarthr-ui/assets/25091548/f8528698-19cc-4c2b-9b81-e2b920178f15)

2024-02-21 09:30 UTC, atzzCokeK commented on src/components/Header/HeaderLink.tsx
> +    className="shr-px-0.25 shr-text-white focus-visible:shr-focus-indicator hover:shr-text-white [&:not(focus-visible)]:shr-shadow-none"
ありがとうございます！修正しました！

2024-02-21 10:42 UTC, uknmr approved these changes
LGTM~

2024-02-21 10:42 UTC, merged