fix: フォーカス時のスタイルを修正
kufu/smarthr-ui pull request #4327
Opened 2024-02-16 06:22 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2024-02-22 00:01 UTC, atzzCokeK commented on src/components/AccordionPanel/AccordionPanelTrigger.tsx
> -      'focus-visible:shr-focusIndicator',
'focus-visible:shr-focus-indicator' に直してみるとUIのフォーカス時の表示が崩れてしまうので、typoを直すのではなく削除する方針にしました。
<img width="1909" alt="image" src="https://github.com/kufu/smarthr-ui/assets/25091548/259fad09-e113-4c02-b781-1963d702873d">

2024-02-22 00:02 UTC, atzzCokeK commented on src/components/Tooltip/Tooltip.tsx
> -    'focus-visible:shr-focusIndicator',
<img width="1592" alt="image" src="https://github.com/kufu/smarthr-ui/assets/25091548/5aea0567-a77f-44a6-9ea4-0a4f9db2e4ef">

2024-02-22 00:15 UTC, uknmr requested changes
https://github.com/kufu/smarthr-ui/pull/4032 の前後に作られた PR で編集漏れがでてしまったように見えました。
tailwindcss 化前の状態を正としたいので、消さずに残しでお願いします!
https://github.com/kufu/smarthr-ui/pull/3935/files#diff-7e15c291156b852cfaa8e9b029b1342d8692fdd8ab6ff8f3ff47ac60593f7280L115-L117

2024-02-22 00:17 UTC, atzzCokeK commented
@uknmr 
ありがとうございます
つまり'focus-visible:shr-focus-indicator'に修正する方針ってことでしょうか？:eyes:

2024-02-22 01:16 UTC, uknmr commented
@atzzCokeK あってます!

2024-03-22 06:20 UTC, uknmr approved these changes
LGTM

2024-03-22 06:20 UTC, uknmr commented on src/components/Tooltip/Tooltip.tsx
> -    'focus-visible:shr-focusIndicator',
Tooltip でちゃんと効いていたので戻しました! [8cf0a7](https://github.com/kufu/smarthr-ui/pull/4327/commits/78cf0a7d412e17d6d9f83a02f6f7f9dd818100ca)

2024-03-22 06:35 UTC, merged