fix: BottomFiexArea を Tailwind CSS 化し、normalize 依存を修正
kufu/smarthr-ui pull request #4436
Opened 2024-03-13 07:13 UTC by uknmr

## Related URL

- https://smarthr.atlassian.net/browse/SHRUI-845
- https://smarthr.atlassian.net/browse/SHRUI-904

## Overview

## What I did

## Capture

2024-03-15 21:10 UTC, atzzCokeK commented on src/components/BottomFixedArea/BottomFixedArea.stories.tsx
> +    secondaryButton={<Button>キャンセル</Button>}
日本語化もありがとうございます

2024-03-15 21:14 UTC, atzzCokeK requested changes
コメントしました！

2024-03-15 21:14 UTC, atzzCokeK commented on src/components/BottomFixedArea/BottomFixedArea.tsx
> +      '',
空文字入ってそう

2024-03-16 00:33 UTC, uknmr commented on src/components/BottomFixedArea/BottomFixedArea.tsx
> +      '',
🙏 https://github.com/kufu/smarthr-ui/pull/4436/commits/5f662b2131f1f8bcf29b0583390196ff555bfb5f

2024-03-16 05:17 UTC, atzzCokeK approved these changes
LGTM

2024-03-16 05:43 UTC, merged