refactor: HeaderDropdownMenuButtonをTailwindCSS化
kufu/smarthr-ui pull request #4454
Opened 2024-03-15 22:29 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2024-03-16 04:49 UTC, uknmr requested changes

2024-03-16 04:49 UTC, uknmr commented on src/components/Header/HeaderDropdownMenuButton.tsx
> +  ],
DropdownMenuButton の tailwind-variants 定義である `dropdownMenuButton` を export して override するとよさそう。
https://www.tailwind-variants.org/docs/overriding-styles

2024-03-16 05:01 UTC, atzzCokeK commented on src/components/Header/HeaderDropdownMenuButton.tsx
> +// })
:sorry-desu:

2024-03-18 15:44 UTC, atzzCokeK commented on src/components/Header/HeaderDropdownMenuButton.tsx
> +}: ComponentPropsWithRef<typeof DropdownMenuButton>) => {
restは"残りのprops"という意味で自分は使うことがあったんですが、SmartHR UI基準に合わせておいたほうが良さそうですね！ありがとうございます。

一応使われていますよということだけ残しておきます🙇
https://github.com/search?q=...rest%7D&type=code

2024-03-18 16:37 UTC, atzzCokeK commented on src/components/Header/HeaderDropdownMenuButton.tsx
> +  ],
これ確認したいんですが、結局<DropdownMenuButton>は使い続けつつっていう感じですよね？🌞
classNameは、triggerWrapperに内部的にマージされてしまうので、triggerButton用のclassNameをpropsに生やしてあげるイメージでしょうか？:bow: 何かしらの方法でtriggerWrapperにマージされることなく、triggerButtonにマージされるようにする必要がありそうです。

```typescript
const headerDropdownMenuButton = tv({
  extend: dropdownMenuButton,
  slots: {
    triggerButton: [
      dropdownMenuButton.slots.triggerButton,
      'shr-border-transparent shr-bg-transparent shr-pe-0.25 shr-ps-0.25 shr-font-normal shr-text-white',
      // ボタンの余白分だけ微調整
      'last-of-type:-shr-me-0.25',
    ],
  },
})
```

2024-03-18 23:43 UTC, uknmr commented on src/components/Header/HeaderDropdownMenuButton.tsx
> +}: ComponentPropsWithRef<typeof DropdownMenuButton>) => {
> rest

英語力のなさだった😇 rest よさそう〜!

2024-03-18 23:50 UTC, uknmr commented on src/components/Header/HeaderDropdownMenuButton.tsx
> +  ],
あー、理解しました。extend はできるけど、DropdownMenuButton は `triggerWrapper` しか外に開かれてないからどうしようもないですね🙄
現状のままで gogo🙏

2024-03-19 05:38 UTC, atzzCokeK commented on src/components/Header/HeaderDropdownMenuButton.tsx
> +}: ComponentPropsWithRef<typeof DropdownMenuButton>) => {
@uknmr @AtsushiM ありがとうございます〜！修正しました！ (...props -> ...rest)

2024-03-22 06:53 UTC, uknmr approved these changes
@atzzCokeK 不要な記述があったので消しました! [45d15c8](https://github.com/kufu/smarthr-ui/pull/4454/commits/45d15c8ae5917eaa7b2ecf4433e1a3895127d9ed)

2024-03-22 08:22 UTC, merged