refactor: HeaderをTailwindCSS化
kufu/smarthr-ui pull request #4455
Opened 2024-03-16 03:21 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2024-03-16 04:58 UTC, atzzCokeK commented
UI Tests1件変更入っていますが、今の状態のほうが正だと感じたので確認お願いしたいです🙇

2024-03-19 13:01 UTC, uknmr requested changes

2024-03-19 13:01 UTC, uknmr commented on src/smarthr-ui-preset.ts
> +      brand: defaultColor.BRAND,
記述が揃ってなくて申し訳ないけど、colors に定義してあるので参照するとよさそう。

```suggestion
      brand: theme('colors.brand'),
```

2024-03-22 10:36 UTC, uknmr approved these changes
LGTM~

2024-03-22 10:37 UTC, merged