refactor: FloatAreaをTailwindCSS化
kufu/smarthr-ui pull request #4456
Opened 2024-03-16 04:52 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2024-03-16 05:10 UTC, atzzCokeK commented on src/components/FloatArea/FloatArea.tsx
> +    base: 'smarthr-ui-FloatArea',
ここwrapperですが、baseにしておくことで、variants内での分岐を書かなくて済むのでbaseにしていますが実装微妙そうだったら、wrapperにしてvariants内で分岐書きます。

```typescript
top: {0 : {wrapper: "shr-top-0"} ...
```
みたいなかんじですかね？:eyes:

2024-03-18 00:30 UTC, uknmr requested changes

2024-03-19 00:00 UTC, uknmr commented on src/components/FloatArea/FloatArea.tsx
> +          className: `${className} ${zIndex ? `shr-z-[${zIndex}]` : 'shr-z-[500]'}`,
複雑というかそもそも `shr-z-[${zIndex}]` では tailwindcss はクラスを生成してくれないかも。
https://tailwindcss.com/docs/content-configuration#dynamic-class-names

> 2箇所にz-index関連の記述をするのに若干抵抗ある

初期値（class）と利用者が指定する値（style）で役割が違うので、個人的には気になりません。

2024-03-19 05:47 UTC, atzzCokeK commented on src/components/FloatArea/FloatArea.tsx
> +          className: `${className} ${zIndex ? `shr-z-[${zIndex}]` : 'shr-z-[500]'}`,
@uknmr 確かに、shr-z-[${zIndex}]だめでした...失礼しました！:bow:

>初期値（class）と利用者が指定する値（style）で役割が違う
ありがとうございます！

2024-03-22 08:42 UTC, uknmr approved these changes
LGTM~

2024-03-22 08:59 UTC, merged