feat: ~ というテキストがスクリーンリーダーで正しく読み上げられる対応をしたコンポーネント、Tildeを追加
kufu/smarthr-ui pull request #4502
Opened 2024-03-26 05:26 UTC by AtsushiM

## Related URL

## Overview

## What I did

## Capture

2024-03-27 23:50 UTC, uknmr requested changes
チルダは記号の名前であり適切な意味を持たないため、期間の記号であることを示す名前を付けたいです。

例）
- RangeSymbol
- RangeImage
- RangeSeparator

2024-03-27 23:52 UTC, uknmr commented on src/components/Text/Tilde.tsx
> +      <span aria-hidden="true">〜</span>
`〜` 部分も decorator で差し替えたい。

2024-03-27 23:53 UTC, AtsushiM commented on src/components/Text/Tilde.tsx
> +      <span aria-hidden="true">〜</span>
あ、結局そっちもやることにしたんすね
了解です。

2024-03-27 23:54 UTC, AtsushiM commented
外でも使われていますし RangeSeparator がいいすかね？

2024-03-27 23:56 UTC, uknmr commented
`RangeSeparator` いいと思います!

2024-03-28 00:22 UTC, AtsushiM commented
@uknmr 一通り対応しました 🙏

2024-03-28 02:21 UTC, uknmr commented on src/components/PageCounter/PageCounter.tsx
> +  )
既存のまま `–` ダーシをデフォルトにしたいです。

```suggestion
  const rangeSeparatorDecorators = useMemo(
    () => ({
      text: () => executeDecorator(RANGE_SEPARATOR_TEXT, decorators?.rangeSeparator),
      visuallyHiddenText: () => executeDecorator(RANGE_SEPARATOR_VISUALLY_HIDDEN_TEXT, decorators?.rangeSeparator),
    }),
    [decorators?.rangeSeparator],
  )
```

2024-03-28 03:07 UTC, AtsushiM commented on src/components/PageCounter/PageCounter.tsx
> +  )
↑だと記号がvisuallyHiddenにも設定されてしまうので駄目っぽいですね。
別途対応します

2024-03-28 04:49 UTC, uknmr approved these changes
LGTM~
PageCounter における decorator の I/F が変わるから Breaking change か? と思ったけど、プロダクト側で使われてなかったので、どちらでもよさそう。

2024-03-28 04:57 UTC, merged