fix: TextareaコンポーネントのmaxLength属性をlimitLength属性に変更
kufu/smarthr-ui pull request #4607
Opened 2024-04-25 22:54 UTC by AtsushiM

## Related URL

## Overview

## What I did

## Capture

2024-04-26 01:11 UTC, s-sasaki-0529 approved these changes
👍 Storybook 上で動作が変わっていないことが確認できました！

2024-05-02 03:28 UTC, oti approved these changes
LGTM!

2024-05-06 23:59 UTC, oti requested changes
2点コメントしました！

2024-05-06 23:59 UTC, oti commented on packages/smarthr-ui/src/components/Textarea/Textarea.tsx
> +    const actuaMaxLettersId = maxLetters ? maxLettersId : undefined
```suggestion
    const actualMaxLettersId = maxLetters ? maxLettersId : undefined
```

typoっぽい！

2024-05-06 23:59 UTC, oti commented on packages/smarthr-ui/src/components/Textarea/Textarea.tsx
> +        aria-labelledby={actuaMaxLettersId}
```suggestion
        aria-describedby={actualMaxLettersId}
```
「あとN文字」はラベルではないと思うので、 `aria-describedby` のほうが良さそうに思いました。

2024-05-06 23:59 UTC, oti commented on packages/smarthr-ui/src/components/Textarea/Textarea.tsx
> +        <span className={counterStyle} id={actuaMaxLettersId}>
```suggestion
        <span className={counterStyle} id={actualMaxLettersId}>
```

2024-05-07 00:19 UTC, oti approved these changes
LGTM!(2)

2024-05-08 07:21 UTC, Qs-F approved these changes
maxLength → maxLettersに関してはLGTMです！

2024-05-08 08:02 UTC, uknmr requested changes
「あと n/n 文字」という表記は意匠も含めて調整した方がよさそうなので、マージされないように request change 入れておきます。

2024-05-09 03:31 UTC, uknmr approved these changes

2024-05-09 03:37 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Textarea/Textarea.tsx
> +        </span>
📝 スクリーンリーダーに読み込ませる場合、/ が正しく読めない場合があるかも？

2024-05-09 03:57 UTC, merged