feat: FormDialogのonSubmitの第二引数にFormEventを渡すように修正
kufu/smarthr-ui pull request #4610
Opened 2024-04-26 01:14 UTC by AtsushiM

## Related URL

## Overview

## What I did

## Capture

2024-04-26 07:29 UTC, Qs-F approved these changes
LGTM

2024-04-26 07:49 UTC, uknmr requested changes

2024-04-26 07:49 UTC, uknmr commented on src/components/Dialog/Dialog.stories.tsx
> +          console.log('event', e)
`console.log` 残ってます

2024-04-30 01:25 UTC, uknmr commented on src/components/Dialog/Dialog.stories.tsx
> +          console.log('event', e)
story だからいいか

2024-04-30 01:25 UTC, uknmr approved these changes

2024-04-30 01:25 UTC, merged