feat: SearchInput コンポーネントに onClickClear オプションを追加する
kufu/smarthr-ui pull request #4635
Opened 2024-05-07 10:55 UTC by s-sasaki-0529

## Related URL

https://smarthr.atlassian.net/browse/SHRUI-957

## Overview

`SearchInput` コンポーネントに `onClickClear` オプションを渡すことで、入力欄の末尾に☓ボタンが表示され、押下時のコールバック関数を指定できるようにします。

## What I did

## Capture

バツボタンを表示
![CleanShot 2024-05-07 at 19 55 03](https://github.com/kufu/smarthr-ui/assets/16274215/4bfe12b7-e277-4c3e-b701-158dc82b6171)
![CleanShot 2024-05-07 at 19 55 26](https://github.com/kufu/smarthr-ui/assets/16274215/6be92c1f-d463-4b16-9223-f441e8e5e400)

バツボタンを表示(ダークモード)
![CleanShot 2024-05-07 at 19 55 41](https://github.com/kufu/smarthr-ui/assets/16274215/ed7ed736-9fbc-41e7-9c5b-0cc4f861caa2)
![CleanShot 2024-05-07 at 19 55 51](https://github.com/kufu/smarthr-ui/assets/16274215/ba730e9c-44dc-460d-a3c2-97a9faf41df5)

2024-05-07 11:01 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +  onClickClear?: (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void
バツボタン表示用の props を追加。
一応 decorators 側も拡張して、解除ボタンの代替テキストを改変できるようにもします。

2024-05-07 11:01 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +})
スタイルはほぼほぼ `SingleCombobox` のそれを拝借

2024-05-07 11:01 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +          }
閉じるボタンを追加。
こちらもほぼほぼ SingleCombobox の実装を拝借。

2024-05-07 11:46 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.stories.tsx
> +    const [value, setValue] = React.useState('value')
検索キーワードの解除をシミュレートするために、非制御コンポーネントになってた Storybook 側を制御コンポーネントに書き換えています。

2024-05-08 07:50 UTC, uknmr requested changes
いいですね!
SingleComboBox と同じ意匠で問題ないと思いますが、2点気になりをコメントしました。

2024-05-08 07:50 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +      'shr-me-0.5 shr-cursor-pointer',
wrapper に余白が存在するので不要そうでした!

```suggestion
      'shr-cursor-pointer',
```

2024-05-08 07:50 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +      <label>
SearchInput は label で囲っているため、`label > input + button` という構造になってしまい HTML として invalid になります。`label[for]` を使うなど明示的な指定が必要かもしれません。

2024-05-08 09:51 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +      <label>
@uknmr こちら HTML としては invalid だけど、以下みたいに for 属性を付与して入力要素に紐づいてることを明示すればセーフという話ですか？

```diff
+    const defaultInptuId = useId()
+    const inputId = props.id || defaultInptuId
+
     return (
-      <label>
+      <label htmlFor={inputId}>
         <InputWithTooltip
           {...props}
+          id={inputId}
           ref={ref}
           prefix={<FaMagnifyingGlassIcon alt={iconAlt} color="TEXT_GREY" />}
           suffix={
```

それとも invalid  な HTML が駄目だから、この場合は `<label>` と `<inputWithTooltip>` を親子じゃなくて兄弟にしなきゃならないとかですか…？

2024-05-08 11:12 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +      <label>
label のインタラクティブな子要素のうち先頭のものと紐づけられる仕様があるので `label > input` の状態で `for / id` で紐づける意味は特にないです。
後者の「兄弟にしなきゃならない」の意図でコメントしました!

こんな感じですかねぇ。

```tsx
<label htmlFor={inputId}>{iconAlt}</label> // 何らかの方法で visually hidden
<InputWithTooltip id={inputId} />
```

2024-05-09 10:32 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +        </label>
@uknmr 
https://github.com/kufu/smarthr-ui/pull/4635#discussion_r1593550788 の続き。

素直に VisuallyHiddenText 使って label と input を兄弟関係にするのだとどうですかね。
見た目は変わらず、HTML valid だし、input 要素には名前が入るしで良い気はします。

ラッパーに `<div>` を使ってるのがイケてない感じましますが、フラグメントにしちゃうと `<Stack>` や `<Cluser>` 内で使用している場合にスタイル崩れに繋がるので避けたんですがどうでしょ。

2024-05-10 00:52 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +        </label>
兄弟にするので良いと思います!
ラッパーを div にした時の懸念は記述コンテンツカテゴリーなどの div の内包を許容しない場合に、HTML が invalid になることかと思いますが、SearchInput は性質上 div でも問題なさそうだと思いました!

2024-05-10 00:52 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
>            prefix={<FaMagnifyingGlassIcon alt={iconAlt} color="TEXT_GREY" />}
`iconAlt` のラベルを消しても良さそうです。

2024-05-10 08:33 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +        </label>
コメント忘れてたんですが、`<VisuallyHiddenText as="label" htmlFor={inputId}>{iconAlt}</VisuallyHiddenText>` と書けると綺麗そうだな、と思いました（現状の型は `span` を使ってるので無理そう）。

2024-05-15 04:54 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +        </label>
@uknmr こちら現状の修正内容でGOGOって認識であってますか？ (VisuallyHiddenText 側の課題はあるものの)
requested changes がついたままだったので、まだやりのこしがあるのか気になりました。

2024-05-15 12:11 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +      <div>
そういえばこの場合は `<div>` じゃなくて　`<search>` が使える機運なのではと思いましたが、この要素というよりは検索ボタンも含めた外側のフォーム全体に role=search が付くべきなんですかね。

2024-05-15 12:14 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +      <div>
割とどのプロダクトも同じように `<SearchInput>`  と検索ボタンに組み合わせで使ってるから、そこまでセットで smarthr-ui で提供しても良い気がしてきた(感想)

2024-05-27 23:13 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Input/SearchInput/SearchInput.tsx
> +      <div>
細かいところですがSearchInputでInputを想像するので、 div より span のほうが利用者のメンタルモデルに近いかも。

2024-05-28 01:47 UTC, uknmr approved these changes
実装と Chromatic、Story での動作確認をしました。
LGTM!!

2024-05-28 01:47 UTC, merged