Buttonをloading状態に切り替えるとフォーカスが外れてしまう問題の修正
kufu/smarthr-ui pull request #4684
Opened 2024-05-30 12:17 UTC by misako0927

## Related URL

https://smarthr.atlassian.net/browse/SHRUI-952

## Overview

aria-disabledを使用することでフォーカスが外れないようにした

## What I did

* aria-disabledを使用した
* aria-disabledの際に非活性スタイルが当たるようにした
* aria-disabledの際にclickしても反応しないようにした

## Capture

2024-06-14 02:41 UTC, s-sasaki-0529 approved these changes
👍 変更内容を確認し、手元でフォーカス移動やホバー・クリック時の挙動、ハイコントラストモードでの見え方あたりを確認できました！

2024-06-25 02:05 UTC, uknmr requested changes

2024-06-25 02:05 UTC, uknmr commented on packages/smarthr-ui/src/components/Button/ButtonWrapper.tsx
> +        'aria-disabled:forced-colors:shr-text-[GrayText]',
いずれの variants でも共通のスタイルのため、compoundSlots に書く必要はなさそうに見えました。意図的でなければ default に移動しても良さそうです。
また、なぜ必要なスタイルなのかコードからは読み取りづらいので、コメントの追記をお願いします!（UA の disabled ではないから強制カラーモードの時に色が変わらない?

2024-06-25 07:52 UTC, uknmr commented on packages/smarthr-ui/src/components/Button/ButtonWrapper.tsx
> +        'aria-disabled:forced-colors:shr-text-[GrayText]',
提案修正 https://github.com/kufu/smarthr-ui/pull/4744

2024-07-01 02:23 UTC, uknmr approved these changes

2024-07-01 02:24 UTC, merged