feat: ErrorScreen の `footer` props を deprecated にする
kufu/smarthr-ui pull request #4714
Opened 2024-06-11 09:50 UTC by oti

## Related URL

- https://smarthr.atlassian.net/browse/SHRUI-987

## Overview

- 使われていない `footer` props を非推奨にしたい
- Storybook の `full` の意味がわかりにくい（おそらく props 全部指定？）ので `all` に変更したい
- `without children` / `with footer` の Storybook をトルツメしたい

## What I did

- 使われていない `footer` props を非推奨にした
- Storybook の `full` の意味がわかりにくい（おそらく props 全部指定？）ので `all` に変更した
- `without children` / `with footer` の Storybook をトルツメした
- `all` の内容が実装例に寄りすぎていたので無味無臭なものにした

## Capture

![スクリーンショット_2024-06-11_18_48_17](https://github.com/kufu/smarthr-ui/assets/710216/db09ce18-0ea7-4ae8-bd21-71e7bf05f80e)

2024-06-11 09:58 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/ErrorScreen/ErrorScreen.tsx
> +  /** @deprecated フッター指定は非推奨です。リンクの表示が必要な場合は links を使用してください。 */
使われていないのなら非推奨化じゃなくて即削除しちゃっても良いかなと思いましたがどうでしょう？
逆に、残すのであれば非推奨であろうと Storybook で確認できてほしい気がしました。

2024-06-11 09:59 UTC, s-sasaki-0529 approved these changes
コメントは入れましたが、非推奨化するってチケットは満たせているので Approve!

2024-06-12 04:36 UTC, uknmr requested changes
使ってないのであれば deprecated 挟まず、消しちゃって良さそう!

2024-06-13 11:41 UTC, oti commented
@s-sasaki-0529 @uknmr `footer` props 削除しました！　確認お願いいたします！

2024-06-13 12:26 UTC, s-sasaki-0529 approved these changes
👍 PR 本文にまだ `非推奨` が残ってるのでそこも修正して頂けると！

2024-06-13 12:50 UTC, uknmr approved these changes
PR 本文の「非推奨にしたい」を「消したい」に変えました。
`feat:` → `feat!:` に変えました。

2024-06-14 05:02 UTC, merged