feat: Loaderを200ms後に初期表示する
kufu/smarthr-ui pull request #4723
Opened 2024-06-14 14:32 UTC by atzzCokeK

## Related URL

## Overview

## What I did

## Capture

2024-07-02 02:54 UTC, uknmr commented on packages/smarthr-ui/src/components/Loader/Loader.tsx
> +      'shr-transition-opacity shr-ease-[unset] shr-duration-0 shr-delay-1000 shr-opacity-0 shr-animate-[loader-fade-in_auto_ease_200ms_forwards]',
`duration-0` や `delay-1000` は必要? 必要な記述をしっかり絞りたい。

2024-07-18 00:01 UTC, uknmr requested changes
ローカルで確認しつつ提案 PR を作ってみました! https://github.com/kufu/smarthr-ui/pull/4787

2024-07-18 01:50 UTC, uknmr approved these changes
自分で提案 PR マージしてしまったので確認お願いします! @atzzCokeK

2024-07-18 01:57 UTC, atzzCokeK commented
@uknmr 確認しました。諸々良くしていただいてありがとうございます🙇

2024-07-18 02:08 UTC, merged