fix: ソートできる場合はクリッカブルなので Th に `cursor: pointer` を当てた
kufu/smarthr-ui pull request #4773
Opened 2024-07-11 08:15 UTC by hiroki0525

## Related URL

## Overview

タイトルの通り

## What I did

## Capture

### before

https://github.com/kufu/smarthr-ui/assets/40714517/7f361ae4-1091-48d3-8554-91563ab0811f

### after

https://github.com/kufu/smarthr-ui/assets/40714517/54b72a14-7ac6-4120-ba88-11114347e0c9

2024-07-11 09:06 UTC, uknmr requested changes
[UnstyeldButton](https://github.com/kufu/smarthr-ui/blob/c1c9c66cc6e4ec23c1405fa4c8f101c8f46d14cf/packages/smarthr-ui/src/components/Button/UnstyledButton.tsx#L6) の cursor リセットを消してしまうとよさそうです。
また [tailwind-variants](https://www.tailwind-variants.org/) を使ってるため、スタイルを当てる場合はそっちに寄せたい。

2024-07-16 02:23 UTC, hiroki0525 commented on packages/smarthr-ui/src/components/Table/Th.tsx
> -  const sortButtonStyle = useMemo(() => sortButton({ align, className }), [align, className])
`className`は使われてなかったので削除しました

2024-07-16 02:45 UTC, hiroki0525 commented
>[UnstyeldButton](https://github.com/kufu/smarthr-ui/blob/c1c9c66cc6e4ec23c1405fa4c8f101c8f46d14cf/packages/smarthr-ui/src/components/Button/UnstyledButton.tsx#L6) の cursor リセットを消してしまうとよさそうです。

結論から言うと、 `Th` の方で `UnstyeldButton` のクラスを上書くのがベストかもです。
現状 [`UnstyeldButton` には `cursor: auto` があたっている](https://github.com/kufu/smarthr-ui/blob/55ee033d9e2d2b22c30a6dc17bc661f532c6a96c/packages/smarthr-ui/src/components/Button/UnstyledButton.tsx#L6)のですが、これを削除してもユーザーエージェントのスタイル `cursor: default` があたって、相変わらず `Th` はポインタにならなかったですね...
かといって、 `UnstyeldButton` に `shr-cursor-pointer` のクラスを当てると、例えばボタンが `disabled` な状態の時もポインタになりますし...（よしなに制御できると思いますけど、ちょっとそこまでするかと言われると微妙です...）
ので、`UnstyeldButton` の利用側 `Th` の方で `shr-cursor-pointer` を指定してクラス上書きするのがよさそうかなと

2024-07-16 05:25 UTC, uknmr approved these changes
LGTM~
（UnstyledButton の cursor を pointer にするのは影響も広いし別で検討しても良いと思いました!）

2024-07-16 05:26 UTC, merged