fix: Tooltipのaria属性の設定方法を調整
kufu/smarthr-ui pull request #4788
Opened 2024-07-18 04:20 UTC by AtsushiM

## Related URL

## Overview

## What I did

## Capture

2024-07-18 06:04 UTC, neet approved these changes
（これでいいのかはさておき）この変更自体は問題ないと思ったのでapproveします

2024-07-19 01:48 UTC, uknmr requested changes

2024-07-19 01:48 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/InputWithTooltip/InputWithTooltip.tsx
> -        ariaDescribedbyTarget="inner"
これを消したことで SearchInput の input と Tooltip の紐づきが消えてそうでした。

2024-07-19 02:11 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Input/InputWithTooltip/InputWithTooltip.tsx
> -        ariaDescribedbyTarget="inner"
@uknmr そもそもtooltip自体のroleがgenericのままで、設定されていないため、設定があるだけで正しく紐づいていない状態です。
(VoiceOverなどはaria-describedby自体がついている要素がインタラクティブな要素である必要があります)
なので↑に関しては問題なさそうな気がしています

2024-07-19 04:12 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Input/InputWithTooltip/InputWithTooltip.tsx
> -        ariaDescribedbyTarget="inner"
inputからメッセージに対して参照していたので↑は間違えていた。
もともとの紐づける処理を再実装

2024-07-19 06:41 UTC, uknmr approved these changes
LGTM!
Tooltip の I/F は変わっていないため BREAKING CHANG の必要なさそうに思いました!（一旦変えておきます。

2024-07-19 07:16 UTC, merged