fix: Tooltip メッセージが機械側に過足提供していたので修正
kufu/smarthr-ui pull request #4827
Opened 2024-08-06 03:30 UTC by uknmr

## Related URL

## Overview

表示されていない Tooltip メッセージも DOM 上に表示されていたので、Tooltip が表示される時に絞りました。

## What I did

## Capture

2024-08-06 03:34 UTC, Qs-F approved these changes

2024-08-07 12:10 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
![ask](https://img.shields.io/badge/review-ask-blue.svg)

不可視要素で、さらにアクセシビリティツリー上も表示させないなら、そもそも要素が不要になるのでは？

```suggestion
      { isVisible && (<VisuallyHiddenText id={messageId}>
        {hiddenText}
      </VisuallyHiddenText>
```

と思ったんですがこれだと意図と違うんでしょうか…？

2024-08-07 12:50 UTC, uknmr commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
テストのために常に HTML 上に表示させたい旨の改修があったので残しています! https://github.com/kufu/smarthr-ui/pull/4788

2024-08-07 21:01 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
あーそうか！そこに立ち返るんですね！

正直、不可視で支援技術にも提供しないものがDOM上に存在していることをテストして何の意味があるんだろうというお気持ちはまだ残ってますが…。

2024-08-07 21:01 UTC, s-sasaki-0529 approved these changes

2024-08-08 02:07 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
↑のもやりはとりあえず解消したので Approve です！

2024-08-08 02:23 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
@uknmr @s-sasaki-0529 これ再レンダリングコスト的にはtooltipをaria-hiddenするほうがいいのでは？感があるんですがどうですかね？

2024-08-08 02:23 UTC, AtsushiM requested changes

2024-08-08 02:23 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
@uknmr @s-sasaki-0529 これ再レンダリングコスト的にはtooltipをaria-hiddenするほうがいいのでは？感があるんですがどうですかね？

2024-08-08 02:28 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
再レンダリングコストで言うとそうですね。
カーソルが出たり入ったりしたときに再描画する要素が丸ごとひとつ増えることになっちゃいます。

Tooltip 側を aria-hidden にすることで支援技術的にはホバーの概念関係なく常に情報受け取れるでも良さそう。

2024-08-08 02:48 UTC, uknmr commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
目に見えない情報が機械にだけ見えてしまう、のは何らかの達成基準の過不足に該当すると思うので（確認中）、tooltip の情報であれば hover した時に表出させるのが妥当に感じます。

2024-08-08 03:02 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
むずいなぁ〜
smarthr-uiのtooltipの使い方的にインタラクティブではない要素に対してもtooltipが使われている現状、tooltipとして扱う必要性がどれくらいあるか、が観点なのかなぁ...
個人的にはtooltipとして扱うかどうかはぶっちゃけどうでも良くて、伝えたい情報がちゃんと伝えられていればいいのかな、と思っています

2024-08-08 03:16 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Tooltip/Tooltip.tsx
> +      </VisuallyHiddenText>
📝 
testing-libraryなどでボタンのラベルにtooltipの内容が含まれてしまう問題を把握。
どうあるべきか？は別途話すことにして一旦この修正は:+1:で良さそう

2024-08-08 03:16 UTC, AtsushiM approved these changes

2024-08-08 04:47 UTC, merged