feat!: useId の独自実装を削除し、React 18 未満のサポートを終了する
kufu/smarthr-ui pull request #4920
Opened 2024-09-13 12:00 UTC by s-sasaki-0529

## 関連URL

## 概要

## 変更内容

## 確認方法

2024-09-13 12:10 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/index.ts
> -export { SequencePrefixIdProvider } from './hooks/useId'
こちらもリポジトリ内及び社内では一切使用されていなかったのであわせて削除してます。

2024-09-13 12:13 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/hooks/useId.tsx
> +  return React.useId()
ここ、 `if (defaultId)` 分岐の下に Hooks が登場するので、Hooks の制約違反で警告が出てしまうので無視してます。

修正前 (`return ('useId' in React ? React.useId : useId_OLD)()`) は動的にコードを組み立ててた都合、さすがの ESLint も検知できなかったようです。

コンポーネント内で `defaultId` を渡すか渡さないかが描画ごとに異なる場合におかしな挙動になる可能性があるなぁと感じますが、これまで異常がなかったので大丈夫かなと思ってます。

2024-09-13 12:14 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/hooks/useId.tsx
> +  return React.useId()
あるいはこうすることで、回避するほうが安全かも…？

```ts
export const useId = (defaultId?: string): string => {
  const id = useId()
  return defaultId || id
}
```

2024-09-17 01:04 UTC, s-sasaki-0529 commented on packages/smarthr-ui/package.json
> +    "react-dom": "^18.0.0",
事実上、React 17 以下で使えないコンポーネントが生まれることにあるのでここも変えちゃってよいですよね。
のでこっちのほうがインパクト強いという意味で、PRタイトルに含めてます。

2024-09-17 02:48 UTC, atzzCokeK commented on packages/smarthr-ui/src/hooks/useId.tsx
> +  return React.useId()
@s-sasaki-0529 上記でいただいているサンプルコードのほうが良いと思いました！

2024-09-17 02:49 UTC, atzzCokeK reviewed
提案いただいているhooks部分だけは修正したほうが良いとおもいました〜！

2024-09-17 02:52 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/hooks/useId.tsx
> +  return React.useId()
厳密には挙動が変わることになるからためらってたんですが、少なくとも悪化することは無さそうなのでそうしちゃいます！

2024-09-17 03:03 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/hooks/useId.tsx
> +  return defaultId || id
https://github.com/kufu/smarthr-ui/pull/4920#discussion_r1758756295
この辺のやりとりもあって実装ちょっと調整してます。

2024-09-17 03:05 UTC, atzzCokeK approved these changes
自分はgogoに見えました。

2024-09-17 03:20 UTC, Qs-F approved these changes
シュッとしてて良さそうでした！

2024-09-17 03:46 UTC, uknmr commented on packages/smarthr-ui/src/hooks/useId.tsx
> +  return defaultId || id
`defaultId` を渡す機構は必要なのか気になりました。

2024-09-17 03:50 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/hooks/useId.tsx
> +  return defaultId || id
プロダクト側からIDを明示したい場合にそれを使用して、指定がなければランダム値を使うみたいな用途っぽいですね。

`useId` がその機構を持たずに、コンポーネント側に分岐を書けば良いという説はあるし、そのほうが健全な気もします。

2024-09-17 03:52 UTC, uknmr requested changes
kufu 内を調べてみましたが、`useId(someId)` の形で使っているのは、smarthr-ui のみ（Checkbox、RadioButton、Switch）でいずれも `someId || useId()` と同等の使い方でした。
`useId()` に defaultId を渡した場合に、存在すれば defaultId が返ってくるのは `useId` の責務ではないと考えられるので、消しても良いと思います。
https://github.com/search?q=org%3Akufu+useId&type=code

2024-09-17 03:58 UTC, s-sasaki-0529 commented
@uknmr 

> useId() に defaultId を渡した場合に、存在すれば defaultId が返ってくるのは useId の責務ではないと考えられるので、消しても良いと思います。

仰るとおりなのでやっていきなんですが、PR は分けても良いですか…？

React 17 で使えなくなるのはユーザー影響ありありですが、内部での id の決定方法はユーザー影響を出さないリファクタになるし、検証観点も異なってくるので切り分けて扱いたいです！

2024-09-17 05:52 UTC, uknmr approved these changes
@s-sasaki-0529 分けるで 👌 です!

2024-09-17 05:54 UTC, s-sasaki-0529 commented
レビューありがとうございました！
このあとちょっと時間取れそうなので続けて次のPR出せるようトライしますが、とりあえずここまでマージしちゃいます！

2024-09-17 05:54 UTC, merged