fix: RadioButtonPanel内のradio buttonがフォーカス時にインジケーターが表示されない
kufu/smarthr-ui pull request #4969
Opened 2024-10-01 10:08 UTC by daiHash

## 関連URL

https://smarthr.atlassian.net/browse/SHRUI-1070

## 概要

- RadioButtonPanel内のradio buttonをフォーカスしたときにフォーカスインジケーターが表示されてなくて、視覚的にフォーカスしたことが分からないため、フォーカスインジケーターが表示されるように修正
- アクセシビリティ簡易チェックのNG対応

## 変更内容

- radio buttonがフォーカスされる時にカスタムradio buttonの代替要素(span)のbox-shadowをnone(透明化)にされていましたのでフォーカスインジケーターが表示されていませんでしたので、そちらのスタイルがあたらないようにclassnameを削除しました
- `[&_.smarthr-ui-RadioButton-radioButton:focus-visible_+_span]:shr-shadow-none`
    - RadioButtonPanelのもともとあったスタイルのため何かしらの理由があるかと思いますですが、いろいろ検証してみましたが、現状の見た目または強制カラーモード時でも特に影響なさそうのようでしたので削除して対応してみましたが、こちら問題ないのでしょうか？

見た目にも影響なさそう

https://github.com/user-attachments/assets/82ae4c9c-6171-4608-b1e3-1f0d4f0bd71f

強制カラーモード時はカスタムradio buttonの代替要素(span)はdisplay noneになるのと、box-shadowのスタイルも無効にされるので影響なさそう。
inputがそのまま利用されるので現状でも強制カラーモード時ではフォーカスインジケーターが表示されてます

https://github.com/user-attachments/assets/79e9b938-e5ad-49e8-9078-3ecfef98f16f

## 確認方法

RadioButtonPanel内のradio buttonをキーボード操作移動してもフォーカスインジケーターが表示されない

https://story.smarthr-ui.dev/?path=/docs/forms%EF%BC%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%EF%BC%89-radiobuttonpanel--docs

https://github.com/user-attachments/assets/932743bb-bcb8-453f-bc1c-3011cdcf9694

2024-10-01 11:23 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/RadioButtonPanel/RadioButtonPanel.tsx
> -    '[&_.smarthr-ui-RadioButton-radioButton:focus-visible_+_span]:shr-shadow-none',
なんか理由あったのかぁ。あえて消す理由がわからないけど良さそうに見える。

2024-10-01 11:23 UTC, s-sasaki-0529 approved these changes

2024-10-01 11:24 UTC, s-sasaki-0529 reviewed
あれ、CI動かすのに何らかのグループに所属するとか必要ですっけ…?
@kufu/group-dev-smarthr-ui-reviewers

2024-10-02 12:55 UTC, uknmr requested changes
既知の問題で、Storybook 上でのみ発生している不具合な認識です。
試しに sandbox 上で確認したら問題なくフォーカスリングが表示されていました。 
![image](https://github.com/user-attachments/assets/823bbb4f-e8d3-45a7-b478-a11911c3ad12)

2024-10-03 03:19 UTC, closed without merging

2024-10-03 03:21 UTC, daiHash commented
@uknmr 
ご確認ありがとうございます

> Storybook 上でのみ発生している不具合

過去にフォーカスインジケーターについてありましたのですね。。。こちらは不要ですね
https://github.com/kufu/smarthr-ui/pull/4689

> 試しに sandbox 上で確認したら問題なくフォーカスリングが表示された

sandboxがあるのですね、確認ありがとうございます
ああっ。。すみません、Storybookのみで検証してしまっていました。🙇‍♂️