chore: NotificationBar の Story を整理
kufu/smarthr-ui pull request #4996
Opened 2024-10-09 23:56 UTC by s-sasaki-0529

## 関連URL

https://smarthr.atlassian.net/browse/SHRUI-1113

## 概要

#4949 の方針に沿って、Badge コンポーネントの Story を見直しました。

## 変更内容

- NotificationBar の Story を見直し

## 確認方法

Storybook や Chromatic で確認してください。

2024-10-09 23:56 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.pict.txt
> +IF [base] = "none" THEN [layer] = "undefined";
animation はVRTだと無意味なので一律 false にしてます。

2024-10-09 23:57 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/VRTNotificationBar.stories.tsx
> +*/
この量になるともう pict と AI を信じることしか出来ない

2024-10-10 00:01 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +}
イベントハンドラの有無で閉じるボタンが出現するので、これも対象にしてます。

2024-10-10 05:10 UTC, AtsushiM approved these changes
👍

2024-10-10 23:23 UTC, uknmr requested changes
見通しよくなりますね! いい感じ。

2024-10-10 23:23 UTC, uknmr commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +export const _onCloseHandlers = {
Messages と On Close Handlers が Story として表示されてしまってるのが気になります。
Story 用のデータとして別ファイルに出す検討をしてもいいかもしれません。
<img width="327" alt="image" src="https://github.com/user-attachments/assets/b2441608-8d63-4811-98d2-650c7dd695fa">

2024-10-10 23:23 UTC, uknmr commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +    <div className="shr-bg-base-grey shr-min-h-[50vh] shr-p-1">
可能であれば parameters か何らかの Storybook の機能で背景色を切り替えられると、より綺麗になると思いました。

2024-10-10 23:23 UTC, uknmr commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +    animate: true,
shoud: Story のデフォルト値はコンポーネントのデフォルト値に寄せたいと思いました。

```suggestion
    animate: false,
```

2024-10-10 23:23 UTC, uknmr commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +    <div className="shr-bg-base-grey shr-min-h-[50vh] shr-p-1">
imo: parameters でやらないにしても、スタイリングは共通化したい気持ちになりました（発生しにくいし、コピペで作りそうだから温度感は低いです

2024-10-10 23:23 UTC, uknmr commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +  title: 'STATES（状態）/NotificationBar',
どっちでもいいんですが大文字だと叫んでるみたいになっちゃうので（Storybook 上が大文字なのは Storybook のスタイルが uppercase してたはず

```suggestion
  title: 'States（状態）/NotificationBar',
```

2024-10-11 00:17 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +export const _onCloseHandlers = {
きえぇ…。`_` つければ除外されると思い込んでました。
別ファイルに出すのも良さそうですが、流石にストーリーじゃないことを示す手段が CSF にある気がしてるのでそちらも調べてみます！

2024-10-11 00:19 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +    <div className="shr-bg-base-grey shr-min-h-[50vh] shr-p-1">
あー、[addon backgrounds](https://storybook.js.org/addons/@storybook/addon-backgrounds) が入ってるので、そっちでやるほうがスマートそうですね。確認します！

2024-10-11 02:51 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +  excludeStories: ['_SampleMessages', '_SampleOnCloseHandlers'],
CSF内で export してもストーリー扱いさせないための設定。
命名規則でもう少しどうにかなってほしい。

2024-10-11 02:52 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +    backgrounds: { default: 'light' },
組み込みのカラーテーマである 'light' を使えば良い感じになりました。
アドオン入れてカスタマイズすれば任意の色にできそうではあります。

2024-10-11 02:53 UTC, s-sasaki-0529 commented
@uknmr ご指摘対応しました！再レビューお願いします！

- [chore: Storyのタイトルをキャメルケースにする](https://github.com/kufu/smarthr-ui/pull/4996/commits/4179a32c9b8915240fc834037b9e4c3c1e9c3d70)
- [chore: CSF内で、Storyにしたくないオブジェクトは exclude する](https://github.com/kufu/smarthr-ui/pull/4996/commits/83d1104e8790a3b57341c970b5acffb861b74c95)
- [chore: animate オプションはコンポーネントのデフォルトに揃える](https://github.com/kufu/smarthr-ui/pull/4996/commits/38f38544c5991fc106a04fbb4d7f297b210287f1)
- [chore: ストーリーの背景色は backgrounds addon 経由で設定する](https://github.com/kufu/smarthr-ui/pull/4996/commits/e27b962301562f657048d119e6db2fe56cd365a3)

2024-10-11 02:55 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +    backgrounds: { default: 'light' },
あ、VRTだと background 反映されないんだ…。
リグレッションテスト用途なら影響しないだろうけど。
https://www.chromatic.com/build?appId=63d0ccabb5d2dd29825524ab&number=8878

2024-10-11 08:04 UTC, uknmr commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +  excludeStories: ['_SampleMessages', '_SampleOnCloseHandlers'],
imo: コンポーネントでもないし private 変数的な `_` だと思うので、camel case でも良さそうだと思ってたんですが、大文字にした意図ってありますか?

2024-10-11 08:04 UTC, uknmr commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +    backgrounds: { default: 'light' },
カスタマイズは別のアドオンが必要なんですね。一旦 light で良さそう!

2024-10-11 08:06 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/NotificationBar/stories/NotificationBar.stories.tsx
> +  excludeStories: ['_SampleMessages', '_SampleOnCloseHandlers'],
意図はないですね。ストーリー名のほうに引きずられてしまったので `sampleMessages` の形式で揃えます!

2024-10-11 08:14 UTC, uknmr commented on packages/smarthr-ui/.storybook/preview.tsx
別の変更混ざったかも!（意図的だったら 🙏

2024-10-11 09:26 UTC, s-sasaki-0529 commented on packages/smarthr-ui/.storybook/preview.tsx
あれ…。これ useTheme を処すやつの差分ですね…。確認します！

2024-10-11 09:27 UTC, s-sasaki-0529 commented on packages/smarthr-ui/.storybook/preview.tsx
master 取り込んだら消えました！

2024-10-15 01:10 UTC, uknmr approved these changes

2024-10-15 01:10 UTC, merged