docs: Heading の Story を整理
kufu/smarthr-ui pull request #5016
Opened 2024-10-16 04:17 UTC by s-sasaki-0529

## 関連URL

- https://smarthr.atlassian.net/browse/SHRUI-1083

## 概要

#4949 の方針に沿って、Dropdown の Story を見直しました。

## 変更内容

- Heading の Story を見直し

## 確認方法

Storybook や Chromatic で確認してください。

2024-10-16 04:21 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Heading/stories/Heading.stories.tsx
> +  name: 'tag',
非推奨化した props の扱いどうしようかなぁと思いましたが、提供している props である以上は扱いに差は設けないことにしました。

2024-10-16 04:22 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Heading/stories/VRTHeading.stories.tsx
> +  // ペアワイズ法は使わずに総当りする
3種類で組み合わせも十分有限なので全網羅

2024-10-17 00:23 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Heading/stories/Heading.stories.tsx
> +  name: 'tag',
fix: ff3ef333822eea8a9cddb893728def819ebe39a4

2024-10-17 00:23 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Heading/stories/Heading.stories.tsx
> +    </Stack>
fix: a9b5938eaaa307c095d75e4074d98e9bbb03faaa

2024-10-17 00:23 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Heading/stories/VRTHeading.stories.tsx
> +                <Heading key={tag} type={type} tag={tag} visuallyHidden={true}>
あ、ないですね 🙏 
フラグメントでくくる前の名残だったので消しときます！

2024-10-17 00:23 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Heading/stories/VRTHeading.stories.tsx
> +          <Stack key={type}>
fix: 2376bcc523fb63ef786681136b371f6d40df4002

2024-10-17 04:51 UTC, uknmr requested changes
subcomponent として PageHeading の対応が漏れてました!（1度目のレビューで気づかず🙏

2024-10-17 06:16 UTC, uknmr commented on packages/smarthr-ui/src/components/Heading/stories/Heading.stories.tsx
> +  component: Heading,
賛否ありそうですが、subcomponents として PageHeading を書いてもよさそう。

```suggestion
  component: Heading,
  subcomponents: { PageHeading },
```

2024-10-17 06:16 UTC, uknmr commented on packages/smarthr-ui/src/components/Heading/stories/PageHeading.stories.tsx
> +    type: 'screenTitle',
（これ書きながら気持ちがぶれてるんですが、）初期値ない方が optional であることが伝わりやすいかも、と思ったりしています（Heading の type も同じ）。

2024-10-17 07:00 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Heading/stories/PageHeading.stories.tsx
> +    type: 'screenTitle',
省略すると Code タブで伝わりにくいかなぁと思ったんですが、試した限り別にそんなことはなさそうだったし、デフォルトでミニマムケースが表示されるのはありがたいので省略しました！

2024-10-17 08:29 UTC, uknmr approved these changes
LGTM~

2024-10-17 08:33 UTC, merged