docs: StackのStoryを見直し
kufu/smarthr-ui pull request #5017
Opened 2024-10-16 05:26 UTC by misako0927

## 関連URL

https://smarthr.atlassian.net/browse/SHRUI-1082

## 概要

https://github.com/kufu/smarthr-ui/pull/4949 の方針に沿って、Stack コンポーネントの Story を見直しました。

## 変更内容

* Stack の Story を見直し
* Stack の VRT 用 Story を pict を利用して書き直し
  * 一部pictを使っていない部分もあるので、その辺りも見ていただきたい
## 確認方法

Storybook や Chromatic で確認してください。

2024-10-16 07:04 UTC, uknmr requested changes

2024-10-16 07:04 UTC, uknmr commented on packages/smarthr-ui/src/components/Layout/stories/VRTStack.stories.tsx
> +  title: 'Layouts（レイアウト）/Stack',
TabBar や Button など、整備済み Story と合わせてほしいです!

```suggestion
  title: 'Layouts（レイアウト）/Stack/VRT',
```

2024-10-16 07:04 UTC, uknmr commented on packages/smarthr-ui/src/components/Layout/stories/VRTStack.stories.tsx
> + * gapはボリュームが多いため、1回ずつ出るように別途組み合わせます
imo: CSS の inline も align も CSS の機能を確認している状態になってしまうので、なくても良さそうな気がしています。
gap の Story と同じものが一つあればいいかも。

2024-10-16 07:04 UTC, uknmr commented on packages/smarthr-ui/src/components/Layout/stories/VRTStack.stories.tsx
> +export const VRTStackNarrow: StoryObj = {
幅に依って変わる振る舞いは持っていないので、なくてよさそう。

2024-10-16 07:04 UTC, uknmr commented on packages/smarthr-ui/src/components/Layout/stories/VRTStack.stories.tsx
> +export const VRTStackForcedColors: StoryObj = {
強制カラーモードで変わる振る舞いは持っていないので、なくてよさそう。

2024-10-16 07:04 UTC, uknmr commented on packages/smarthr-ui/src/components/Layout/stories/VRTStack.stories.tsx
> +const Wrapper = styled.div`
tailwlindcss で書きたい

2024-10-17 00:27 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/Stack.stories.tsx
構成勘違いしておりました🙏直しました！
https://github.com/kufu/smarthr-ui/pull/5017/commits/8bb759246d6f7e226ea8798339478228c510a1e1

2024-10-17 00:27 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/Stack.stories.tsx
> +}
直しました！
https://github.com/kufu/smarthr-ui/pull/5017/commits/f5443a4203b5a8b6e24c2f533663051ab8ac399c

2024-10-17 00:27 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/Stack.stories.tsx
> +    withTheming: true,
以下でまとめて直しました！
https://github.com/kufu/smarthr-ui/pull/5017/commits/34b7304e215056c7f0265d19ded0fc19d675c5b2

2024-10-17 00:27 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/Stack.stories.tsx
> +    gap: 'XL',
以下でまとめて直しました！
https://github.com/kufu/smarthr-ui/pull/5017/commits/34b7304e215056c7f0265d19ded0fc19d675c5b2

2024-10-17 00:28 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/Stack.stories.tsx
> +export const Gap: StoryObj<typeof Stack> = {
以下で直しました！
https://github.com/kufu/smarthr-ui/pull/5017/commits/34b7304e215056c7f0265d19ded0fc19d675c5b2

なお、codeを処していないのでmap使わない方がいいかな〜と思い、ベタ書きしております

2024-10-17 00:29 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/VRTStack.stories.tsx
> +  title: 'Layouts（レイアウト）/Stack',
気づいておりませんでした🙇‍♀️失礼しました
https://github.com/kufu/smarthr-ui/pull/5017/commits/a04236ffa0be17060343f7f45f882accafd97c50

2024-10-17 00:30 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/VRTStack.stories.tsx
> + * gapはボリュームが多いため、1回ずつ出るように別途組み合わせます
VRTのストーリーを1つにしました🙇‍♀️
https://github.com/kufu/smarthr-ui/pull/5017/commits/a04236ffa0be17060343f7f45f882accafd97c50

2024-10-17 06:05 UTC, uknmr commented on packages/smarthr-ui/src/components/Layout/stories/Stack.stories.tsx
> +export const Align: StoryObj<typeof Stack> = {
以下のような感じであれば、違いを視覚的に表せないかしら。

```jsx
<Stack>
  {['stretch', 'baseline', 'flex-start', 'flex-end'].map((align) => (
    <Stack {...args} align={align}>
      <ColorBox />
      <ColorBox />
    </Stack>
  )}
</Stack>
```

2024-10-23 00:59 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/stories/Stack.stories.tsx
> +export const Gap: StoryObj<typeof Stack> = {
修正しました🙇‍♀️
https://github.com/kufu/smarthr-ui/pull/5017/commits/178f9feb0b7a855b237155a804164f9ff16beeb8

2024-10-23 00:59 UTC, misako0927 commented on packages/smarthr-ui/src/components/Layout/Stack/stories/VRTStack.stories.tsx
> +  render: (args) => (
修正しました🙇‍♀️
https://github.com/kufu/smarthr-ui/pull/5017/commits/fd825d5d9c927bd30daa42c224ad40f5b6b5ccce

2024-10-23 01:30 UTC, uknmr approved these changes
LGTM~

2024-10-23 01:30 UTC, uknmr commented on packages/smarthr-ui/src/components/Layout/Stack/stories/Stack.stories.tsx
> +export const AlignStory: StoryObj<typeof Stack> = {
わかりやすくてよさそう!

2024-10-23 06:08 UTC, merged