docs: Input と CurrencyInput、SearchInput の Story を見直し
kufu/smarthr-ui pull request #5029
Opened 2024-10-18 05:50 UTC by uknmr

## 関連URL

- https://smarthr.atlassian.net/browse/SHRUI-1086
- https://smarthr.atlassian.net/browse/SHRUI-1124
- https://smarthr.atlassian.net/browse/SHRUI-1144

## 概要

#4949 の方針に沿って Input や CurrencyInput、SearchInput の Story を見直しました。

## 変更内容

- Input と VRT 向け Input の Story を見直し
- CurrencyInput の Story を見直し
  - 中身が Input のため VRT は不要だと判断しました
- SearchInput を VRT 向け SearchInput の Story を見直し

## 確認方法

Storybook や Chromatic で確認してください。

2024-10-18 05:52 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/CurrencyInput/CurrencyInput.tsx
> +type Props = Omit<React.ComponentProps<typeof Input>, 'type' | 'value' | 'defaultValue'> & {
`placeholder` は Input で定義されていたので消しました。

2024-10-18 05:52 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/SearchInput/stories/VRTSearchInput.stories.tsx
> +export const VRTHover: StoryObj<typeof SearchInput> = {
addon-pseudo-states では再現できなさそうだったため play function を利用（focus も同じ

2024-10-18 10:18 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Input/stories/Input.stories.tsx
> +  args: {},
ReactNode を受けると props についてはデフォ値を設定するか、args の型を定義しないと Playground で [Set Object] 押下するとクラッシュしちゃいますね…。

2024-10-18 10:21 UTC, s-sasaki-0529 requested changes
各コンポーネントでPlayground が使えない状態になっちゃってるのでご確認お願いします！

2024-10-18 13:09 UTC, uknmr commented on packages/smarthr-ui/src/components/Input/stories/Input.stories.tsx
> +  args: {},
対応しました! 973bdc66

2024-10-23 06:39 UTC, s-sasaki-0529 approved these changes
👍️ 一通りの Story と VRT 結果を確認できました！

2024-10-23 06:40 UTC, merged