feat: 月選択UI (`MonthPicker`) を追加したい
kufu/smarthr-ui pull request #5030
Opened 2024-10-18 08:31 UTC by zoshigayan

## 関連URL

## 概要

## 変更内容

## 確認方法

2024-10-18 08:43 UTC, Qs-F reviewed
ありがとうございます〜！挙動は良さそうでした！
少し気になったところを書いておきます！

- ~~Pickerだと少し広い名前に感じてしまいました。DateTimePicker とかでまとめてもいいかも~~
- ~~DatePickerもPickerに移動させてもいいかもと思いました！~~
  - 既にSlackで出てた結論でした！上記2つは無視で大丈夫です
- input[type=month] がSafariやFirefoxで対応していないようでただのテキストになってしまう雰囲気を感じたのですが、それは問題なさそうですか？

2024-10-18 08:44 UTC, Qs-F commented
@uknmr 新規コンポーネント追加するときって新しいStorybookの形式にしてもらったほうがいいですかね？(とはいえドキュメントが充実しているわけではないので若干やってもらう心苦しさはありつつ…)

2024-10-18 10:07 UTC, s-sasaki-0529 commented
あとこれも全然運用プロセスに乗せてないんですが、RSCに対応してるかどうかの定義追加もお願いしたいです。
コード見る限りはRSCでいけそうなので、以下に追加してテストが通ればOKです！
https://github.com/kufu/smarthr-ui/blob/b2111231e4524fce9f82ff8fc70180443dc9a4b1/sandbox/next/e2e/rsc.test.ts#L3-L32

2024-10-21 01:59 UTC, zoshigayan commented
@Qs-F https://github.com/kufu/smarthr-ui/pull/5030#pullrequestreview-2377428056

> input[type=month] がSafariやFirefoxで対応していないようでただのテキストになってしまう雰囲気を感じたのですが、それは問題なさそうですか？

あーすみません、ここ確認できてませんでした…！
いちおう [SmartHRの動作環境](https://support.smarthr.jp/ja/help/articles/360035170054/) としているブラウザ (Chrome / Edge / iOS Safari / Android Chrome) が対応していそうなので社内プロダクトとしての利用に限って見れば大丈夫だと思います 💭 
SmartHR UIの対応環境って特に明記されていないと思うので、上記で大丈夫なのかどうか…については皆さんにご意見いただきたいです 🙏

2024-10-21 23:15 UTC, s-sasaki-0529 approved these changes
見ました！RSC検証の対応もありがとうございます！

個人的にはですが

- Storybook のリライト作業はチームミッションとしての取り組みなので、少なくとも期中はコアチームでやりきるで良さそう
- ブラウザサポートも SmartHR の範囲内では扱えてるし、Firefox などでもただのテキストボックスになるだけで辛うじて使えないこともないので良さそう

なお気持ちです。

2024-10-22 01:58 UTC, uknmr commented
Story のリライトはチームミッションとしてコアチームでやる、でいいと思います! @Qs-F

2024-10-23 07:59 UTC, uknmr requested changes

2024-10-23 07:59 UTC, uknmr commented on packages/smarthr-ui/src/components/Picker/style.ts
> +      'smarthr-ui-TimePicker',
MonthPicker にも `smarthr-ui-TimePicker` が付いてしまうので、コンポーネント側で付けるとよさそう。

```suggestion
```

2024-10-23 08:26 UTC, zoshigayan commented on packages/smarthr-ui/src/components/Picker/style.ts
> +      'smarthr-ui-TimePicker',
ホンマや忘れてました！対応します 🙏

2024-10-23 08:50 UTC, zoshigayan commented on packages/smarthr-ui/src/components/Picker/style.ts
> +      'smarthr-ui-TimePicker',
対応しましたっ https://github.com/kufu/smarthr-ui/pull/5030/commits/eaea335716fbbf1da26b49efc7d6e06086e0b3a6

2024-10-23 11:14 UTC, uknmr approved these changes
LGTM~

2024-10-24 00:47 UTC, zoshigayan commented
ありがとうございます！マージしてしまいますっ

2024-10-24 00:47 UTC, merged