Improve radio button story
kufu/smarthr-ui pull request #5063
Opened 2024-10-28 00:33 UTC by uknmr

## 関連URL
https://smarthr.atlassian.net/browse/SHRUI-1103

## 概要

#4949 の方針に沿って RadioButton と RadioButtonPanel の Story を見直しました。

## 変更内容

## 確認方法

Storybook や Chromatic で確認してください。

2024-10-30 07:24 UTC, s-sasaki-0529 requested changes
一点だけコメントしました！あとは良さそうです！

2024-10-30 07:24 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/RadioButtonPanel/stories/RadioButtonPanel.stories.tsx
> +  },
ここ、`as` の定義がないと Playground とか Controls 全般でクラッシュしちゃいます ><

2024-10-31 02:47 UTC, uknmr commented on packages/smarthr-ui/src/components/RadioButtonPanel/stories/RadioButtonPanel.stories.tsx
> +  },
修正しました! 8e3af660

2024-10-31 07:52 UTC, s-sasaki-0529 approved these changes

2024-10-31 08:33 UTC, merged