docs(Switch): Story を見直し
kufu/smarthr-ui pull request #5091
Opened 2024-11-11 01:22 UTC by misako0927

## 関連URL

- https://smarthr.atlassian.net/browse/SHRUI-1154

## 概要

#4949 の方針に沿って、Switch の Story を見直しました。

## 変更内容

## 確認方法

Storybook や Chromatic で確認してください。

2024-11-11 02:42 UTC, uknmr commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> + * $ pict input.pict
```suggestion
 * $ pict switch.pict
```

2024-11-11 02:42 UTC, uknmr commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +    <Stack align="flex-start">
wrapper の focus-visible に対する VRT がほしいです!（ここの実装、バギーで storybook 上でフォーカス出ないので意味ないかもしれないけど）
参考： https://github.com/kufu/smarthr-ui/blob/master/packages/smarthr-ui/src/components/Pagination/stories/VRTPagination.stories.tsx#L32

2024-11-11 12:06 UTC, misako0927 commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +    <Stack align="flex-start">
@uknmr 追加しました！が、あってるのか・・？不安なので見ていただけると嬉しいです🙏
https://github.com/kufu/smarthr-ui/pull/5091/commits/d7fb1994bd8735f61aa42103fd4ae157b565ed13

2024-11-11 23:43 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +    <Stack align="flex-start">
FocusVisible できてなさそうなのと、そもそも Switch にフォーカスあてられない…？ Tab で移動できない気がする。
https://www.chromatic.com/test?appId=63d0ccabb5d2dd29825524ab&id=6731f38403dde64a2423d520

2024-11-12 02:29 UTC, uknmr commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +    <Stack align="flex-start">
@s-sasaki-0529 RadioButtonPanel でも発生しているんですが、`has(:focus-visible)` が Storybook では表示されない不具合のせいかと思います。sandbox 環境などで試すと表示されるはず。

2024-11-12 02:37 UTC, uknmr commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +      focusVisible: ['#focus-visible input'],
[wrapper に対して `has(:focus-visible)` が指定されている](https://github.com/kufu/smarthr-ui/blob/abf754dbebe83815b7e30600660a548b791054ea/packages/smarthr-ui/src/components/Switch/Switch.tsx#L17)ので、input だと対象になりません。
wrapper に `smarthr-ui-Switch` を足して、`focusVisible: ['#focus-visible .smarthr-ui-Switch']` とすると良いように思いました!
<img width="415" alt="image" src="https://github.com/user-attachments/assets/d4442617-c26a-4c8e-a9bf-747d60c433d6">

2024-11-12 02:44 UTC, s-sasaki-0529 commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +    <Stack align="flex-start">
あー！そのパターンいつも忘れて辛い…。

2024-11-13 23:55 UTC, uknmr requested changes

2024-11-13 23:55 UTC, uknmr commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +      focusVisible: ['#focus-visible .smarthr-ui-Switch'],
switch の Wrapper に `'smarthr-ui-Switch',` を足す必要があります。
https://github.com/kufu/smarthr-ui/blob/fbc2902b66e8867eeea2bac969f6ed55fc0aa190/packages/smarthr-ui/src/components/Switch/Switch.tsx#L11

2024-11-13 23:57 UTC, misako0927 commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +      focusVisible: ['#focus-visible input'],
入れたのですがChromaticでは見えない感じですね・・・😓has(:focus-visible) が Storybook では表示されない不具合のせいですかね・・・？

2024-11-14 00:13 UTC, misako0927 commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +      focusVisible: ['#focus-visible .smarthr-ui-Switch'],
https://github.com/kufu/smarthr-ui/pull/5091/files#diff-894ed6d266c39894c3dad86aa15e29682532b14cfef04c7b3a6d6b4bd5f6e2edR50
これでWrapperにたせてると思っているのですがそこではないですかね・・？🤔

2024-11-14 00:46 UTC, uknmr approved these changes

2024-11-14 00:46 UTC, uknmr commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +      focusVisible: ['#focus-visible .smarthr-ui-Switch'],
見逃してました!
他コンポーネントはオーバーライドを目的とした `smarthr-ui-Hoge` を持っているので、外から渡す発想がなかったです🙏
Switch をオーバーライドする可能性は考えにくいので、この対応で良さそうです!

2024-11-14 00:49 UTC, misako0927 commented
なるほど・・！Switch.tsx側に追加するという意味でしたか。理解ができておらずすみません。
今回の対応でもOKという話ですが、Chromaticでは結局見えておらず、has(:focus-visible) が Storybook では表示されない不具合のせいなのかがわかっていないのですが、その理解であっていますか？

2024-11-14 00:55 UTC, uknmr commented
> has(:focus-visible) が Storybook では表示されない不具合のせい

その理解であっています!

2024-11-14 00:55 UTC, uknmr commented on packages/smarthr-ui/src/components/Switch/stories/VRTSwitch.stories.tsx
> +      focusVisible: ['#focus-visible input'],
ですです!

2024-11-14 00:56 UTC, misako0927 commented
承知しました！

2024-11-14 02:41 UTC, merged