fix(MultiComboBox): itemの比較にitem.labelを参照していたのをやめる
kufu/smarthr-ui pull request #5191
Opened 2024-12-13 07:12 UTC by eatski

## 関連URL
todo

## 概要
close https://github.com/kufu/smarthr-ui/pull/5190

MultiComboBoxのitem同士が同一かどうかの判定でlabelも参照されているが、labelに設定できるJSX.Elementは等価であっても等値ではない場合がありうるので、label同士の === による判定が意図通りになるかはアプリケーションの実装による。

## 変更内容
valueがitems内で一意（valueが同じでlabelが違うitemは無い）という前提を置き、MultiComboBox内でitem同士が同一かどうかの判定を行っていた部分でlabelも参照するのをやめました。

## 確認方法
- コードの確認
- 動作を確認

2024-12-13 07:13 UTC, eatski commented on packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx
> +            <li key={selectedItem.value}>
valueがitems内で一意（valueが同じでlabelが違うitemは無い）という前提を置いたので、keyの設定にlabelは必要ないはず
また、JSX.Elementが渡されると `[Object Object]` が展開されてしまうので修正しました。

2025-01-07 06:25 UTC, uknmr approved these changes
LGTM! ありがとうございます!!

2025-01-07 08:59 UTC, oti requested changes

2025-01-07 08:59 UTC, oti commented on packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx
> +        const matchedSelectedItem = selectedItems.find((item) => item.value === selected.value)
`ラベルがReactNodeの場合（ダミー……テキスト）` を選択しても、ドロップダウン側で選択済みスタイルが当たってないようでした。
どう直せばいいかまで検証できていないのですが、いったんコメントしておきます :bow:

![スクリーンショット 2025-01-07 17 54 03](https://github.com/user-attachments/assets/8711e79f-7c74-4534-9fa7-a6be5010ecc9)

2025-01-07 09:35 UTC, eatski reviewed
いただいた指摘について対応いたしました！

2025-01-07 09:35 UTC, eatski commented on packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx
> +        const matchedSelectedItem = selectedItems.find((item) => item.value === selected.value)
@oti 
確かにそうですね汗

https://63d0ccabb5d2dd29825524ab-huhcsaomhr.chromatic.com/?path=/docs/forms%EF%BC%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%EF%BC%89-multicombobox--docs

こちら修正前も発生はしていたのでデグレというわけではないのですが一緒に直してしまいました〜
ただ、この修正はSingleComboBoxにも波及してます（おそらく同様のバグが修正されているはず）ので軽く動作確認はしておきましたがそちらも問題なさそうでした。

2025-01-07 09:44 UTC, eatski commented
テスト落ちてますが、テストの意図するところが不明なので確認中です

2025-01-07 09:58 UTC, eatski commented
failしているテストケースについて、blameしてみたところこのPRが見つかりました。
どうやらバグを再現するためのテストケースであり正常な動作を担保するためのものではなさそうなので、修正に伴いテストの内容も変更いたしました。

https://github.com/kufu/smarthr-ui/pull/4346

2025-01-07 22:55 UTC, AtsushiM commented
> valueがitems内で一意（valueが同じでlabelが違うitemは無い）という前提

これは大体そうだろうなぁと思いつつ、たまにあるし落とすべきかどうかちょっと迷いますね...
smarthr-uiはreact-innertextを導入しているので対象からテキスト引っこ抜いて比較するという手もありますが、やりすぎっすかね？
https://www.npmjs.com/package/react-innertext

2025-01-08 00:59 UTC, oti commented on packages/smarthr-ui/src/components/ComboBox/MultiComboBox.tsx
> +        const matchedSelectedItem = selectedItems.find((item) => item.value === selected.value)
選択済みスタイルについての修正はこちらも確認できました！ありがとうございます！　

2025-01-08 04:50 UTC, uknmr commented
> 対象からテキスト引っこ抜いて比較

良さそう!

2025-01-10 11:56 UTC, eatski commented
@AtsushiM 

なるほど、アリだと思います〜
そのように対応します！

2025-01-20 10:12 UTC, eatski commented
@AtsushiM 
こちら修正しました〜

2025-01-30 07:07 UTC, oti approved these changes
LGTM!

2025-02-05 04:49 UTC, merged