feat: FormControl,Fieldsetのtitleにアイコンやボタンを含めずマークアップできるよう属性を追加
kufu/smarthr-ui pull request #5235
Opened 2024-12-31 00:17 UTC by AtsushiM

## 関連URL

## 概要

## 変更内容

## 確認方法

2025-01-02 04:05 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Fieldset/stories/VRTFieldset.stories.tsx
> +    subActionArea: 'サブアクションエリア',
属性名は検討中です。
他に良さそうな名前があれば 🙏

2025-01-02 04:07 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +  innerMargin?: PositiveGap
これまではnegativeな値もinnerMarginに設定できる状態でしたが、想定はされていないロジックになっていました。
スタイル生成ロジックの共通化の影響で型エラーが起きるようになってしまったため、positiveな値のみの型を定義しなおしました

2025-01-02 04:09 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +    label: ['smarthr-ui-FormControl-label', 'shr-float-left', 'shr-px-[unset]'],
FormControlはほぼそのままFieldsetコンポーネントからそのまま再利用されています。
FormControlのlabel要素なら制約はありませんが、Fieldsetのlegendは fieldset直下にlegendが存在しなければアクセシビリティの名前として正常にひも付きません。
そのためLayout系コンポーネントでUI調整が行えないため、古典的なfloatでのUI調整を行っています

2025-01-06 00:19 UTC, AtsushiM commented
📝 VisuallyHiddenでlegendを表現する案が出たため再実装する

2025-01-06 03:10 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +        {isRoleGroup && <VisuallyHiddenText as="legend">{body}</VisuallyHiddenText>}
(相談) bodyをそのまま埋め込んでいますが、innerTextするかどうか悩んでいます。
基本的にマークアップとしては同じ意味になるはずですが、読み上げなどに影響する可能性があるかも？と思い念の為そのまま埋め込んでいます

2025-01-06 04:48 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +        <Cluster justify="space-between" className="!shr-mt-0">
📝 legendが存在する場合、Stack内に先んじる要素が存在することになるので上部に余計な余白が生じてしまう。
見た目上必ず先頭の要素となるため、importantなmargin-top: 0 を設定し、潰しています

2025-01-06 07:40 UTC, uknmr requested changes
全部見きれてないんですが、一旦コメントします!

- スタイリングは tailwind-variants に寄せたい
- 早期 return の方が可読性は高そう（不用意なコード差分も出るのでレビューコストも上がってるように感じる）

2025-01-06 07:40 UTC, uknmr commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +  errorMessages.length > 0 ? (
ask: 早期 return をやめる必要はありそうですか? 元のコードの方が可読性が高く見えます。

2025-01-06 07:40 UTC, uknmr commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +  const actualErrorMessages = useMemo(
imo: これも早期 return を残すでよさそう

2025-01-06 07:40 UTC, uknmr commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +    const clusterAttrs = isRoleGroup
should: Cluster が複数あるので認識しにくいので、適切な名前を与えたい

2025-01-06 07:40 UTC, uknmr commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +          className="!shr-mt-0"
must: コメントがほしい & important はやめたい

2025-01-07 22:57 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +  errorMessages.length > 0 ? (
他は全部↑と同じ三項演算でreturnしてたんで揃えた感じですね

2025-01-07 23:21 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +          className="!shr-mt-0"
importantつけないとselectorの強さ的に勝てないんですが &&& とかで回避する感じです？

2025-01-08 00:49 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> -  statusLabelProps = [],
errorMessagesと合わせてuseMemoの中で空配列を代入するように変更しました。
ロジックを合わせる & memoの中で判定が行われるようになり、多少早いはず

2025-01-08 00:50 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> -        const inputLabelledByIds = input.getAttribute('aria-labelledby')
isInputFile が true の場合のみ inputLabelledByIds の計算が必要だったため、移動しています

2025-01-08 00:50 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +    if (describedbyIds) {
describedbyIds が存在しない限り、すべてのロジックが不要だったのでifを調整しています

2025-01-08 07:55 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Fieldset/Fieldset.tsx
> +  Omit<ComponentProps<typeof ActualFormControl>, 'as' | 'htmlFor' | 'labelId'>
Fieldsetコンポーネントに置いて、htmlForとlabelIdを設定する利用方法が存在しないためomitします

2025-01-08 07:57 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> -      aria-labelledby={isRoleGroup ? managedLabelId : undefined}
古から何故かaria-labelledbyが設定されていましたが、恐らく `fieldset直下でなければlegendとうまく紐づかない` 問題の回避のための属性だったと思われます。
VisuallyHiddenでlegendを直下に設置するようにしたことで正常に紐づく状態になっているため、削除しています

2025-01-08 07:58 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +        {isRoleGroup && <VisuallyHiddenText as="legend">{innerText(body)}</VisuallyHiddenText>}
innerTextは大体の利用方法で問題はないはずですが、titleはReactNodeを受け取るので、念の為textを引っこ抜いてます

2025-01-08 12:48 UTC, uknmr reviewed
BREAKING CHANGE する必要ありそうですか?

あと Chromatic の diff 見たかったけど何故か unchanged だった。
![image](https://github.com/user-attachments/assets/0defaa37-ee36-4db9-b6f4-a8366c810fb2)

2025-01-08 12:48 UTC, uknmr commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +        {isRoleGroup && <VisuallyHiddenText as="legend">{innerText(body)}</VisuallyHiddenText>}
こっちを `hidden` にすれば後続の Cluster の margin を調整する必要はないかも?（`hidden` 使うとWAI-ARIA で紐づける必要が出ちゃうからか?

2025-01-08 12:48 UTC, uknmr commented on packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx
> +        <TextLink href="https://www.google.com/">外部リンク</TextLink>
example.com か `#` や `/` でも良さそう（外部リンクってラベルだけど）

2025-01-08 22:23 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +        {isRoleGroup && <VisuallyHiddenText as="legend">{innerText(body)}</VisuallyHiddenText>}
↑ですね

2025-01-08 22:25 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +        {isRoleGroup && <VisuallyHiddenText as="legend">{innerText(body)}</VisuallyHiddenText>}
せっかくVisuallyHiddenまで使ってfieldset直下にlegend置いてるのでariaで紐づけるよりは...と思っています

2025-01-08 22:31 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +  errorMessages.length > 0 ? (
> 揃える必要があるのかも気になります

あえて断言しますがあります。
ファイル内でルールなく記法がブレることは作為的なものか未作為なのかがわからず、意図を読み取ろうとしたりする開発者（私とか）が現れ、目に見えずらいコストが発生し始めるからです（この問題を防ぐためにlint, autoformatが存在しているとすら思っています）

どちらでも良くないか？みたいなものなら可能な限りファイル内で記法を揃えるべきです。

2025-01-08 22:35 UTC, AtsushiM commented
> BREAKING CHANGE する必要ありそうですか?


https://github.com/kufu/smarthr-ui/pull/5235#discussion_r1906656640

↑の状況を発見、調整し、↓のようにhtmlForとlabelIdが不要なpropsになりそうだったため、属性からomitしています

https://github.com/kufu/smarthr-ui/pull/5235#discussion_r1906651062

2025-01-08 22:46 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx
> +        <TextLink href="https://www.google.com/">外部リンク</TextLink>
ここ悩んでいたんですが 

- 実際に使われそうなもの (リンクとかボタンとか)
- `サブアクションエリア` みたいなアタリとかわかる文言

みたいなのってどっちが良いんですかね？

2025-01-08 23:39 UTC, uknmr commented on packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx
> +        <TextLink href="https://www.google.com/">外部リンク</TextLink>
ややブレてるんですが、どちらかといえば `サブアクションエリア` のようなアタリの方が読み解きは少なく済むのかなぁ、と思っています!
![image](https://github.com/user-attachments/assets/2bc942ed-9749-47fe-bf02-bb295dabfeab)
![image](https://github.com/user-attachments/assets/5122083c-4a73-4d88-945a-7a30c2796620)
![image](https://github.com/user-attachments/assets/80bf7643-2aa3-4de7-a6ae-61cad226e67f)

2025-01-09 04:23 UTC, uknmr approved these changes
LGTM~

2025-01-09 04:23 UTC, uknmr commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
> +  errorMessages.length > 0 ? (
すいません、主語が足りてなかった。このファイル上で早期 return をやめたり、一部だけ揃える必要があるように見えなかったと思っただけで、全体で揃える必要性はわかります。

2025-01-09 04:24 UTC, uknmr commented on packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx
> +        <TextLink href="https://www.google.com/">外部リンク</TextLink>
ABC
DEF
のところも
サブアクションエリア（start)
サブアクションエリア（end)
とすると丁寧なのかしら（props として渡してる Cluster だから不要な気はする）

2025-01-09 04:29 UTC, AtsushiM commented on packages/smarthr-ui/src/components/FormControl/FormControl.tsx
>    const isRoleGroup = as === 'fieldset'
下からisRoleGroupという変数名だったんでそのままにしてた感じですね。
俺もisFieldsetほうが直感的という派閥なんで修正しちゃいます

2025-01-09 04:31 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx
> +        <TextLink href="https://www.google.com/">外部リンク</TextLink>
Clusterは使って

`サブアクションエリア左` `サブアクションエリア右`

みたいな感じで設置することにします

2025-01-09 04:36 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx
> +        <TextLink href="https://www.google.com/">外部リンク</TextLink>
> props として渡してる Cluster だから不要な気はする

悩ましいんですが、ほとんどの場合でCluster使いそうなんで書いといたほうが良い気がしており...

2025-01-09 04:36 UTC, AtsushiM commented on packages/smarthr-ui/src/components/Fieldset/stories/Fieldset.stories.tsx
> +        <TextLink href="https://www.google.com/">外部リンク</TextLink>
領域がちゃんとひろがっているよねぇという確認できるしClusterは残しておきます

2025-01-09 22:42 UTC, merged